//! htlcmax admission valve parity, pinned by `fixtures/golden/htlcmax/*.json`
//! — a byte-for-byte vendored copy of
//! `~/bin/cl_revenue_ops-port/tests/golden/fixtures/htlcmax/` (12 files:
//! 8 `compute_htlcmax_msat` scenarios + `test_htlcmax_hand_computed_anchor`'s
//! sibling case + 4 `delta_exceeds_deadband` cases), generated by
//! `tests/golden/test_golden_htlcmax.py` against the real
//! `FeeController._compute_dynamic_htlcmax_msat` /
//! `_htlcmax_delta_exceeds_deadband` shims, which delegate verbatim to
//! `modules/admission_policy.py`.
//!
//! Defaults (`test_golden_htlcmax.py::_cfg`): `enable_dynamic_htlcmax=True,
//! htlcmax_source_pct=0.85, htlcmax_sink_pct=0.25,
//! htlcmax_balanced_pct=0.50`, overlaid per-case by `inputs.cfg_overrides`.

use revops_fees::admission::{compute_htlcmax_msat, delta_exceeds_deadband, HtlcmaxCfg};
use serde_json::Value;
use std::path::{Path, PathBuf};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/golden/htlcmax")
}

fn load(name: &str) -> Value {
    let path = fixtures_dir().join(format!("{name}.json"));
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("valid JSON")
}

const HTLCMAX_SCENARIOS: &[&str] = &[
    "disabled_returns_none",
    "string_true_enables",
    "source_ample_spendable",
    "sink_small_share",
    "balanced_mid_share",
    "depletion_caps_target",
    "floor_wins_when_depleted",
    "zero_capacity_none",
];

const DEADBAND_SCENARIOS: &[&str] = &[
    "deadband_equal_no_broadcast",
    "deadband_zero_current_always",
    "deadband_tiny_move",
    "deadband_big_move",
];

/// `test_golden_htlcmax.py::_cfg` defaults, overlaid with `cfg_overrides`.
fn cfg_from_overrides(overrides: &Value) -> HtlcmaxCfg {
    let mut enable = Value::Bool(true);
    let mut source_pct = 0.85;
    let mut sink_pct = 0.25;
    let mut balanced_pct = 0.50;

    if let Some(obj) = overrides.as_object() {
        if let Some(v) = obj.get("enable_dynamic_htlcmax") {
            enable = v.clone();
        }
        if let Some(v) = obj.get("htlcmax_source_pct") {
            source_pct = v.as_f64().expect("source pct number");
        }
        if let Some(v) = obj.get("htlcmax_sink_pct") {
            sink_pct = v.as_f64().expect("sink pct number");
        }
        if let Some(v) = obj.get("htlcmax_balanced_pct") {
            balanced_pct = v.as_f64().expect("balanced pct number");
        }
    }

    HtlcmaxCfg {
        enable_dynamic_htlcmax: enable,
        htlcmax_source_pct: source_pct,
        htlcmax_sink_pct: sink_pct,
        htlcmax_balanced_pct: balanced_pct,
    }
}

#[test]
fn golden_htlcmax_all_scenarios() {
    for name in HTLCMAX_SCENARIOS {
        let doc = load(name);
        let inputs = &doc["inputs"];
        let cfg = cfg_from_overrides(&inputs["cfg_overrides"]);
        let channel_info = &inputs["channel_info"];
        let capacity_sats = channel_info["capacity"].as_i64().expect("capacity int");
        let spendable_msat = channel_info["spendable_msat"]
            .as_i64()
            .expect("spendable int");
        let flow_state = inputs["flow_state"].as_str().expect("flow_state string");

        let got = compute_htlcmax_msat(&cfg, capacity_sats, spendable_msat, flow_state);
        let expected = doc["htlcmax_msat"].as_i64();

        assert_eq!(got, expected, "scenario {name}: inputs={inputs}");
    }
}

#[test]
fn golden_htlcmax_deadband_all_scenarios() {
    for name in DEADBAND_SCENARIOS {
        let doc = load(name);
        let inputs = &doc["inputs"];
        let new_msat = inputs["new_msat"].as_i64().expect("new_msat int");
        let current_msat = inputs["current_msat"].as_i64().expect("current_msat int");
        let expected = doc["exceeds"].as_bool().expect("exceeds bool");

        assert_eq!(
            delta_exceeds_deadband(new_msat, current_msat),
            expected,
            "scenario {name}: new={new_msat} current={current_msat}"
        );
    }
}

/// Boundary case NOT present in the vendored golden set: `|delta| ==
/// current * 0.10` exactly must be `false` (strict `>`, not `>=`).
/// current_msat = 1_000_000_000, delta = 100_000_000 == current * 0.10
/// exactly (both integers with an exact f64 representation).
#[test]
fn deadband_boundary_equal_to_threshold_is_false() {
    let current_msat = 1_000_000_000i64;
    let new_msat = current_msat + 100_000_000;
    assert!((new_msat - current_msat) as f64 == current_msat as f64 * 0.10);
    assert!(!delta_exceeds_deadband(new_msat, current_msat));
}

/// Byte-identity guard: when the Python port checkout is available, every
/// vendored fixture's bytes must equal the source file's bytes exactly.
/// Skipped (not failed) when neither `REVOPS_PY_CORPUS` nor the default
/// `~/bin/cl_revenue_ops-port` checkout exists, so CI environments without
/// the sibling repo still pass.
#[test]
fn vendored_fixtures_are_byte_identical_to_python_source() {
    let source_root: PathBuf = if let Ok(p) = std::env::var("REVOPS_PY_CORPUS") {
        PathBuf::from(p)
    } else if let Some(home) = std::env::var_os("HOME") {
        PathBuf::from(home).join("bin/cl_revenue_ops-port")
    } else {
        return;
    };
    let source_dir = source_root.join("tests/golden/fixtures/htlcmax");
    if !source_dir.is_dir() {
        eprintln!(
            "skipping byte-identity guard: {} not found",
            source_dir.display()
        );
        return;
    }

    let vendored_dir = fixtures_dir();
    let mut checked = 0usize;
    for entry in std::fs::read_dir(&vendored_dir).expect("read vendored dir") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let file_name = path.file_name().expect("file name");
        let source_path: &Path = &source_dir.join(file_name);
        let vendored_bytes = std::fs::read(&path).expect("read vendored file");
        let source_bytes = std::fs::read(source_path)
            .unwrap_or_else(|e| panic!("read source {}: {e}", source_path.display()));
        assert_eq!(
            vendored_bytes,
            source_bytes,
            "{} diverged from vendored source",
            file_name.to_string_lossy()
        );
        checked += 1;
    }
    assert_eq!(checked, 12, "expected 12 vendored htlcmax fixtures");
}

#[test]
fn vendored_fixture_count_is_twelve() {
    let count = std::fs::read_dir(fixtures_dir())
        .expect("read fixtures dir")
        .filter(|e| {
            e.as_ref()
                .map(|e| e.path().extension().and_then(|x| x.to_str()) == Some("json"))
                .unwrap_or(false)
        })
        .count();
    assert_eq!(count, 12);
}
