//! Golden + generator-fixture replay for `revops_fees::floors`.
//!
//! Sources:
//! - `fixtures/golden/fee/floor_*.json` — byte-for-byte vendored copies of
//!   `tests/golden/fixtures/fee/` in `cl_revenue_ops-port`.
//! - `fixtures/fees/floors/*.json` — generated by
//!   `tools/port/gen_fees_fixtures.py floors` in the port worktree, calling
//!   the real `FeeController`/`ChainCostDefaults` methods directly (the
//!   oracle; nothing here reimplements the algorithm).
//!
//! Float inputs/expectations are CPython `repr(float)` strings; outputs
//! compare via `py_repr(actual) == expected` — bit-for-bit, no epsilon
//! (Phase 4 Global Constraints).

use revops_econ::pyfloat::py_repr;
use revops_fees::floors::{
    calculate_floor, detect_congestion, dynamic_chain_costs, effective_min_fee_ppm,
    flow_adjusted_ceiling, is_flow_balanced_router, rebalance_cost_floor, ChainCosts, FlowStateRow,
    FlowWindow, LiveHtlc, MinFeeCfg, PeerLatency, RebalanceCostSample, CHANNEL_CLOSE_COST_SATS,
    CHANNEL_LIFETIME_DAYS, CHANNEL_OPEN_COST_SATS, DAILY_VOLUME_SATS, FLOW_BALANCED_MAX_NET_RATIO,
    FLOW_BALANCED_MIN_WEEKLY_TURNOVER, FLOW_BALANCED_WINDOW_SECONDS, REBALANCE_FLOOR_MARGIN,
    REBALANCE_FLOOR_MIN_SAMPLES, REBALANCE_FLOOR_WINDOW_DAYS, SATURATED_OUTBOUND_RATIO,
};
use serde_json::Value;
use std::path::PathBuf;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn read_json(rel: &str) -> Value {
    let path = repo_root().join(rel);
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("valid JSON")
}

fn golden_fixture(name: &str) -> Value {
    read_json(&format!("fixtures/golden/fee/{name}.json"))
}

fn floors_fixture(name: &str) -> Value {
    read_json(&format!("fixtures/fees/floors/{name}.json"))
}

fn parse_chain_costs(v: &Value) -> Option<ChainCosts> {
    if v.is_null() {
        return None;
    }
    Some(ChainCosts {
        open_cost_sats: v["open_cost_sats"].as_i64().unwrap(),
        close_cost_sats: v["close_cost_sats"].as_i64().unwrap(),
        sat_per_vbyte: v
            .get("sat_per_vbyte")
            .and_then(|x| x.as_f64())
            .unwrap_or(0.0),
    })
}

fn parse_peer_latency(v: &Value) -> Option<PeerLatency> {
    if v.is_null() {
        return None;
    }
    Some(PeerLatency {
        avg: v["avg"].as_f64().unwrap(),
        std: v["std"].as_f64().unwrap(),
    })
}

// ---------------------------------------------------------------------------
// calculate_floor — vendored golden replay (byte-for-byte Python fixtures).
// ---------------------------------------------------------------------------

const GOLDEN_FLOOR_SCENARIOS: &[&str] = &[
    "floor_remote_opener_cheaper",
    "floor_small_channel",
    "floor_defaults_no_chain_costs",
    "floor_live_chain_costs_local",
];

#[test]
fn golden_floor_scenarios_replay_exactly() {
    for name in GOLDEN_FLOOR_SCENARIOS {
        let fx = golden_fixture(name);
        let capacity_sats = fx["inputs"]["capacity_sats"].as_i64().unwrap();
        let chain_costs = parse_chain_costs(&fx["inputs"]["chain_costs"]);
        let opener = fx["inputs"]["opener"].as_str().unwrap();

        let floor_ppm = calculate_floor(capacity_sats, chain_costs.as_ref(), None, opener);
        assert_eq!(
            floor_ppm,
            fx["floor_ppm"].as_i64().unwrap(),
            "{name}: floor_ppm"
        );
    }
}

/// ADR-001 stage 1 (rails: floor). Conformance scenario 08 replay pin
/// (capacity 2_000_000, chain_costs None, opener "local" -> 21).
#[test]
fn conformance_scenario_08_fee_rail_floor() {
    assert_eq!(calculate_floor(2_000_000, None, None, "local"), 21);
}

/// The Python `capacity_sats` parameter is genuinely unused by
/// `ChainCostDefaults.calculate_floor_ppm` (config.py:1444-1468) — pin
/// that this vestigial-parameter fidelity holds in the port too.
#[test]
fn capacity_sats_does_not_affect_the_default_floor() {
    let a = calculate_floor(1, None, None, "local");
    let b = calculate_floor(999_999_999, None, None, "local");
    assert_eq!(a, b);
    assert_eq!(a, 21);
}

// ---------------------------------------------------------------------------
// calculate_floor — generator-fixture cases (stall multiplier, risk
// premium, P8-002 regression).
// ---------------------------------------------------------------------------

#[test]
fn calculate_floor_generator_cases_replay_exactly() {
    let fx = floors_fixture("calculate_floor");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let capacity_sats = case["capacity_sats"].as_i64().unwrap();
        let chain_costs = parse_chain_costs(&case["chain_costs"]);
        let peer_latency = parse_peer_latency(&case["peer_latency"]);
        let opener = case["opener"].as_str().unwrap();

        let actual = calculate_floor(
            capacity_sats,
            chain_costs.as_ref(),
            peer_latency.as_ref(),
            opener,
        );
        assert_eq!(
            actual,
            case["expected_floor_ppm"].as_i64().unwrap(),
            "{name}"
        );
    }
}

// ---------------------------------------------------------------------------
// Pinned constants (ChainCostDefaults + FeeController class-body
// constants transcribed for this module).
// ---------------------------------------------------------------------------

#[test]
fn pinned_constants_match_python() {
    let fx = floors_fixture("pinned_constants");
    assert_eq!(
        CHANNEL_OPEN_COST_SATS,
        fx["CHANNEL_OPEN_COST_SATS"].as_i64().unwrap()
    );
    assert_eq!(
        CHANNEL_CLOSE_COST_SATS,
        fx["CHANNEL_CLOSE_COST_SATS"].as_i64().unwrap()
    );
    assert_eq!(
        CHANNEL_LIFETIME_DAYS,
        fx["CHANNEL_LIFETIME_DAYS"].as_i64().unwrap()
    );
    assert_eq!(DAILY_VOLUME_SATS, fx["DAILY_VOLUME_SATS"].as_i64().unwrap());
    assert_eq!(
        REBALANCE_FLOOR_WINDOW_DAYS,
        fx["REBALANCE_FLOOR_WINDOW_DAYS"].as_i64().unwrap()
    );
    assert_eq!(
        REBALANCE_FLOOR_MIN_SAMPLES as i64,
        fx["REBALANCE_FLOOR_MIN_SAMPLES"].as_i64().unwrap()
    );
    assert_eq!(
        py_repr(REBALANCE_FLOOR_MARGIN),
        fx["REBALANCE_FLOOR_MARGIN"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(SATURATED_OUTBOUND_RATIO),
        fx["SATURATED_OUTBOUND_RATIO"].as_str().unwrap()
    );
    assert_eq!(
        FLOW_BALANCED_WINDOW_SECONDS,
        fx["FLOW_BALANCED_WINDOW_SECONDS"].as_i64().unwrap()
    );
    assert_eq!(
        py_repr(FLOW_BALANCED_MAX_NET_RATIO),
        fx["FLOW_BALANCED_MAX_NET_RATIO"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(FLOW_BALANCED_MIN_WEEKLY_TURNOVER),
        fx["FLOW_BALANCED_MIN_WEEKLY_TURNOVER"].as_str().unwrap()
    );
}

// ---------------------------------------------------------------------------
// dynamic_chain_costs — fallback chain + clamp boundaries.
// ---------------------------------------------------------------------------

#[test]
fn dynamic_chain_costs_generator_cases_replay_exactly() {
    let fx = floors_fixture("dynamic_chain_costs");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let perkb = &case["perkb"];
        let expected = &case["expected"];

        let actual = dynamic_chain_costs(perkb);
        if expected.is_null() {
            assert!(actual.is_none(), "{name}: expected None");
            continue;
        }
        let actual = actual.unwrap_or_else(|| panic!("{name}: expected Some"));
        assert_eq!(
            actual.open_cost_sats,
            expected["open_cost_sats"].as_i64().unwrap(),
            "{name}: open_cost_sats"
        );
        assert_eq!(
            actual.close_cost_sats,
            expected["close_cost_sats"].as_i64().unwrap(),
            "{name}: close_cost_sats"
        );
        assert_eq!(
            py_repr(actual.sat_per_vbyte),
            expected["sat_per_vbyte"].as_str().unwrap(),
            "{name}: sat_per_vbyte"
        );
    }
}

// ---------------------------------------------------------------------------
// rebalance_cost_floor — integer-division pin, confidence gating, window
// re-filtering.
// ---------------------------------------------------------------------------

#[test]
fn rebalance_cost_floor_generator_cases_replay_exactly() {
    let fx = floors_fixture("rebalance_cost_floor");
    let now = fx["now"].as_i64().unwrap();
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let flow_state = case["flow_state"].as_str().unwrap();
        let recent_costs: Vec<RebalanceCostSample> = case["recent_costs"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| RebalanceCostSample {
                cost_sats: c["cost_sats"].as_i64().unwrap(),
                amount_sats: c["amount_sats"].as_i64().unwrap(),
                timestamp: c["timestamp"].as_i64().unwrap(),
            })
            .collect();
        let peer_fallback = &case["peer_fallback"];
        let confidence = peer_fallback.get("confidence").and_then(|v| v.as_str());
        let avg_fee_ppm = peer_fallback.get("avg_fee_ppm").and_then(|v| v.as_i64());
        let peer_fallback_opt = match (confidence, avg_fee_ppm) {
            (Some(c), Some(a)) => Some((c, a)),
            _ => None,
        };

        let actual = rebalance_cost_floor(flow_state, &recent_costs, peer_fallback_opt, now);
        let expected = case["expected"].as_i64();
        assert_eq!(actual, expected, "{name}");
    }
}

// ---------------------------------------------------------------------------
// flow_adjusted_ceiling — day boundaries (2.99/3/6.99/7 days).
// ---------------------------------------------------------------------------

#[test]
fn flow_adjusted_ceiling_generator_cases_replay_exactly() {
    let fx = floors_fixture("flow_adjusted_ceiling");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let current_fee = case["current_fee"].as_i64().unwrap();
        let base_ceiling = case["base_ceiling"].as_i64().unwrap();
        let last_forward_ts = case["last_forward_ts"].as_i64();
        let now = case["now"].as_i64().unwrap();

        let actual = flow_adjusted_ceiling(current_fee, base_ceiling, last_forward_ts, now);
        assert_eq!(actual, case["expected"].as_i64().unwrap(), "{name}");
    }
}

// ---------------------------------------------------------------------------
// detect_congestion — live-vs-snapshot resolution, staleness TTL.
// ---------------------------------------------------------------------------

fn parse_flow_state_row(v: &Value) -> Option<FlowStateRow> {
    if v.is_null() {
        return None;
    }
    Some(FlowStateRow {
        state: v.get("state").and_then(|x| x.as_str()).map(String::from),
        updated_at: v.get("updated_at").and_then(|x| x.as_i64()),
    })
}

fn parse_live_htlc(v: &Value) -> Option<LiveHtlc> {
    if v.is_null() {
        return None;
    }
    Some(LiveHtlc {
        has_htlc_data: v["has_htlc_data"].as_bool().unwrap(),
        max_accepted_htlcs: v["max_accepted_htlcs"].as_i64().unwrap(),
        our_htlcs_in_flight: v["our_htlcs_in_flight"].as_i64().unwrap(),
    })
}

#[test]
fn detect_congestion_generator_cases_replay_exactly() {
    let fx = floors_fixture("congestion");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let state = parse_flow_state_row(&case["state"]);
        let channel_info = parse_live_htlc(&case["channel_info"]);
        let threshold: f64 = case["htlc_congestion_threshold"]
            .as_str()
            .unwrap()
            .parse()
            .unwrap();
        let flow_interval = case["flow_interval"].as_i64().unwrap();
        let now = case["now"].as_i64().unwrap();

        let actual = detect_congestion(
            state.as_ref(),
            channel_info.as_ref(),
            threshold,
            flow_interval,
            now,
        );
        assert_eq!(actual, case["expected"].as_bool().unwrap(), "{name}");
    }
}

// ---------------------------------------------------------------------------
// effective_min_fee_ppm / is_flow_balanced_router — class-aware min fee.
// ---------------------------------------------------------------------------

#[test]
fn effective_min_fee_generator_cases_replay_exactly() {
    let fx = floors_fixture("effective_min_fee");
    for case in fx["cases"].as_array().unwrap() {
        let name = case["name"].as_str().unwrap();
        let cfg = MinFeeCfg {
            min_fee_ppm: case["min_fee_ppm"].as_i64().unwrap(),
            min_fee_ppm_saturated: case["min_fee_ppm_saturated"].as_i64().unwrap(),
        };
        let flow_state = case["flow_state"].as_str();
        let outbound_ratio = case["outbound_ratio"]
            .as_str()
            .map(|s| s.parse::<f64>().unwrap());
        let capacity_sats = case["capacity_sats"].as_i64().unwrap();
        let flow_window = case["flow_window"].as_array().map(|arr| FlowWindow {
            out_sats: arr[0].as_i64().unwrap(),
            in_sats: arr[1].as_i64().unwrap(),
        });

        let actual = effective_min_fee_ppm(
            &cfg,
            flow_state,
            outbound_ratio,
            capacity_sats,
            flow_window.as_ref(),
        );
        assert_eq!(actual, case["expected"].as_i64().unwrap(), "{name}");
    }
}

#[test]
fn is_flow_balanced_router_boundary_cases() {
    // capacity <= 0 -> false regardless of window.
    assert!(!is_flow_balanced_router(
        0,
        Some(&FlowWindow {
            out_sats: 100,
            in_sats: 100
        })
    ));
    // No window data -> false.
    assert!(!is_flow_balanced_router(1_000_000, None));
    // gross == 0 -> false.
    assert!(!is_flow_balanced_router(
        1_000_000,
        Some(&FlowWindow {
            out_sats: 0,
            in_sats: 0
        })
    ));
    // Exactly at the minimum weekly turnover boundary AND at the max net
    // ratio boundary (both `<=`/inclusive per py 2806/2809): balanced.
    // gross = capacity * 0.25 = 250_000; net_ratio = 0.33 exactly.
    let out = 166_250i64; // (gross + net*gross)/2 with net=0.33, gross=250_000
    let in_ = 250_000 - out;
    assert!(is_flow_balanced_router(
        1_000_000,
        Some(&FlowWindow {
            out_sats: out,
            in_sats: in_
        })
    ));
}
