//! Golden + generator-fixture replay for `revops_fees::{profiles, rails}`.
//!
//! Sources:
//! - `fixtures/golden/fee/damping_*.json` — byte-for-byte vendored copies
//!   of `tests/golden/fixtures/fee/` in `cl_revenue_ops-port`
//!   (`tests/golden/test_golden_fee_damping.py::DAMPING_SCENARIOS`).
//! - `fixtures/fees/rails/*.json` — generated by
//!   `tools/port/gen_fees_fixtures.py rails` in the port worktree, calling
//!   the real `FeeController`/`GaussianThompsonState` methods directly (the
//!   oracle; nothing here reimplements the algorithm).
//!
//! Float inputs/expectations are CPython `repr(float)` strings; outputs
//! compare via `py_repr(actual) == expected` — bit-for-bit, no epsilon
//! (Phase 4 Global Constraints).

use revops_econ::pyfloat::py_repr;
use revops_fees::profiles::{
    fee_profile, FeeProfileSettings, ACTIVE_PROFILE, CONSERVATIVE_PROFILE,
    EXPLORATION_FEE_MULTIPLIER, EXPLORATION_HEADROOM_RATIO, EXPLORATION_MAX_DISCOUNT_RATIO,
    EXPLORATION_SPARSE_HEADROOM_RATIO,
};
use revops_fees::rails::{
    apply_damped_fee_target, apply_zero_flow_ratchet_guard, blend_fee_target,
    exploration_fee_target, exploration_std_threshold, fee_step_cap, is_unroutable_zero_window,
    kalman_demand_factor, target_blend_ratio, zero_flow_streak_thresholds, ZeroFlowInputs,
    GOSSIP_GATE_SUPPRESSION_RATIO, KALMAN_DEMAND_FACTOR_MAX, KALMAN_DEMAND_FACTOR_MIN,
    UNDERCUT_EXPLORATION_STD_THRESHOLD, UNROUTABLE_SPENDABLE_SATS, ZERO_FLOW_ANCHOR_FLOOR_FRAC,
    ZERO_FLOW_DAYS_MODERATE, ZERO_FLOW_DAYS_SEVERE, ZERO_FLOW_DOWNSHIFT_INTERVAL_CYCLES,
    ZERO_FLOW_DOWNSHIFT_RATIO, ZERO_FLOW_DOWNSHIFT_STREAK, ZERO_FLOW_FEE_THRESHOLD,
    ZERO_FLOW_GAP_CAP_HOURS, ZERO_FLOW_GAP_DOWNSHIFT_MULT, ZERO_FLOW_GAP_GUARD_MULT,
    ZERO_FLOW_GUARD_STREAK, ZERO_FLOW_REDUCTION_MODERATE, ZERO_FLOW_REDUCTION_SEVERE,
};
use serde_json::Value;
use std::path::PathBuf;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn golden_fixture(name: &str) -> Value {
    let path = repo_root().join(format!("fixtures/golden/fee/{name}.json"));
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("valid JSON")
}

fn rails_fixture(name: &str) -> Value {
    let path = repo_root().join(format!("fixtures/fees/rails/{name}.json"));
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("valid JSON")
}

fn parse_f(v: &Value) -> f64 {
    v.as_str().expect("repr string").parse().expect("parse f64")
}

fn parse_opt_f(v: &Value) -> Option<f64> {
    if v.is_null() {
        None
    } else {
        Some(parse_f(v))
    }
}

// ---------------------------------------------------------------------------
// Golden damping replay (6 vendored `damping_*.json` files). The golden
// suite pins a custom profile (see `test_golden_fee_damping.py::PROFILE`):
// wake_cycle_max_delta_ratio=0.50, normal_cycle_max_delta_ratio=0.15,
// wake_cycle_min_delta_ppm=25, normal_cycle_min_delta_ppm=10.
// ---------------------------------------------------------------------------

const GOLDEN_PROFILE: FeeProfileSettings = FeeProfileSettings {
    min_observation_hours: 0.0,
    min_forwards_for_signal: 0,
    dts_discount_gamma: 0.0,
    dts_sparse_discount_gamma: 0.0,
    normal_target_blend_ratio: 0.0,
    wake_target_blend_ratio: 0.0,
    sparse_target_blend_ratio: 0.0,
    normal_cycle_max_delta_ratio: 0.15,
    normal_cycle_min_delta_ppm: 10,
    wake_cycle_max_delta_ratio: 0.50,
    wake_cycle_min_delta_ppm: 25,
};

const DAMPING_SCENARIOS: &[&str] = &[
    "damping_small_raise_within_cap",
    "damping_large_raise_clamped",
    "damping_large_cut_clamped",
    "damping_wake_cycle_wider_cap",
    "damping_low_fee_min_delta_floor",
    "damping_no_change",
];

#[test]
fn golden_damping_scenarios_replay_exactly() {
    for name in DAMPING_SCENARIOS {
        let fx = golden_fixture(name);
        let current = fx["inputs"]["current"].as_i64().unwrap();
        let target = fx["inputs"]["target"].as_i64().unwrap();
        let woke = fx["inputs"]["woke"].as_bool().unwrap();

        let (applied, diag) = apply_damped_fee_target(current, target, woke, &GOLDEN_PROFILE);

        assert_eq!(
            applied,
            fx["applied_fee_ppm"].as_i64().unwrap(),
            "{name}: applied_fee_ppm"
        );
        assert_eq!(
            diag.requested_delta_ppm,
            fx["diag"]["requested_delta_ppm"].as_i64().unwrap(),
            "{name}: requested_delta_ppm"
        );
        assert_eq!(
            diag.max_delta_ppm,
            fx["diag"]["max_delta_ppm"].as_i64().unwrap(),
            "{name}: max_delta_ppm"
        );
        assert_eq!(
            diag.cap_reason,
            fx["diag"]["cap_reason"].as_str().unwrap(),
            "{name}: cap_reason"
        );
        assert_eq!(
            diag.cap_applied,
            fx["diag"]["cap_applied"].as_bool().unwrap(),
            "{name}: cap_applied"
        );
        assert_eq!(
            diag.wake_damping_applied,
            fx["diag"]["wake_damping_applied"].as_bool().unwrap(),
            "{name}: wake_damping_applied"
        );
    }
}

/// Non-golden anchor mirrored from `test_damping_hand_computed_anchor` in
/// the Python suite: 1000 -> 5000 normal cycle caps at
/// `1000 + max(10, ceil(1000*0.15)) = 1150`.
#[test]
fn damping_hand_computed_anchor() {
    let (applied, diag) = apply_damped_fee_target(1000, 5000, false, &GOLDEN_PROFILE);
    assert_eq!(applied, 1150);
    assert!(diag.cap_applied);
    assert_eq!(diag.cap_reason, "normal_cycle_delta_cap");
}

// ---------------------------------------------------------------------------
// Byte-identity guard: vendored fee/ goldens == port-worktree source bytes.
// ---------------------------------------------------------------------------

const ALL_VENDORED_FEE_FIXTURES: &[&str] = &[
    "damping_small_raise_within_cap",
    "damping_large_raise_clamped",
    "damping_large_cut_clamped",
    "damping_wake_cycle_wider_cap",
    "damping_low_fee_min_delta_floor",
    "damping_no_change",
    "floor_defaults_no_chain_costs",
    "floor_live_chain_costs_local",
    "floor_remote_opener_cheaper",
    "floor_small_channel",
];

fn resolve_source_dir() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("REVOPS_PY_CORPUS") {
        let pb = PathBuf::from(p).join("tests/golden/fixtures/fee");
        return pb.is_dir().then_some(pb);
    }
    let home = std::env::var("HOME").ok()?;
    let default = PathBuf::from(home).join("bin/cl_revenue_ops-port/tests/golden/fixtures/fee");
    default.is_dir().then_some(default)
}

#[test]
fn fee_goldens_are_byte_identical_to_source() {
    let Some(source) = resolve_source_dir() else {
        eprintln!("skip fee_goldens_are_byte_identical_to_source: source not found");
        return;
    };
    for name in ALL_VENDORED_FEE_FIXTURES {
        let filename = format!("{name}.json");
        let a = std::fs::read(source.join(&filename))
            .unwrap_or_else(|e| panic!("read source {filename}: {e}"));
        let b = std::fs::read(repo_root().join("fixtures/golden/fee").join(&filename))
            .unwrap_or_else(|e| panic!("read vendored {filename}: {e}"));
        assert_eq!(a, b, "byte drift in {filename}");
    }
}

#[test]
fn all_ten_fee_goldens_are_vendored() {
    let dir = repo_root().join("fixtures/golden/fee");
    let mut found: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .collect();
    found.sort();
    let mut expected: Vec<String> = ALL_VENDORED_FEE_FIXTURES
        .iter()
        .map(|n| format!("{n}.json"))
        .collect();
    expected.sort();
    assert_eq!(found, expected, "vendored fee/ fixture set drifted");
}

// ---------------------------------------------------------------------------
// profiles.json: both FEE_PROFILES tables + name-resolution fallback.
// ---------------------------------------------------------------------------

fn assert_settings_match(settings: &FeeProfileSettings, expected: &Value) {
    assert_eq!(
        py_repr(settings.min_observation_hours),
        expected["min_observation_hours"].as_str().unwrap()
    );
    assert_eq!(
        settings.min_forwards_for_signal,
        expected["min_forwards_for_signal"].as_i64().unwrap()
    );
    assert_eq!(
        py_repr(settings.dts_discount_gamma),
        expected["dts_discount_gamma"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(settings.dts_sparse_discount_gamma),
        expected["dts_sparse_discount_gamma"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(settings.normal_target_blend_ratio),
        expected["normal_target_blend_ratio"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(settings.wake_target_blend_ratio),
        expected["wake_target_blend_ratio"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(settings.sparse_target_blend_ratio),
        expected["sparse_target_blend_ratio"].as_str().unwrap()
    );
    assert_eq!(
        py_repr(settings.normal_cycle_max_delta_ratio),
        expected["normal_cycle_max_delta_ratio"].as_str().unwrap()
    );
    assert_eq!(
        settings.normal_cycle_min_delta_ppm,
        expected["normal_cycle_min_delta_ppm"].as_i64().unwrap()
    );
    assert_eq!(
        py_repr(settings.wake_cycle_max_delta_ratio),
        expected["wake_cycle_max_delta_ratio"].as_str().unwrap()
    );
    assert_eq!(
        settings.wake_cycle_min_delta_ppm,
        expected["wake_cycle_min_delta_ppm"].as_i64().unwrap()
    );
}

#[test]
fn profile_tables_match_fixture() {
    let fx = rails_fixture("profiles");
    for case in fx["cases"].as_array().unwrap() {
        let input_name = case["input_name"].as_str().unwrap();
        let expected_resolved = case["resolved_name"].as_str().unwrap();
        let (resolved, settings) = fee_profile(input_name);
        assert_eq!(resolved, expected_resolved, "input {input_name:?}");
        assert_settings_match(settings, &case["settings"]);
    }
}

#[test]
fn active_and_conservative_statics_match_fixture() {
    let fx = rails_fixture("profiles");
    let cases = fx["cases"].as_array().unwrap();
    let active_case = cases
        .iter()
        .find(|c| c["input_name"] == "active")
        .expect("active case present");
    assert_settings_match(&ACTIVE_PROFILE, &active_case["settings"]);
    let conservative_case = cases
        .iter()
        .find(|c| c["input_name"] == "conservative")
        .expect("conservative case present");
    assert_settings_match(&CONSERVATIVE_PROFILE, &conservative_case["settings"]);
}

// ---------------------------------------------------------------------------
// step_cap.json
// ---------------------------------------------------------------------------

#[test]
fn fee_step_cap_matches_fixture() {
    let fx = rails_fixture("step_cap");
    for case in fx["cases"].as_array().unwrap() {
        let current = case["current_fee_ppm"].as_i64().unwrap();
        let woke = case["woke_from_sleep"].as_bool().unwrap();
        let profile_name = case["profile_name"].as_str().unwrap();
        let expected = case["expected"].as_i64().unwrap();
        let (_, profile) = fee_profile(profile_name);
        assert_eq!(
            fee_step_cap(current, woke, profile),
            expected,
            "current={current} woke={woke} profile={profile_name}"
        );
    }
}

// ---------------------------------------------------------------------------
// blend_ratio.json / blend_target.json
// ---------------------------------------------------------------------------

#[test]
fn target_blend_ratio_matches_fixture() {
    let fx = rails_fixture("blend_ratio");
    for case in fx["cases"].as_array().unwrap() {
        let std = parse_f(&case["posterior_std"]);
        let woke = case["woke_from_sleep"].as_bool().unwrap();
        let profile_name = case["profile_name"].as_str().unwrap();
        let expected = case["expected"].as_str().unwrap();
        let (_, profile) = fee_profile(profile_name);
        let actual = target_blend_ratio(woke, false, std, profile_name, profile);
        assert_eq!(
            py_repr(actual),
            expected,
            "std={std} woke={woke} profile={profile_name}"
        );
    }
}

#[test]
fn blend_fee_target_matches_fixture() {
    let fx = rails_fixture("blend_target");
    for case in fx["cases"].as_array().unwrap() {
        let current = case["current_fee_ppm"].as_i64().unwrap();
        let bounded_target = case["bounded_target_ppm"].as_i64().unwrap();
        let woke = case["woke_from_sleep"].as_bool().unwrap();
        let sparse = case["sparse_data_conservative"].as_bool().unwrap();
        let std = parse_f(&case["posterior_std"]);
        let profile_name = case["profile_name"].as_str().unwrap();
        let (_, profile) = fee_profile(profile_name);

        let (blended, diag) = blend_fee_target(
            current,
            bounded_target,
            woke,
            sparse,
            std,
            profile_name,
            profile,
        );

        assert_eq!(
            blended,
            case["expected_blended_target_ppm"].as_i64().unwrap(),
            "case {case}"
        );
        let expected_diag = &case["expected_diag"];
        assert_eq!(
            py_repr(diag.blend_ratio),
            expected_diag["blend_ratio"].as_str().unwrap()
        );
        assert_eq!(
            diag.blended_delta_ppm,
            expected_diag["blended_delta_ppm"].as_i64().unwrap()
        );
        assert_eq!(
            diag.sparse_data_conservative,
            expected_diag["sparse_data_conservative"].as_bool().unwrap()
        );
    }
}

// ---------------------------------------------------------------------------
// exploration.json
// ---------------------------------------------------------------------------

#[test]
fn exploration_fee_target_matches_fixture() {
    let fx = rails_fixture("exploration");
    for case in fx["cases"].as_array().unwrap() {
        let current = case["current_fee_ppm"].as_i64().unwrap();
        let floor_ppm = case["floor_ppm"].as_i64().unwrap();
        let cfg_min = case["cfg_min_fee_ppm"].as_i64().unwrap();
        let sparse = case["sparse_data_conservative"].as_bool().unwrap();
        let effective_min = case["effective_min_fee_ppm"].as_i64();
        let expected = case["expected"].as_i64().unwrap();

        let actual = exploration_fee_target(current, floor_ppm, cfg_min, sparse, effective_min);
        assert_eq!(actual, expected, "case {case}");
    }
}

// ---------------------------------------------------------------------------
// zero_flow_thresholds.json
// ---------------------------------------------------------------------------

#[test]
fn zero_flow_streak_thresholds_matches_fixture() {
    let fx = rails_fixture("zero_flow_thresholds");
    for case in fx["cases"].as_array().unwrap() {
        let gap = parse_f(&case["gap_ema_hours"]);
        let cycle = parse_f(&case["cycle_hours"]);
        let expected_guard = case["expected_guard"].as_i64().unwrap();
        let expected_downshift = case["expected_downshift"].as_i64().unwrap();

        let (guard, downshift) = zero_flow_streak_thresholds(gap, cycle);
        assert_eq!(guard, expected_guard, "gap={gap} cycle={cycle} (guard)");
        assert_eq!(
            downshift, expected_downshift,
            "gap={gap} cycle={cycle} (downshift)"
        );
    }
}

// ---------------------------------------------------------------------------
// zero_flow_guard.json
// ---------------------------------------------------------------------------

#[test]
fn zero_flow_ratchet_guard_matches_fixture() {
    let fx = rails_fixture("zero_flow_guard");
    for case in fx["cases"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap();
        let inputs = &case["inputs"];
        let zfi = ZeroFlowInputs {
            current_fee: inputs["current_fee"].as_i64().unwrap(),
            target_fee: inputs["target_fee"].as_i64().unwrap(),
            min_fee: inputs["min_fee"].as_i64().unwrap(),
            zero_revenue_streak: inputs["zero_revenue_streak"].as_i64().unwrap(),
            forwards_since_update: inputs["forwards_since_update"].as_i64().unwrap(),
            revenue_rate: parse_f(&inputs["revenue_rate"]),
            supported_fee_ceiling: parse_opt_f(&inputs["supported_fee_ceiling"]),
            earning_anchor_ppm: parse_opt_f(&inputs["earning_anchor_ppm"]),
            guard_streak: inputs["guard_streak"].as_i64(),
            downshift_streak: inputs["downshift_streak"].as_i64(),
            rate_is_meaningful: inputs["rate_is_meaningful"].as_bool(),
        };

        let (fee, tag) = apply_zero_flow_ratchet_guard(&zfi);
        assert_eq!(fee, case["expected_fee"].as_i64().unwrap(), "{label}: fee");
        let expected_tag = case["expected_tag"].as_str();
        assert_eq!(tag, expected_tag, "{label}: tag");
    }
}

// ---------------------------------------------------------------------------
// kalman.json / std_threshold.json / unroutable.json
// ---------------------------------------------------------------------------

#[test]
fn kalman_demand_factor_matches_fixture() {
    let fx = rails_fixture("kalman");
    for case in fx["cases"].as_array().unwrap() {
        let ed = parse_f(&case["expected_demand"]);
        let expected = case["expected"].as_str().unwrap();
        assert_eq!(py_repr(kalman_demand_factor(ed)), expected, "ed={ed}");
    }
}

#[test]
fn exploration_std_threshold_matches_fixture() {
    let fx = rails_fixture("std_threshold");
    for case in fx["cases"].as_array().unwrap() {
        let fee = case["current_fee_ppm"].as_i64().unwrap();
        let expected = case["expected"].as_str().unwrap();
        assert_eq!(
            py_repr(exploration_std_threshold(fee)),
            expected,
            "fee={fee}"
        );
    }
}

#[test]
fn is_unroutable_zero_window_matches_fixture() {
    let fx = rails_fixture("unroutable");
    for case in fx["cases"].as_array().unwrap() {
        let rate = parse_f(&case["revenue_rate"]);
        let spendable = parse_f(&case["spendable_sats"]);
        let expected = case["expected"].as_bool().unwrap();
        assert_eq!(
            is_unroutable_zero_window(rate, spendable),
            expected,
            "rate={rate} spendable={spendable}"
        );
    }
}

// ---------------------------------------------------------------------------
// Pinned-constants tests (Phase 4 Global Constraints: every constant is
// load-bearing, transcribed verbatim — grep the class body in
// fee_controller.py for each name to re-verify).
// ---------------------------------------------------------------------------

#[test]
fn pinned_zero_flow_constants() {
    assert_eq!(ZERO_FLOW_GUARD_STREAK, 8);
    assert_eq!(ZERO_FLOW_DOWNSHIFT_STREAK, 24);
    assert_eq!(py_repr(ZERO_FLOW_DOWNSHIFT_RATIO), "0.85");
    assert_eq!(ZERO_FLOW_DOWNSHIFT_INTERVAL_CYCLES, 12);
    assert_eq!(py_repr(ZERO_FLOW_ANCHOR_FLOOR_FRAC), "0.5");
    assert_eq!(py_repr(ZERO_FLOW_GAP_GUARD_MULT), "2.0");
    assert_eq!(py_repr(ZERO_FLOW_GAP_DOWNSHIFT_MULT), "4.0");
    assert_eq!(py_repr(ZERO_FLOW_GAP_CAP_HOURS), "168.0");
    assert_eq!(ZERO_FLOW_DAYS_MODERATE, 3);
    assert_eq!(ZERO_FLOW_DAYS_SEVERE, 7);
    assert_eq!(ZERO_FLOW_FEE_THRESHOLD, 500);
    assert_eq!(py_repr(ZERO_FLOW_REDUCTION_MODERATE), "0.75");
    assert_eq!(py_repr(ZERO_FLOW_REDUCTION_SEVERE), "0.5");
}

#[test]
fn pinned_exploration_constants() {
    assert_eq!(py_repr(EXPLORATION_FEE_MULTIPLIER), "1.25");
    assert_eq!(py_repr(EXPLORATION_MAX_DISCOUNT_RATIO), "0.5");
    assert_eq!(py_repr(EXPLORATION_HEADROOM_RATIO), "0.35");
    assert_eq!(py_repr(EXPLORATION_SPARSE_HEADROOM_RATIO), "0.5");
}

#[test]
fn pinned_misc_constants() {
    assert_eq!(UNROUTABLE_SPENDABLE_SATS, 25_000);
    assert_eq!(py_repr(GOSSIP_GATE_SUPPRESSION_RATIO), "0.05");
    assert_eq!(py_repr(KALMAN_DEMAND_FACTOR_MIN), "1.0");
    assert_eq!(py_repr(KALMAN_DEMAND_FACTOR_MAX), "2.0");
    assert_eq!(py_repr(UNDERCUT_EXPLORATION_STD_THRESHOLD), "100.0");
}
