//! Generator-fixture replay for `revops_fees::vegas`.
//!
//! Source: `fixtures/fees/vegas/*.json`, generated by
//! `tools/port/gen_fees_fixtures.py vegas` in the port worktree, calling
//! the real `VegasReflexState.update`/`get_floor_multiplier` directly (the
//! oracle; nothing here reimplements the algorithm).
//!
//! Pins: decay-BEFORE-spike-check ordering, the short-circuited RNG
//! consumption (`random()` called ONLY inside the 2x..4x branch when
//! `consecutive_spikes < 2`), and the `ma_sat_vb <= 0` guard. Floats
//! compare via `py_repr(actual) == expected` — bit-for-bit, no epsilon
//! (Phase 4 Global Constraints).

use revops_econ::pyfloat::py_repr;
use revops_fees::pyrand::PyRandom;
use revops_fees::vegas::{vegas_floor_multiplier, vegas_update, VegasReflexState};
use serde_json::Value;
use std::path::PathBuf;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn vegas_fixture(name: &str) -> Value {
    let path = repo_root().join(format!("fixtures/fees/vegas/{name}.json"));
    let raw =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("valid JSON")
}

fn parse_f(v: &Value) -> f64 {
    v.as_str().expect("repr string").parse().expect("parse f64")
}

/// The default `VegasReflexState` (py dataclass field defaults) matches
/// what `_controller()`-independent Python instantiation produces:
/// intensity 0.0, decay_rate 0.85, last_sat_vb 1.0, last_update 0,
/// consecutive_spikes 0.
#[test]
fn default_state_matches_python_dataclass_defaults() {
    let s = VegasReflexState::default();
    assert_eq!(py_repr(s.intensity), "0.0");
    assert_eq!(py_repr(s.decay_rate), "0.85");
    assert_eq!(py_repr(s.last_sat_vb), "1.0");
    assert_eq!(s.last_update, 0);
    assert_eq!(s.consecutive_spikes, 0);
    assert_eq!(vegas_floor_multiplier(&s), 1.0);
}

/// 12-cycle sequences per seed, pinning `(intensity, consecutive_spikes,
/// floor_multiplier)` after every cycle. Ratios cross the 2x boundary
/// exactly (cycle 1, boost=0.0 — RNG consumed but never triggers),
/// confirmation-window transitions (cycles 2-4, RNG NOT consumed once
/// `consecutive_spikes >= 2`), the 4x immediate trigger (cycles 4, 11 —
/// exactly at the boundary), and decay-only cool-downs (cycles 0, 5, 7,
/// 10).
#[test]
fn vegas_sequences_replay_exactly_per_seed() {
    let fx = vegas_fixture("sequences");
    for entry in fx["entries"].as_array().unwrap() {
        let seed = entry["seed"].as_u64().unwrap();
        let mut rng = PyRandom::seed_from_u64(seed);
        let mut state = VegasReflexState::default();

        for cycle in entry["cycles"].as_array().unwrap() {
            let idx = cycle["cycle"].as_i64().unwrap();
            let now = cycle["now"].as_i64().unwrap();
            let current_sat_vb = parse_f(&cycle["current_sat_vb"]);
            let ma_sat_vb = parse_f(&cycle["ma_sat_vb"]);

            vegas_update(&mut state, current_sat_vb, ma_sat_vb, &mut rng, now);

            assert_eq!(
                py_repr(state.intensity),
                cycle["intensity"].as_str().unwrap(),
                "seed {seed} cycle {idx}: intensity"
            );
            assert_eq!(
                state.consecutive_spikes,
                cycle["consecutive_spikes"].as_i64().unwrap(),
                "seed {seed} cycle {idx}: consecutive_spikes"
            );
            assert_eq!(
                py_repr(vegas_floor_multiplier(&state)),
                cycle["floor_multiplier"].as_str().unwrap(),
                "seed {seed} cycle {idx}: floor_multiplier"
            );
        }
    }
}

/// `ma_sat_vb <= 0` guard (py 2363-2364): clamped to 1.0 before the ratio
/// is computed, so `current_sat_vb=2.5` with `ma_sat_vb<=0` behaves
/// exactly like `ma_sat_vb=1.0` (spike_ratio=2.5, 2x..4x branch).
#[test]
fn ma_leq_zero_guard_replays_exactly() {
    let fx = vegas_fixture("ma_leq_zero_guard");
    let seed = fx["seed"].as_u64().unwrap();
    let now = fx["now"].as_i64().unwrap();
    let mut rng = PyRandom::seed_from_u64(seed);
    let mut state = VegasReflexState::default();

    for (i, cycle) in fx["cycles"].as_array().unwrap().iter().enumerate() {
        let current_sat_vb = parse_f(&cycle["current_sat_vb"]);
        let ma_sat_vb_input = parse_f(&cycle["ma_sat_vb_input"]);
        vegas_update(&mut state, current_sat_vb, ma_sat_vb_input, &mut rng, now);
        assert_eq!(
            py_repr(state.intensity),
            cycle["intensity"].as_str().unwrap(),
            "cycle {i}: intensity"
        );
        assert_eq!(
            state.consecutive_spikes,
            cycle["consecutive_spikes"].as_i64().unwrap(),
            "cycle {i}: consecutive_spikes"
        );
    }
}

// ---------------------------------------------------------------------------
// Hand-computed anchors: decay-before-check invariant and the RNG
// short-circuit trap, independent of the generator (so a regression that
// happens to also break the generator's exact numbers still has a
// second, hand-verified witness).
// ---------------------------------------------------------------------------

/// An immediate 4x+ trigger sets intensity to 1.0; the VERY NEXT cycle
/// (even a sub-2x ratio) must decay from 1.0 first (0.85), not be left at
/// 1.0 or reset to 0.0. This is the "decay BEFORE spike check" invariant.
#[test]
fn decay_before_spike_check_invariant() {
    let mut rng = PyRandom::seed_from_u64(0);
    let mut s = VegasReflexState::default();
    vegas_update(&mut s, 50.0, 10.0, &mut rng, 1_752_400_000); // ratio 5.0 -> immediate 1.0
    assert_eq!(py_repr(s.intensity), "1.0");
    assert_eq!(s.consecutive_spikes, 1);

    vegas_update(&mut s, 5.0, 10.0, &mut rng, 1_752_400_100); // ratio 0.5 -> decay only
    assert_eq!(py_repr(s.intensity), py_repr(1.0 * 0.85));
    assert_eq!(s.consecutive_spikes, 0);
}

/// `consecutive_spikes >= 2` short-circuits `rng.random()` in Python's
/// `or` — the RNG must NOT be consumed on that branch. The check uses
/// `consecutive_spikes` AFTER it is incremented for the CURRENT cycle
/// (py 2372-2376 runs before 2381-2387), so only the FIRST 2x..4x cycle
/// in a run (post-increment count 1, `1 >= 2` false) draws; every
/// subsequent 2x..4x cycle in the same run (post-increment count >= 2)
/// short-circuits and draws nothing.
///
/// Verified by running three consecutive 2x..4x cycles (post-increment
/// counts 1, 2, 3) through one `PyRandom` stream, then confirming the
/// NEXT draw from that stream equals the SECOND draw of a fresh,
/// identically-seeded stream — proving exactly one draw (not three) was
/// consumed across the three `vegas_update` calls.
#[test]
fn confirmed_spike_branch_does_not_consume_rng() {
    let now = 1_752_400_000;
    let mut rng_a = PyRandom::seed_from_u64(7);
    let mut s_a = VegasReflexState::default();
    vegas_update(&mut s_a, 25.0, 10.0, &mut rng_a, now); // consec 0->1 (1>=2 false): draws
    vegas_update(&mut s_a, 25.0, 10.0, &mut rng_a, now); // consec 1->2 (2>=2 true): no draw
    vegas_update(&mut s_a, 25.0, 10.0, &mut rng_a, now); // consec 2->3 (3>=2 true): no draw
    assert_eq!(s_a.consecutive_spikes, 3);

    let mut rng_b = PyRandom::seed_from_u64(7);
    let _first_draw = rng_b.random();
    let second_draw = rng_b.random();
    let next_from_a = rng_a.random();
    assert_eq!(
        py_repr(second_draw),
        py_repr(next_from_a),
        "rng_a should have consumed exactly ONE draw across the three confirmed-spike cycles"
    );
}
