//! Phase 3 Task 7 (Wave 2): demand-flow classifier bit-parity replay
//! against `fixtures/flow.json` (`classify_peers_cases`,
//! `classify_candidate_cases`, `sink_adjacent_cases`), generated by
//! `tools/port/gen_flow_fixtures.py` from the real `modules/demand_flow.py`.

use std::collections::{HashMap, HashSet};

use revops_analytics::classification::ChannelState;
use revops_analytics::demand_flow::{
    classify_candidate, classify_peers, find_sink_adjacent_candidates, NodeFlowProfile,
};
use revops_analytics::flow::FlowMetrics;
use serde_json::Value;

fn fixture() -> Value {
    let raw = include_str!("../../../fixtures/flow.json");
    serde_json::from_str(raw).unwrap()
}

fn bits_to_f64(s: &str) -> f64 {
    assert_eq!(s.len(), 16, "expected a 16-hex-char bit pattern, got {s:?}");
    let mut bytes = [0u8; 8];
    for (i, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("valid hex byte");
    }
    f64::from_bits(u64::from_le_bytes(bytes))
}

fn f64_bits(v: &Value) -> f64 {
    bits_to_f64(v.as_str().expect("expected a hex bit-pattern string"))
}

fn assert_bits_eq(actual: f64, expected: f64, label: &str) {
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{label}: bit mismatch (actual={actual:?} [{:016x}], expected={expected:?} [{:016x}])",
        actual.to_bits(),
        expected.to_bits(),
    );
}

fn flow_metric_stub(peer_id: &str, sats_in: i64, sats_out: i64) -> FlowMetrics {
    FlowMetrics {
        channel_id: format!("stub-{peer_id}"),
        peer_id: peer_id.to_string(),
        sats_in,
        sats_out,
        capacity: 1,
        flow_ratio: 0.0,
        state: ChannelState::Unknown,
        daily_volume: 0,
        is_congested: false,
        confidence: 1.0,
        velocity: 0.0,
        flow_multiplier: 1.0,
        ema_decay: 0.8,
        forward_count: 0,
        kalman_flow_ratio: 0.0,
        kalman_velocity: 0.0,
        kalman_uncertainty: 0.1,
        kalman_regime_change: false,
    }
}

// =============================================================================
// classify_peers
// =============================================================================

#[test]
fn classify_peers_cases_match_python() {
    let data = fixture();
    let cases = data["classify_peers_cases"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let id = case["id"].as_str().unwrap();
        let flows: Vec<FlowMetrics> = case["flows"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| {
                flow_metric_stub(
                    f["peer_id"].as_str().unwrap(),
                    f["sats_in"].as_i64().unwrap(),
                    f["sats_out"].as_i64().unwrap(),
                )
            })
            .collect();

        let profiles = classify_peers(&flows);
        let expected = case["profiles"].as_object().unwrap();

        assert_eq!(
            profiles.len(),
            expected.len(),
            "{id}: profile count mismatch"
        );
        for (pid, exp) in expected {
            let actual = profiles
                .get(pid)
                .unwrap_or_else(|| panic!("{id}: missing profile for peer {pid}"));
            assert_eq!(
                actual.role,
                exp["role"].as_str().unwrap(),
                "{id}[{pid}].role"
            );
            assert_bits_eq(
                actual.confidence,
                f64_bits(&exp["confidence"]),
                &format!("{id}[{pid}].confidence"),
            );
            match (&actual.net_flow_ratio, exp["net_flow_ratio"].as_str()) {
                (None, None) => {}
                (Some(a), Some(_)) => {
                    assert_bits_eq(
                        *a,
                        f64_bits(&exp["net_flow_ratio"]),
                        &format!("{id}[{pid}].net_flow_ratio"),
                    );
                }
                other => panic!("{id}[{pid}]: net_flow_ratio Some/None mismatch: {other:?}"),
            }
        }
    }
}

// =============================================================================
// classify_candidate
// =============================================================================

#[test]
fn classify_candidate_cases_match_python() {
    let data = fixture();
    let cases = data["classify_candidate_cases"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let id = case["id"].as_str().unwrap();
        let node_id = case["node_id"].as_str().unwrap();
        let node_info = match &case["node_info"] {
            Value::Null => None,
            v => Some(v.clone()),
        };
        let channels: Vec<Value> = case["channels"].as_array().unwrap().clone();

        let profile = classify_candidate(node_id, node_info.as_ref(), &channels);

        assert_eq!(profile.role, case["role"].as_str().unwrap(), "{id}.role");
        assert_bits_eq(
            profile.confidence,
            f64_bits(&case["confidence"]),
            &format!("{id}.confidence"),
        );
        assert_eq!(
            profile.has_liquidity_ads,
            case["has_liquidity_ads"].as_bool().unwrap(),
            "{id}.has_liquidity_ads"
        );

        let expected_signals = case["gossip_signals"].as_object().unwrap();
        assert_eq!(
            profile.gossip_signals.len(),
            expected_signals.len(),
            "{id}: gossip_signals count mismatch"
        );
        for (k, v) in &profile.gossip_signals {
            let expected_v = expected_signals
                .get(k)
                .unwrap_or_else(|| panic!("{id}: unexpected gossip signal {k}"));
            assert_bits_eq(
                *v,
                f64_bits(expected_v),
                &format!("{id}.gossip_signals[{k}]"),
            );
        }
    }
}

// =============================================================================
// find_sink_adjacent_candidates
// =============================================================================

fn profile_from_case(node_id: &str, v: &Value) -> NodeFlowProfile {
    NodeFlowProfile {
        node_id: node_id.to_string(),
        role: "sink".to_string(),
        confidence: f64_bits(&v["confidence"]),
        net_flow_ratio: v["net_flow_ratio"]
            .as_str()
            .map(|_| f64_bits(&v["net_flow_ratio"])),
        gossip_signals: Vec::new(),
        has_liquidity_ads: false,
    }
}

#[test]
fn sink_adjacent_cases_match_python() {
    let data = fixture();
    let cases = data["sink_adjacent_cases"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let id = case["id"].as_str().unwrap();
        let order: Vec<String> = case["sink_profiles_order"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();
        let profiles_json = case["sink_profiles"].as_object().unwrap();
        let sink_profiles: Vec<NodeFlowProfile> = order
            .iter()
            .map(|pid| profile_from_case(pid, &profiles_json[pid]))
            .collect();

        let mut sink_channels: HashMap<String, Vec<Value>> = HashMap::new();
        for (pid, chans) in case["sink_channels"].as_object().unwrap() {
            sink_channels.insert(pid.clone(), chans.as_array().unwrap().clone());
        }

        let existing_peers: HashSet<String> = case["existing_peers"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();

        let candidates =
            find_sink_adjacent_candidates(&sink_profiles, &sink_channels, &existing_peers);

        let expected = case["candidates"].as_array().unwrap();
        assert_eq!(
            candidates.len(),
            expected.len(),
            "{id}: candidate count mismatch"
        );
        for (i, (actual, exp)) in candidates.iter().zip(expected.iter()).enumerate() {
            let label = format!("{id}.candidates[{i}]");
            assert_eq!(
                actual.peer_id,
                exp["peer_id"].as_str().unwrap(),
                "{label}.peer_id"
            );
            assert_eq!(
                actual.source,
                exp["source"].as_str().unwrap(),
                "{label}.source"
            );
            assert_bits_eq(
                actual.score,
                f64_bits(&exp["score"]),
                &format!("{label}.score"),
            );
            assert_eq!(
                actual.reason,
                exp["reason"].as_str().unwrap(),
                "{label}.reason"
            );
            assert_eq!(
                actual.sink_peer_id,
                exp["sink_peer_id"].as_str().unwrap(),
                "{label}.sink_peer_id"
            );
            assert_eq!(
                actual.is_sink_adjacent,
                exp["is_sink_adjacent"].as_bool().unwrap(),
                "{label}.is_sink_adjacent"
            );
        }
    }
}

#[test]
fn sink_adjacent_tie_stability_is_insertion_order_not_reversed() {
    let data = fixture();
    let cases = data["sink_adjacent_cases"].as_array().unwrap();

    let forward = cases
        .iter()
        .find(|c| c["id"] == "tie_preserves_original_relative_order")
        .expect("tie case must exist");
    let reversed = cases
        .iter()
        .find(|c| c["id"] == "tie_reversed_insertion_order")
        .expect("reversed tie case must exist");

    let forward_order: Vec<&str> = forward["candidates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c["peer_id"].as_str().unwrap())
        .collect();
    let reversed_order: Vec<&str> = reversed["candidates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c["peer_id"].as_str().unwrap())
        .collect();

    // Same two candidates (equal |net_flow_ratio| -> equal score), opposite
    // insertion order in the two fixture cases -> the OUTPUT order must
    // flip too, proving the sort is insertion-order-stable, not
    // node-id-driven or defeated by a sort-then-reverse implementation.
    assert_eq!(forward_order, vec!["destTieA", "destTieB"]);
    assert_eq!(reversed_order, vec!["destTieB", "destTieA"]);
}
