//! Phase 3 Task 7 (Wave 2): flow-pipeline bit-parity replay against
//! `fixtures/flow.json`, generated by `tools/port/gen_flow_fixtures.py` in
//! the `cl_revenue_ops-port` worktree from the real
//! `modules/flow_analysis.py`.

use revops_analytics::classification::ChannelState;
use revops_analytics::flow::{
    apply_kalman_filter, apply_kalman_reclassification, calculate_adaptive_decay,
    calculate_ema_flow, calculate_velocity, update_temporal_profile, EmaBucket,
    HourlyHistogramBucket, KalmanFilterOutcome, KalmanStep, ReclassificationInput, TemporalProfile,
    BASE_EMA_DECAY, DECAY_RANGE, MAX_VELOCITY, MIN_VELOCITY, TEMPORAL_EMA_ALPHA,
    TEMPORAL_GRADUATION_DAYS, TEMPORAL_MIN_DAILY_FORWARDS, VELOCITY_OUTLIER_THRESHOLD,
};
use revops_analytics::kalman::{DailyBucket, KalmanFlowFilter, KalmanFlowState, NetFlowEntry};
use serde_json::Value;

fn fixture() -> Value {
    let raw = include_str!("../../../fixtures/flow.json");
    serde_json::from_str(raw).unwrap()
}

fn bits_to_f64(s: &str) -> f64 {
    assert_eq!(s.len(), 16, "expected a 16-hex-char bit pattern, got {s:?}");
    let mut bytes = [0u8; 8];
    for (i, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("valid hex byte");
    }
    f64::from_bits(u64::from_le_bytes(bytes))
}

fn f64_bits(v: &Value) -> f64 {
    bits_to_f64(v.as_str().expect("expected a hex bit-pattern string"))
}

fn assert_bits_eq(actual: f64, expected: f64, label: &str) {
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{label}: bit mismatch (actual={actual:?} [{:016x}], expected={expected:?} [{:016x}])",
        actual.to_bits(),
        expected.to_bits(),
    );
}

fn daily_buckets_from(v: &Value) -> Vec<DailyBucket> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|b| DailyBucket {
            out: b["out"].as_f64().unwrap(),
            in_: b["in"].as_f64().unwrap(),
        })
        .collect()
}

fn state_from_json(v: &Value) -> KalmanFlowState {
    KalmanFlowState {
        flow_ratio: f64_bits(&v["flow_ratio"]),
        flow_velocity: f64_bits(&v["flow_velocity"]),
        variance_ratio: f64_bits(&v["variance_ratio"]),
        variance_velocity: f64_bits(&v["variance_velocity"]),
        covariance: f64_bits(&v["covariance"]),
        last_update: v["last_update"].as_i64().unwrap(),
        innovation_variance: f64_bits(&v["innovation_variance"]),
        last_innovation: f64_bits(&v["last_innovation"]),
        observation_count: v["observation_count"].as_i64().unwrap(),
    }
}

fn step_from_str(s: &str) -> KalmanStep {
    match s {
        "untouched" => KalmanStep::Untouched,
        "updated" => KalmanStep::Updated,
        "predict_only" => KalmanStep::PredictOnly,
        other => panic!("unknown step label {other}"),
    }
}

// =============================================================================
// Constants
// =============================================================================

#[test]
fn constants_match_python_bit_for_bit() {
    let c = &fixture()["constants"];
    assert_bits_eq(MAX_VELOCITY, f64_bits(&c["MAX_VELOCITY"]), "MAX_VELOCITY");
    assert_bits_eq(MIN_VELOCITY, f64_bits(&c["MIN_VELOCITY"]), "MIN_VELOCITY");
    assert_bits_eq(
        VELOCITY_OUTLIER_THRESHOLD,
        f64_bits(&c["VELOCITY_OUTLIER_THRESHOLD"]),
        "VELOCITY_OUTLIER_THRESHOLD",
    );
    assert_bits_eq(
        BASE_EMA_DECAY,
        f64_bits(&c["BASE_EMA_DECAY"]),
        "BASE_EMA_DECAY",
    );
    assert_bits_eq(DECAY_RANGE, f64_bits(&c["DECAY_RANGE"]), "DECAY_RANGE");
    assert_bits_eq(
        TEMPORAL_EMA_ALPHA,
        f64_bits(&c["TEMPORAL_EMA_ALPHA"]),
        "TEMPORAL_EMA_ALPHA",
    );
    assert_eq!(
        TEMPORAL_GRADUATION_DAYS,
        c["TEMPORAL_GRADUATION_DAYS"].as_i64().unwrap()
    );
    assert_eq!(
        TEMPORAL_MIN_DAILY_FORWARDS,
        c["TEMPORAL_MIN_DAILY_FORWARDS"].as_i64().unwrap()
    );
}

// =============================================================================
// calculate_velocity
// =============================================================================

#[test]
fn velocity_cases_match_python() {
    let data = fixture();
    let cases = data["velocity_cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let id = case["id"].as_str().unwrap();
        let flow_ratio = f64_bits(&case["flow_ratio"]);
        let previous_ratio = f64_bits(&case["previous_ratio"]);
        let previous_timestamp = case["previous_timestamp"].as_i64().unwrap();
        let now = case["now"].as_i64().unwrap();
        let actual = calculate_velocity(flow_ratio, previous_ratio, previous_timestamp, now);
        assert_bits_eq(actual, f64_bits(&case["velocity"]), id);
    }
}

// =============================================================================
// calculate_adaptive_decay
// =============================================================================

#[test]
fn decay_cases_match_python() {
    let data = fixture();
    let cases = data["decay_cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let id = case["id"].as_str().unwrap();
        let buckets = daily_buckets_from(&case["daily_buckets"]);
        let actual = calculate_adaptive_decay(&buckets);
        assert_bits_eq(actual, f64_bits(&case["decay"]), id);
    }
}

// =============================================================================
// calculate_ema_flow
// =============================================================================

#[test]
fn ema_cases_match_python() {
    let data = fixture();
    let cases = data["ema_cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let id = case["id"].as_str().unwrap();
        let buckets: Vec<EmaBucket> = case["daily_buckets"]
            .as_array()
            .unwrap()
            .iter()
            .map(|b| EmaBucket {
                in_sats: b["in"].as_i64().unwrap(),
                out_sats: b["out"].as_i64().unwrap(),
                count: b["count"].as_i64().unwrap(),
                last_ts: b["last_ts"].as_i64().unwrap(),
            })
            .collect();
        let decay_factor = f64_bits(&case["decay_factor"]);
        let (ema_in, ema_out, total_in, total_out, forward_count, last_forward_ts) =
            calculate_ema_flow(&buckets, decay_factor);
        assert_bits_eq(ema_in, f64_bits(&case["ema_in"]), &format!("{id}.ema_in"));
        assert_bits_eq(
            ema_out,
            f64_bits(&case["ema_out"]),
            &format!("{id}.ema_out"),
        );
        assert_eq!(
            total_in,
            case["total_in"].as_i64().unwrap(),
            "{id}.total_in"
        );
        assert_eq!(
            total_out,
            case["total_out"].as_i64().unwrap(),
            "{id}.total_out"
        );
        assert_eq!(
            forward_count,
            case["forward_count"].as_i64().unwrap(),
            "{id}.forward_count"
        );
        assert_eq!(
            last_forward_ts,
            case["last_forward_ts"].as_i64().unwrap(),
            "{id}.last_forward_ts"
        );
    }
}

// =============================================================================
// apply_kalman_filter (300s no-touch gate, first-run dt=24h, cap-168h)
// =============================================================================

fn assert_outcome_matches(outcome: &KalmanFilterOutcome, case: &Value, label: &str) {
    assert_bits_eq(
        outcome.flow_ratio,
        f64_bits(&case["flow_ratio"]),
        &format!("{label}.flow_ratio"),
    );
    assert_bits_eq(
        outcome.flow_velocity,
        f64_bits(&case["flow_velocity"]),
        &format!("{label}.flow_velocity"),
    );
    assert_bits_eq(
        outcome.uncertainty,
        f64_bits(&case["uncertainty"]),
        &format!("{label}.uncertainty"),
    );
    assert_eq!(
        outcome.regime_change,
        case["regime_change"].as_bool().unwrap(),
        "{label}.regime_change"
    );
    assert_eq!(
        outcome.observation_count,
        case["observation_count"].as_i64().unwrap(),
        "{label}.observation_count"
    );
    assert_eq!(
        outcome.step,
        step_from_str(case["step"].as_str().unwrap()),
        "{label}.step"
    );
}

#[test]
fn kalman_filter_single_shot_cases_match_python() {
    let data = fixture();
    let cases = data["kalman_filter_cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    let mut n_checked = 0;
    for case in cases {
        // The `convergence_walk_sequence` entry has a different shape
        // (`steps`, no top-level `id`/`flow_ratio`); handled separately
        // below.
        if case.get("steps").is_some() {
            continue;
        }
        let id = case["id"].as_str().unwrap();
        let mut filter = match &case["initial_state"] {
            Value::Null => KalmanFlowFilter::default(),
            v => KalmanFlowFilter::new(Some(state_from_json(v))),
        };
        let observed_ratio = f64_bits(&case["observed_ratio"]);
        let confidence = f64_bits(&case["confidence"]);
        let daily_buckets = daily_buckets_from(&case["daily_buckets"]);
        let has_observation = case["has_observation"].as_bool().unwrap();
        let now = case["now"].as_i64().unwrap();

        let outcome = apply_kalman_filter(
            &mut filter,
            observed_ratio,
            confidence,
            &daily_buckets,
            has_observation,
            now,
        );
        assert_outcome_matches(&outcome, case, id);

        let expected_final = state_from_json(&case["final_state"]);
        assert_eq!(filter.state, expected_final, "{id}.final_state");
        n_checked += 1;
    }
    assert!(
        n_checked >= 6,
        "expected several single-shot cases, got {n_checked}"
    );
}

#[test]
fn kalman_filter_untouched_case_leaves_state_byte_identical() {
    let data = fixture();
    let cases = data["kalman_filter_cases"].as_array().unwrap();
    let case = cases
        .iter()
        .find(|c| c["id"] == "untouched_within_300s")
        .expect("untouched_within_300s case must exist");

    let mut filter = KalmanFlowFilter::new(Some(state_from_json(&case["initial_state"])));
    let before = filter.state.clone();

    let outcome = apply_kalman_filter(
        &mut filter,
        f64_bits(&case["observed_ratio"]),
        f64_bits(&case["confidence"]),
        &daily_buckets_from(&case["daily_buckets"]),
        case["has_observation"].as_bool().unwrap(),
        case["now"].as_i64().unwrap(),
    );

    assert_eq!(outcome.step, KalmanStep::Untouched);
    assert_eq!(filter.state, before, "Untouched must not mutate state");
}

#[test]
fn kalman_filter_convergence_walk_sequence_matches_python() {
    let data = fixture();
    let cases = data["kalman_filter_cases"].as_array().unwrap();
    let case = cases
        .iter()
        .find(|c| c["id"] == "convergence_walk_sequence")
        .expect("convergence_walk_sequence case must exist");

    let mut filter = KalmanFlowFilter::default();
    let daily_buckets = vec![
        DailyBucket {
            out: 10_000.0,
            in_: 9_000.0,
        },
        DailyBucket {
            out: 10_500.0,
            in_: 8_800.0,
        },
        DailyBucket {
            out: 9_500.0,
            in_: 9_200.0,
        },
    ];

    for (i, step) in case["steps"].as_array().unwrap().iter().enumerate() {
        let now = step["now"].as_i64().unwrap();
        let outcome = apply_kalman_filter(&mut filter, 0.3, 0.85, &daily_buckets, true, now);
        assert_outcome_matches(&outcome, step, &format!("convergence_walk[{i}]"));
    }
}

// =============================================================================
// apply_kalman_reclassification (convergence gate, DTS widening, congestion
// skip, hysteresis via previous_state)
// =============================================================================

fn expected_state_from_name(name: &str) -> ChannelState {
    match name {
        "SOURCE" => ChannelState::Source,
        "SINK" => ChannelState::Sink,
        "BALANCED" => ChannelState::Balanced,
        "BALANCED_ACTIVE" => ChannelState::BalancedActive,
        "DORMANT" => ChannelState::Dormant,
        "UNKNOWN" => ChannelState::Unknown,
        "CONGESTED" => ChannelState::Congested,
        other => panic!("unknown ChannelState name {other}"),
    }
}

#[test]
fn reclassification_cases_match_python() {
    let data = fixture();
    let cases = data["reclassification_cases"].as_array().unwrap();
    assert!(!cases.is_empty());
    for case in cases {
        let id = case["id"].as_str().unwrap();
        let mut filter = KalmanFlowFilter::new(Some(state_from_json(&case["initial_state"])));

        let daily_buckets = daily_buckets_from(&case["daily_buckets"]);
        let raw_entries: Vec<NetFlowEntry> = case["raw_entries"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| NetFlowEntry {
                timestamp: f64_bits(&e["timestamp"]),
                net_msat: e["net_msat"].as_i64().unwrap(),
            })
            .collect();
        let previous_state = case["previous_state"].as_str();
        let posterior_variance = case["posterior_variance"].as_f64();

        let input = ReclassificationInput {
            capacity: case["capacity"].as_i64().unwrap(),
            our_balance: case["our_balance"].as_i64().unwrap(),
            daily_volume: case["daily_volume"].as_i64().unwrap(),
            is_congested: case["is_congested"].as_bool().unwrap(),
            daily_buckets: &daily_buckets,
            raw_entries: &raw_entries,
            last_forward_ts: case["last_forward_ts"].as_i64().unwrap(),
            previous_state,
            source_threshold: f64_bits(&case["source_threshold"]),
            sink_threshold: f64_bits(&case["sink_threshold"]),
            fallback_confidence: f64_bits(&case["fallback_confidence"]),
            posterior_variance,
            now: case["now"].as_i64().unwrap(),
        };

        let outcome = apply_kalman_reclassification(&mut filter, &input);

        assert_bits_eq(
            outcome.kalman_flow_ratio,
            f64_bits(&case["kalman_flow_ratio"]),
            &format!("{id}.kalman_flow_ratio"),
        );
        assert_bits_eq(
            outcome.kalman_velocity,
            f64_bits(&case["kalman_velocity"]),
            &format!("{id}.kalman_velocity"),
        );
        assert_bits_eq(
            outcome.kalman_uncertainty,
            f64_bits(&case["kalman_uncertainty"]),
            &format!("{id}.kalman_uncertainty"),
        );
        assert_eq!(
            outcome.kalman_regime_change,
            case["kalman_regime_change"].as_bool().unwrap(),
            "{id}.kalman_regime_change"
        );
        assert_eq!(
            outcome.step,
            step_from_str(case["step"].as_str().unwrap()),
            "{id}.step"
        );

        let expect_overridden = case["state_overridden"].as_bool().unwrap();
        if expect_overridden {
            let expected = expected_state_from_name(case["resulting_state"].as_str().unwrap());
            assert_eq!(
                outcome.state,
                Some(expected),
                "{id}: expected state override to {expected:?}"
            );
        } else {
            assert_eq!(outcome.state, None, "{id}: expected no state override");
        }
    }
}

// =============================================================================
// TemporalProfile / update_temporal_profile
// =============================================================================

fn histogram_from_json(v: &Value) -> [HourlyHistogramBucket; 24] {
    let arr = v.as_array().unwrap();
    assert_eq!(arr.len(), 24, "histogram must have exactly 24 buckets");
    let mut out = [HourlyHistogramBucket::default(); 24];
    for (i, b) in arr.iter().enumerate() {
        out[i] = HourlyHistogramBucket {
            out_sats: f64_bits(&b["out_sats"]),
            in_sats: f64_bits(&b["in_sats"]),
            count: f64_bits(&b["count"]),
        };
    }
    out
}

/// `burstiness`/`diurnal_strength` are numpy-derived (see `flow.rs`'s
/// module doc comment) -- epsilon compare, not bit-exact.
const NUMPY_EPS: f64 = 1e-9;

fn assert_profile_matches(actual: &TemporalProfile, expected: &Value, label: &str) {
    for h in 0..24 {
        assert_bits_eq(
            actual.hourly_out[h],
            f64_bits(&expected["hourly_out"][h]),
            &format!("{label}.hourly_out[{h}]"),
        );
        assert_bits_eq(
            actual.hourly_in[h],
            f64_bits(&expected["hourly_in"][h]),
            &format!("{label}.hourly_in[{h}]"),
        );
        assert_bits_eq(
            actual.hourly_count[h],
            f64_bits(&expected["hourly_count"][h]),
            &format!("{label}.hourly_count[{h}]"),
        );
    }

    let expected_peak: Vec<i64> = expected["peak_hours"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect();
    let expected_quiet: Vec<i64> = expected["quiet_hours"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect();
    assert_eq!(actual.peak_hours, expected_peak, "{label}.peak_hours");
    assert_eq!(actual.quiet_hours, expected_quiet, "{label}.quiet_hours");

    let expected_burstiness = expected["burstiness"].as_f64().unwrap();
    let expected_diurnal = expected["diurnal_strength"].as_f64().unwrap();
    assert!(
        (actual.burstiness - expected_burstiness).abs() < NUMPY_EPS,
        "{label}.burstiness: actual={:?} expected={:?}",
        actual.burstiness,
        expected_burstiness
    );
    assert!(
        (actual.diurnal_strength - expected_diurnal).abs() < NUMPY_EPS,
        "{label}.diurnal_strength: actual={:?} expected={:?}",
        actual.diurnal_strength,
        expected_diurnal
    );

    assert_eq!(
        actual.dominant_bucket,
        expected["dominant_bucket"].as_str().unwrap(),
        "{label}.dominant_bucket"
    );
    assert_eq!(
        actual.observation_days,
        expected["observation_days"].as_i64().unwrap(),
        "{label}.observation_days"
    );
    assert_eq!(
        actual.last_observation_day,
        expected["last_observation_day"].as_i64().unwrap(),
        "{label}.last_observation_day"
    );
    assert_eq!(
        actual.last_updated,
        expected["last_updated"].as_i64().unwrap(),
        "{label}.last_updated"
    );
}

#[test]
fn temporal_profile_sequences_match_python() {
    let data = fixture();
    let sequences = data["temporal_profile_cases"].as_array().unwrap();
    assert!(!sequences.is_empty());

    let mut total_steps = 0usize;
    for seq in sequences {
        let id = seq["id"].as_str().unwrap();
        let mut existing = TemporalProfile::default();
        for (i, step) in seq["steps"].as_array().unwrap().iter().enumerate() {
            let histogram = histogram_from_json(&step["histogram"]);
            let daily_forwards = step["daily_forwards"].as_i64().unwrap();
            let now = step["now"].as_i64().unwrap();

            let updated = update_temporal_profile(&existing, &histogram, daily_forwards, now);
            assert_profile_matches(&updated, &step["profile_after"], &format!("{id}[{i}]"));
            existing = updated;
        }
        total_steps += seq["steps"].as_array().unwrap().len();
    }
    assert!(
        total_steps > 10,
        "expected a substantial step count, got {total_steps}"
    );
}

#[test]
fn temporal_profile_graduated_matches_grace_boundary() {
    let mut tp = TemporalProfile::default();
    assert!(!tp.graduated());
    tp.observation_days = TEMPORAL_GRADUATION_DAYS - 1;
    assert!(!tp.graduated());
    tp.observation_days = TEMPORAL_GRADUATION_DAYS;
    assert!(tp.graduated());
    tp.observation_days = TEMPORAL_GRADUATION_DAYS + 5;
    assert!(tp.graduated());
}

// =============================================================================
// FlowMetrics.to_dict rounding
// =============================================================================

#[test]
fn flow_metrics_to_dict_rounds_and_maps_state_value() {
    use revops_analytics::flow::FlowMetrics;

    let m = FlowMetrics {
        channel_id: "123x456x0".to_string(),
        peer_id: "02aa".to_string(),
        sats_in: 1_000,
        sats_out: 2_000,
        capacity: 3_000,
        flow_ratio: 0.123_456_78,
        state: ChannelState::Sink,
        daily_volume: 500,
        is_congested: false,
        confidence: 0.123_456,
        velocity: 0.000_123_45,
        flow_multiplier: 1.234_567,
        ema_decay: 0.812_345,
        forward_count: 7,
        kalman_flow_ratio: -0.111_115,
        kalman_velocity: 0.000_005,
        kalman_uncertainty: 0.100_001,
        kalman_regime_change: true,
    };

    let d = m.to_dict();
    assert_eq!(d.state, "sink");
    assert_eq!(d.flow_ratio, 0.1235);
    assert_eq!(d.confidence, 0.123);
    assert_eq!(d.velocity, 0.0001);
    assert_eq!(d.flow_multiplier, 1.235);
    assert_eq!(d.ema_decay, 0.812);
    assert_eq!(d.kalman_flow_ratio, -0.1111);
    // round(0.000005, 4) == 0.0 (real CPython, verified by direct execution).
    assert_eq!(d.kalman_velocity, 0.0);
    assert_eq!(d.kalman_uncertainty, 0.1);
    assert!(d.kalman_regime_change);
    assert_eq!(d.channel_id, "123x456x0");
    assert_eq!(d.peer_id, "02aa");
    assert_eq!(d.sats_in, 1_000);
    assert_eq!(d.sats_out, 2_000);
    assert_eq!(d.capacity, 3_000);
    assert_eq!(d.daily_volume, 500);
    assert!(!d.is_congested);
    assert_eq!(d.forward_count, 7);
}
