//! Bit-parity replay of `fixtures/kalman.json` (Phase 3 Task 3) against the
//! real Python `modules/flow_analysis.py` Kalman filter, generated by
//! `tools/port/gen_kalman_fixtures.py` in the cl_revenue_ops-port worktree.
//! Every float assertion below compares `f64::to_bits` — no epsilon: the
//! whole point of this fixture is that the Rust arithmetic reproduces the
//! exact same IEEE-754 double, term for term, as Python.

use revops_analytics::kalman::{
    calculate_confidence, calculate_kalman_volatility, compute_raw_kalman_observation,
    estimate_depletion_hours, DailyBucket, KalmanFlowFilter, KalmanFlowState, KalmanStateDict,
    NetFlowEntry, CONFIDENCE_RECENCY_HALFLIFE_DAYS, DEPLETION_MIN_DRAIN_SATS_PER_DAY,
    KALMAN_BASE_MEASUREMENT_NOISE, KALMAN_BASE_PROCESS_NOISE, KALMAN_CONFIDENCE_SCALING,
    KALMAN_CONVERGENCE_UNCERTAINTY, KALMAN_INITIAL_VARIANCE, KALMAN_MAX_MEASUREMENT_NOISE,
    KALMAN_MAX_PROCESS_NOISE, KALMAN_MAX_VELOCITY, KALMAN_MIN_MEASUREMENT_NOISE,
    KALMAN_MIN_OBSERVATIONS, KALMAN_MIN_PROCESS_NOISE, KALMAN_MIN_UPDATE_INTERVAL_SECS,
    KALMAN_MIN_VELOCITY, KALMAN_VELOCITY_PROCESS_NOISE, KALMAN_VOLATILITY_SCALING, MAX_CONFIDENCE,
    MIN_CONFIDENCE, MIN_FORWARDS_FOR_HIGH_CONFIDENCE,
};
use serde_json::Value;

fn fixture() -> Value {
    let raw = include_str!("../../../fixtures/kalman.json");
    serde_json::from_str(raw).unwrap()
}

/// Decode a `struct.pack('<d', v).hex()` string (little-endian 8-byte f64)
/// back into the exact `f64` bit pattern Python produced.
fn bits_to_f64(s: &str) -> f64 {
    assert_eq!(
        s.len(),
        16,
        "expected a 16-hex-char (8-byte) little-endian pattern, got {s:?}"
    );
    let mut bytes = [0u8; 8];
    for (i, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("valid hex byte");
    }
    f64::from_bits(u64::from_le_bytes(bytes))
}

fn f64_bits(v: &Value) -> f64 {
    bits_to_f64(v.as_str().expect("expected a hex bit-pattern string"))
}

fn assert_bits_eq(actual: f64, expected: f64, label: &str) {
    assert_eq!(
        actual.to_bits(),
        expected.to_bits(),
        "{label}: bit mismatch (actual={actual:?} [{:016x}], expected={expected:?} [{:016x}])",
        actual.to_bits(),
        expected.to_bits(),
    );
}

fn state_from_json(v: &Value) -> KalmanFlowState {
    KalmanFlowState {
        flow_ratio: f64_bits(&v["flow_ratio"]),
        flow_velocity: f64_bits(&v["flow_velocity"]),
        variance_ratio: f64_bits(&v["variance_ratio"]),
        variance_velocity: f64_bits(&v["variance_velocity"]),
        covariance: f64_bits(&v["covariance"]),
        last_update: v["last_update"].as_i64().unwrap(),
        innovation_variance: f64_bits(&v["innovation_variance"]),
        last_innovation: f64_bits(&v["last_innovation"]),
        observation_count: v["observation_count"].as_i64().unwrap(),
    }
}

fn assert_state_eq(actual: &KalmanFlowState, expected_json: &Value, label: &str) {
    assert_bits_eq(
        actual.flow_ratio,
        f64_bits(&expected_json["flow_ratio"]),
        &format!("{label}.flow_ratio"),
    );
    assert_bits_eq(
        actual.flow_velocity,
        f64_bits(&expected_json["flow_velocity"]),
        &format!("{label}.flow_velocity"),
    );
    assert_bits_eq(
        actual.variance_ratio,
        f64_bits(&expected_json["variance_ratio"]),
        &format!("{label}.variance_ratio"),
    );
    assert_bits_eq(
        actual.variance_velocity,
        f64_bits(&expected_json["variance_velocity"]),
        &format!("{label}.variance_velocity"),
    );
    assert_bits_eq(
        actual.covariance,
        f64_bits(&expected_json["covariance"]),
        &format!("{label}.covariance"),
    );
    assert_eq!(
        actual.last_update,
        expected_json["last_update"].as_i64().unwrap(),
        "{label}.last_update"
    );
    assert_bits_eq(
        actual.innovation_variance,
        f64_bits(&expected_json["innovation_variance"]),
        &format!("{label}.innovation_variance"),
    );
    assert_bits_eq(
        actual.last_innovation,
        f64_bits(&expected_json["last_innovation"]),
        &format!("{label}.last_innovation"),
    );
    assert_eq!(
        actual.observation_count,
        expected_json["observation_count"].as_i64().unwrap(),
        "{label}.observation_count"
    );
}

// =============================================================================
// Constants cross-check
// =============================================================================

#[test]
fn constants_match_python_bit_for_bit() {
    let c = &fixture()["constants"];
    assert_bits_eq(
        KALMAN_MAX_VELOCITY,
        f64_bits(&c["KALMAN_MAX_VELOCITY"]),
        "KALMAN_MAX_VELOCITY",
    );
    assert_bits_eq(
        KALMAN_MIN_VELOCITY,
        f64_bits(&c["KALMAN_MIN_VELOCITY"]),
        "KALMAN_MIN_VELOCITY",
    );
    assert_bits_eq(
        KALMAN_BASE_PROCESS_NOISE,
        f64_bits(&c["KALMAN_BASE_PROCESS_NOISE"]),
        "KALMAN_BASE_PROCESS_NOISE",
    );
    assert_bits_eq(
        KALMAN_VELOCITY_PROCESS_NOISE,
        f64_bits(&c["KALMAN_VELOCITY_PROCESS_NOISE"]),
        "KALMAN_VELOCITY_PROCESS_NOISE",
    );
    assert_bits_eq(
        KALMAN_MIN_PROCESS_NOISE,
        f64_bits(&c["KALMAN_MIN_PROCESS_NOISE"]),
        "KALMAN_MIN_PROCESS_NOISE",
    );
    assert_bits_eq(
        KALMAN_MAX_PROCESS_NOISE,
        f64_bits(&c["KALMAN_MAX_PROCESS_NOISE"]),
        "KALMAN_MAX_PROCESS_NOISE",
    );
    assert_bits_eq(
        KALMAN_BASE_MEASUREMENT_NOISE,
        f64_bits(&c["KALMAN_BASE_MEASUREMENT_NOISE"]),
        "KALMAN_BASE_MEASUREMENT_NOISE",
    );
    assert_bits_eq(
        KALMAN_MIN_MEASUREMENT_NOISE,
        f64_bits(&c["KALMAN_MIN_MEASUREMENT_NOISE"]),
        "KALMAN_MIN_MEASUREMENT_NOISE",
    );
    assert_bits_eq(
        KALMAN_MAX_MEASUREMENT_NOISE,
        f64_bits(&c["KALMAN_MAX_MEASUREMENT_NOISE"]),
        "KALMAN_MAX_MEASUREMENT_NOISE",
    );
    assert_bits_eq(
        KALMAN_INITIAL_VARIANCE,
        f64_bits(&c["KALMAN_INITIAL_VARIANCE"]),
        "KALMAN_INITIAL_VARIANCE",
    );
    assert_bits_eq(
        KALMAN_VOLATILITY_SCALING,
        f64_bits(&c["KALMAN_VOLATILITY_SCALING"]),
        "KALMAN_VOLATILITY_SCALING",
    );
    assert_bits_eq(
        KALMAN_CONFIDENCE_SCALING,
        f64_bits(&c["KALMAN_CONFIDENCE_SCALING"]),
        "KALMAN_CONFIDENCE_SCALING",
    );
    assert_bits_eq(
        KALMAN_CONVERGENCE_UNCERTAINTY,
        f64_bits(&c["KALMAN_CONVERGENCE_UNCERTAINTY"]),
        "KALMAN_CONVERGENCE_UNCERTAINTY",
    );
    assert_bits_eq(
        MIN_CONFIDENCE,
        f64_bits(&c["MIN_CONFIDENCE"]),
        "MIN_CONFIDENCE",
    );
    assert_bits_eq(
        MAX_CONFIDENCE,
        f64_bits(&c["MAX_CONFIDENCE"]),
        "MAX_CONFIDENCE",
    );
    assert_bits_eq(
        CONFIDENCE_RECENCY_HALFLIFE_DAYS,
        f64_bits(&c["CONFIDENCE_RECENCY_HALFLIFE_DAYS"]),
        "CONFIDENCE_RECENCY_HALFLIFE_DAYS",
    );
    assert_bits_eq(
        DEPLETION_MIN_DRAIN_SATS_PER_DAY,
        f64_bits(&c["DEPLETION_MIN_DRAIN_SATS_PER_DAY"]),
        "DEPLETION_MIN_DRAIN_SATS_PER_DAY",
    );
    assert_eq!(
        KALMAN_MIN_OBSERVATIONS,
        c["KALMAN_MIN_OBSERVATIONS"].as_i64().unwrap()
    );
    assert_eq!(
        KALMAN_MIN_UPDATE_INTERVAL_SECS,
        c["KALMAN_MIN_UPDATE_INTERVAL_SECS"].as_i64().unwrap()
    );
    assert_eq!(
        MIN_FORWARDS_FOR_HIGH_CONFIDENCE,
        c["MIN_FORWARDS_FOR_HIGH_CONFIDENCE"].as_i64().unwrap()
    );
}

// =============================================================================
// Sequence replay: fresh + persisted-state filters through randomized
// predict/update interleavings.
// =============================================================================

#[test]
fn sequence_replay_matches_python_bit_for_bit() {
    let data = fixture();
    let sequences = data["sequences"].as_array().unwrap();
    assert!(!sequences.is_empty(), "fixture must be non-empty");

    let mut total_steps = 0usize;
    for seq in sequences {
        let id = seq["id"].as_str().unwrap();
        let initial_state = &seq["initial_state"];
        let mut filter = if initial_state.is_null() {
            KalmanFlowFilter::default()
        } else {
            KalmanFlowFilter::new(Some(state_from_json(initial_state)))
        };

        for (i, step) in seq["steps"].as_array().unwrap().iter().enumerate() {
            let label = format!("{id}[{i}]");
            let kind = step["kind"].as_str().unwrap();
            let recovery_delta = match kind {
                "predict" => {
                    let dt_hours = f64_bits(&step["dt_hours"]);
                    let volatility = f64_bits(&step["volatility"]);
                    filter.predict(dt_hours, volatility);
                    filter.take_nan_recovery_count()
                }
                "update" => {
                    let observed_ratio = f64_bits(&step["observed_ratio"]);
                    let confidence = f64_bits(&step["confidence"]);
                    let now = step["now"].as_i64().unwrap();
                    let innovation = filter.update(observed_ratio, confidence, now);
                    assert_bits_eq(
                        innovation,
                        f64_bits(&step["innovation"]),
                        &format!("{label}.innovation"),
                    );
                    filter.take_nan_recovery_count()
                }
                other => panic!("unknown step kind {other}"),
            };
            assert_eq!(
                recovery_delta as i64,
                step["nan_recovery_delta"].as_i64().unwrap(),
                "{label}.nan_recovery_delta"
            );
            assert_state_eq(&filter.state, &step["state_after"], &label);
            total_steps += 1;
        }
    }
    assert!(
        total_steps > 200,
        "expected a substantial fixture corpus, got {total_steps}"
    );
}

// =============================================================================
// Hand cases
// =============================================================================

fn run_hand_case(case: &Value) -> (KalmanFlowFilter, Option<f64>, u32) {
    let mut filter = KalmanFlowFilter::new(Some(state_from_json(&case["initial_state"])));
    let step = &case["step"];
    let innovation = match step["kind"].as_str().unwrap() {
        "predict" => {
            filter.predict(f64_bits(&step["dt_hours"]), f64_bits(&step["volatility"]));
            None
        }
        "update" => Some(filter.update(
            f64_bits(&step["observed_ratio"]),
            f64_bits(&step["confidence"]),
            step["now"].as_i64().unwrap(),
        )),
        other => panic!("unknown step kind {other}"),
    };
    let recovery = filter.take_nan_recovery_count();
    (filter, innovation, recovery)
}

#[test]
fn dt_zero_is_a_noop() {
    let data = fixture();
    let case = &data["hand_cases"]["dt_zero_noop"];
    let before = state_from_json(&case["initial_state"]);
    let (filter, _, recovery) = run_hand_case(case);
    assert_eq!(filter.state, before, "dt<=0 must not mutate state");
    assert_eq!(recovery, 0);
}

#[test]
fn dt_negative_is_a_noop() {
    let data = fixture();
    let case = &data["hand_cases"]["dt_negative_noop"];
    let before = state_from_json(&case["initial_state"]);
    let (filter, _, recovery) = run_hand_case(case);
    assert_eq!(filter.state, before, "dt<0 must not mutate state");
    assert_eq!(recovery, 0);
}

#[test]
fn predict_resets_on_preexisting_nan_state() {
    let data = fixture();
    let case = &data["hand_cases"]["predict_nan_state_reset"];
    let (filter, _, recovery) = run_hand_case(case);
    assert_eq!(filter.state, KalmanFlowState::default());
    assert_eq!(recovery, 1, "exactly one reset should be counted");
}

#[test]
fn update_resets_on_preexisting_nan_state_and_returns_zero() {
    let data = fixture();
    let case = &data["hand_cases"]["update_nan_state_reset"];
    let (filter, innovation, recovery) = run_hand_case(case);
    assert_eq!(filter.state, KalmanFlowState::default());
    assert_eq!(recovery, 1, "exactly one reset should be counted");
    assert_eq!(innovation, Some(0.0), "NaN-triggered reset must return 0.0");
}

#[test]
fn covariance_clamps_when_determinant_nonpositive() {
    let data = fixture();
    let case = &data["hand_cases"]["det_nonpositive_clamp"];
    let (filter, _, _) = run_hand_case(case);
    assert_state_eq(
        &filter.state,
        &case["step"]["state_after"],
        "det_nonpositive_clamp",
    );

    let p00 = filter.state.variance_ratio;
    let p01 = filter.state.covariance;
    let p11 = filter.state.variance_velocity;
    assert!(
        p00 * p11 - p01 * p01 > 0.0,
        "clamp must restore a positive determinant"
    );
    assert!(
        (p01.abs() - 0.9 * (p00 * p11).sqrt()).abs() < 1e-9,
        "covariance must be pinned to the +/-0.9*sqrt(p00*p11) bound"
    );
}

#[test]
fn observation_rejects_leave_state_untouched_but_return_zero() {
    let data = fixture();
    for label in [
        "observation_nan_no_touch",
        "observation_pos_inf_no_touch",
        "observation_neg_inf_no_touch",
    ] {
        let case = &data["hand_cases"][label];
        let before = state_from_json(&case["initial_state"]);
        let (filter, innovation, recovery) = run_hand_case(case);
        assert_eq!(filter.state, before, "{label}: state must be untouched");
        assert_eq!(innovation, Some(0.0), "{label}: must still return 0.0");
        assert_eq!(recovery, 0, "{label}: no reset should be counted");
    }
}

// =============================================================================
// to_dict / from_dict roundtrip (real `_safe` semantics)
// =============================================================================

fn opt_f64(v: &Value) -> Option<f64> {
    if v.is_null() {
        None
    } else {
        Some(f64_bits(&v["bits"]))
    }
}

fn opt_i64(v: &Value) -> Option<i64> {
    if v.is_null() {
        None
    } else {
        v.as_i64()
    }
}

#[test]
fn state_dict_roundtrip_matches_python() {
    let data = fixture();
    for case in data["state_dict_roundtrip"].as_array().unwrap() {
        let label = case["label"].as_str().unwrap();
        let input = &case["input"];
        let get = |key: &str| input.get(key).cloned().unwrap_or(Value::Null);

        let dict = KalmanStateDict {
            flow_ratio: opt_f64(&get("flow_ratio")),
            flow_velocity: opt_f64(&get("flow_velocity")),
            variance_ratio: opt_f64(&get("variance_ratio")),
            variance_velocity: opt_f64(&get("variance_velocity")),
            covariance: opt_f64(&get("covariance")),
            last_update: opt_i64(&get("last_update")),
            innovation_variance: opt_f64(&get("innovation_variance")),
            last_innovation: opt_f64(&get("last_innovation")),
            observation_count: opt_i64(&get("observation_count")),
        };

        let state = KalmanFlowState::from_dict(&dict);
        assert_state_eq(&state, &case["expected_state"], label);

        // to_dict roundtrip: re-encoding the resulting state must reproduce
        // the same field values (present, since to_dict always populates
        // every key). Compare via bit pattern, not `==` — `state.flow_ratio`
        // is legitimately NaN in the `present_nonfinite_passes_through`
        // case, and NaN != NaN under IEEE-754 `PartialEq`.
        let redict = state.to_dict();
        assert_eq!(
            redict.flow_ratio.map(f64::to_bits),
            Some(state.flow_ratio.to_bits())
        );
        assert_eq!(redict.last_update, Some(state.last_update));
        assert_eq!(redict.observation_count, Some(state.observation_count));
    }
}

#[test]
fn all_missing_keys_yield_defaults() {
    let data = fixture();
    let case = &data["state_dict_roundtrip"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["label"] == "all_missing_defaults")
        .unwrap();
    let dict = KalmanStateDict::default();
    let state = KalmanFlowState::from_dict(&dict);
    assert_eq!(state, KalmanFlowState::default());
    assert_state_eq(&state, &case["expected_state"], "all_missing_defaults");
}

#[test]
fn present_nonfinite_values_pass_through_unchanged() {
    let data = fixture();
    let case = data["state_dict_roundtrip"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["label"] == "present_nonfinite_passes_through")
        .unwrap();
    let input = &case["input"];
    let dict = KalmanStateDict {
        flow_ratio: Some(f64_bits(&input["flow_ratio"]["bits"])),
        variance_ratio: Some(f64_bits(&input["variance_ratio"]["bits"])),
        covariance: Some(f64_bits(&input["covariance"]["bits"])),
        last_update: input["last_update"].as_i64(),
        innovation_variance: Some(f64_bits(&input["innovation_variance"]["bits"])),
        ..Default::default()
    };
    let state = KalmanFlowState::from_dict(&dict);
    assert!(
        state.flow_ratio.is_nan(),
        "NaN present value must pass through, not default"
    );
    assert!(state.variance_ratio.is_infinite() && state.variance_ratio > 0.0);
    assert!(state.covariance.is_infinite() && state.covariance < 0.0);
    assert!(state.innovation_variance.is_nan());
    // flow_velocity was absent from the input -> falls back to default.
    assert_eq!(state.flow_velocity, 0.0);
}

// =============================================================================
// calculate_kalman_volatility
// =============================================================================

#[test]
fn volatility_cases_match_python() {
    let data = fixture();
    for case in data["volatility_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let buckets: Vec<DailyBucket> = case["daily_buckets"]
            .as_array()
            .unwrap()
            .iter()
            .map(|b| DailyBucket {
                out: b["out"].as_f64().unwrap(),
                in_: b["in"].as_f64().unwrap(),
            })
            .collect();
        let actual = calculate_kalman_volatility(&buckets);
        assert_bits_eq(actual, f64_bits(&case["volatility"]), id);
    }
}

// =============================================================================
// compute_raw_kalman_observation
// =============================================================================

#[test]
fn raw_observation_cases_match_python() {
    let data = fixture();
    for case in data["raw_observation_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let capacity = case["capacity"].as_i64().unwrap();
        let now = f64_bits(&case["now"]);
        let entries: Vec<NetFlowEntry> = case["entries"]
            .as_array()
            .unwrap()
            .iter()
            .map(|e| NetFlowEntry {
                timestamp: f64_bits(&e["timestamp"]),
                net_msat: e["net_msat"].as_i64().unwrap(),
            })
            .collect();
        let (ratio, count) = compute_raw_kalman_observation(capacity, &entries, now);
        assert_bits_eq(ratio, f64_bits(&case["ratio"]), &format!("{id}.ratio"));
        assert_eq!(count as i64, case["count"].as_i64().unwrap(), "{id}.count");
    }
}

// =============================================================================
// calculate_confidence
// =============================================================================

#[test]
fn confidence_cases_match_python() {
    let data = fixture();
    for case in data["confidence_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let forward_count = case["forward_count"].as_i64().unwrap();
        let last_forward_ts = case["last_forward_ts"].as_i64().unwrap();
        let now = case["now"].as_i64().unwrap();
        let actual = calculate_confidence(forward_count, last_forward_ts, now);
        assert_bits_eq(actual, f64_bits(&case["confidence"]), id);
    }
}

// =============================================================================
// estimate_depletion_hours
// =============================================================================

#[test]
fn depletion_cases_match_python() {
    let data = fixture();
    for case in data["depletion_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let local_sats = f64_bits(&case["local_sats"]);
        let capacity_sats = f64_bits(&case["capacity_sats"]);
        let kalman_ratio = f64_bits(&case["kalman_ratio"]);
        let kalman_velocity = f64_bits(&case["kalman_velocity"]);
        let actual =
            estimate_depletion_hours(local_sats, capacity_sats, kalman_ratio, kalman_velocity);
        match (&actual, case["hours"].as_str()) {
            (None, None) => {}
            (Some(a), Some(expected_hex)) => {
                assert_bits_eq(*a, bits_to_f64(expected_hex), id);
            }
            _ => panic!(
                "{id}: Some/None mismatch (actual={actual:?}, expected={:?})",
                case["hours"]
            ),
        }
    }
}
