//! Byte-shape replay of `fixtures/telemetry.json` (Phase 3 Task 8) against
//! the real Python `_push_profitability_summary` dict construction +
//! `json.dumps(payload)` defaults, generated by
//! `tools/port/gen_telemetry_fixtures.py` in the cl_revenue_ops-port
//! worktree. Every case below asserts full `String` equality against the
//! real Python-produced `json.dumps` output — no normalization, no
//! re-parsing: this is the byte-shape contract itself.
//!
//! Envelope-rule tests (timestamp injection, error-key reject, size cap) are
//! hand-written Rust cases at the bottom of this file: the rules are simple
//! and mechanical (no float/unicode subtlety), so they don't need a
//! Python-sourced golden fixture the way the payload byte-shape does.

use revops_analytics::profitability::{
    ChannelCosts, ChannelProfitability, ChannelRevenue, ProfitabilityClass,
};
use revops_analytics::telemetry::{
    datastore_envelope, profitability_summary_payload, python_dumps, PyDict, PyVal, TelemetryError,
    PROFITABILITY_SUMMARY_KEY,
};
use serde_json::Value;

fn fixture() -> Value {
    let raw = include_str!("../../../fixtures/telemetry.json");
    serde_json::from_str(raw).unwrap()
}

fn bits_to_f64(s: &str) -> f64 {
    assert_eq!(s.len(), 16, "expected a 16-hex-char bit pattern, got {s:?}");
    let mut bytes = [0u8; 8];
    for (i, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("valid hex byte");
    }
    f64::from_bits(u64::from_le_bytes(bytes))
}

fn classification_from_name(name: &str) -> ProfitabilityClass {
    match name {
        "PROFITABLE" => ProfitabilityClass::Profitable,
        "BREAK_EVEN" => ProfitabilityClass::BreakEven,
        "UNDERWATER" => ProfitabilityClass::Underwater,
        "STAGNANT_CANDIDATE" => ProfitabilityClass::StagnantCandidate,
        "ZOMBIE" => ProfitabilityClass::Zombie,
        other => panic!("unknown ProfitabilityClass name {other:?}"),
    }
}

/// Placeholder values mirrored exactly from the generator's
/// `PLACEHOLDER_*` constants (`tools/port/gen_telemetry_fixtures.py`) — the
/// datastore payload never reads these `ChannelProfitability` fields, so
/// both sides pin them to the same fixed values rather than varying them
/// per case.
fn profitability_from_entry(entry: &Value) -> (ChannelProfitability, f64) {
    let channel_id = entry["channel_id"].as_str().unwrap().to_string();
    let peer_id = entry["peer_id"].as_str().unwrap().to_string();

    let costs = ChannelCosts {
        channel_id: channel_id.clone(),
        peer_id: peer_id.clone(),
        open_cost_sats: entry["open_cost_sats"].as_i64().unwrap(),
        rebalance_cost_sats: entry["rebalance_cost_sats"].as_i64().unwrap(),
        effective_rebalance_cost_sats: 0,
    };
    let revenue = ChannelRevenue {
        channel_id: channel_id.clone(),
        fees_earned_msat: entry["fees_earned_msat"].as_i64().unwrap(),
        volume_routed_msat: entry["volume_routed_msat"].as_i64().unwrap(),
        forward_count: entry["forward_count"].as_i64().unwrap(),
        sourced_volume_msat: entry["sourced_volume_msat"].as_i64().unwrap(),
        sourced_fee_contribution_msat: entry["sourced_fee_contribution_msat"].as_i64().unwrap(),
        sourced_forward_count: entry["sourced_forward_count"].as_i64().unwrap(),
    };

    let p = ChannelProfitability {
        channel_id,
        peer_id,
        capacity_sats: 1_000_000, // PLACEHOLDER_CAPACITY_SATS
        costs,
        revenue,
        net_profit_sats: entry["net_profit_sats"].as_i64().unwrap(),
        roi_percent: bits_to_f64(entry["roi_percent_bits"].as_str().unwrap()),
        classification: classification_from_name(entry["classification"].as_str().unwrap()),
        cost_per_sat_routed: 0.0, // PLACEHOLDER_COST_PER_SAT_ROUTED
        fee_per_sat_routed: 0.0,  // PLACEHOLDER_FEE_PER_SAT_ROUTED
        days_open: entry["days_open"].as_i64().unwrap(),
        last_routed: None,           // PLACEHOLDER_LAST_ROUTED
        marginal_profit_30d_sats: 0, // PLACEHOLDER_MARGINAL_PROFIT_30D_SATS
        rebalance_cost_30d_sats: entry["rebalance_cost_30d_sats"].as_i64().unwrap(),
        opener: "local".to_string(), // PLACEHOLDER_OPENER
        contribution_30d_msat: entry["contribution_30d_msat"].as_i64().unwrap(),
        fees_earned_30d_msat: entry["fees_earned_30d_msat"].as_i64().unwrap(),
        sourced_fee_30d_msat: entry["sourced_fee_30d_msat"].as_i64().unwrap(),
        forward_count_30d: entry["forward_count_30d"].as_i64().unwrap(),
        sourced_forward_count_30d: entry["sourced_forward_count_30d"].as_i64().unwrap(),
        window_30d_available: entry["window_30d_available"].as_bool().unwrap(),
    };
    let fee_multiplier = bits_to_f64(entry["fee_multiplier_bits"].as_str().unwrap());
    (p, fee_multiplier)
}

#[test]
fn profitability_summary_key_matches_python_datastore_key() {
    let fx = fixture();
    let expected: Vec<String> = fx["datastore_key"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert_eq!(
        PROFITABILITY_SUMMARY_KEY.to_vec(),
        expected,
        "datastore key path must match Python's `[\"revenue\", \"profitability-summary\"]`"
    );
}

#[test]
fn payload_cases_are_byte_identical_to_python_json_dumps() {
    let fx = fixture();
    let cases = fx["payload_cases"].as_array().unwrap();
    assert!(cases.len() >= 6, "expected at least 6 payload cases");

    for case in cases {
        let id = case["id"].as_str().unwrap();
        let timestamp = case["timestamp"].as_i64().unwrap();
        let expected_json = case["expected_json"].as_str().unwrap();

        let entries_json = case["entries"].as_array().unwrap();
        let mut built: Vec<(ChannelProfitability, f64)> =
            entries_json.iter().map(profitability_from_entry).collect();

        let summary_entries: Vec<revops_analytics::telemetry::SummaryEntry<'_>> = built
            .iter_mut()
            .map(
                |(p, fee_multiplier)| revops_analytics::telemetry::SummaryEntry {
                    profitability: p,
                    fee_multiplier: *fee_multiplier,
                },
            )
            .collect();

        let payload = profitability_summary_payload(&summary_entries, timestamp);
        let actual_json = python_dumps(&PyVal::Dict(payload));

        assert_eq!(
            actual_json, expected_json,
            "case {id:?}: byte-shape mismatch against Python json.dumps output"
        );
    }
}

#[test]
fn empty_channels_case_renders_empty_dict_not_empty_array() {
    let fx = fixture();
    let cases = fx["payload_cases"].as_array().unwrap();
    let case = cases
        .iter()
        .find(|c| c["id"] == "empty_channels")
        .expect("expected an empty_channels case");
    let expected_json = case["expected_json"].as_str().unwrap();
    assert!(expected_json.contains("\"channels\": {}"));

    let payload = profitability_summary_payload(&[], case["timestamp"].as_i64().unwrap());
    let actual = python_dumps(&PyVal::Dict(payload));
    assert_eq!(actual, expected_json);
}

// =============================================================================
// python_dumps: direct byte-shape unit tests (insertion order, separators,
// ensure_ascii escaping, float repr) — independent of the fixture, since
// these are properties of the serializer itself, not the payload.
// =============================================================================

#[test]
fn python_dumps_preserves_insertion_order_not_sorted() {
    let mut d = PyDict::new();
    d.push("z", PyVal::Int(1));
    d.push("a", PyVal::Int(2));
    d.push("m", PyVal::Int(3));
    assert_eq!(python_dumps(&PyVal::Dict(d)), r#"{"z": 1, "a": 2, "m": 3}"#);
}

#[test]
fn python_dumps_uses_default_separators() {
    let mut inner = PyDict::new();
    inner.push("x", PyVal::Int(1));
    let mut d = PyDict::new();
    d.push("a", PyVal::Int(1));
    d.push("b", PyVal::Dict(inner));
    assert_eq!(python_dumps(&PyVal::Dict(d)), r#"{"a": 1, "b": {"x": 1}}"#);
}

#[test]
fn python_dumps_escapes_non_ascii_like_python_ensure_ascii_true() {
    // Golden: json.dumps({"a": "héllo", "b": "日本語", "c": "😀"})
    // == '{"a": "h\\u00e9llo", "b": "\\u65e5\\u672c\\u8a9e", "c": "\\ud83d\\ude00"}'
    let mut d = PyDict::new();
    d.push("a", PyVal::Str("héllo".to_string()));
    d.push("b", PyVal::Str("日本語".to_string()));
    d.push("c", PyVal::Str("😀".to_string()));
    let expected =
        "{\"a\": \"h\\u00e9llo\", \"b\": \"\\u65e5\\u672c\\u8a9e\", \"c\": \"\\ud83d\\ude00\"}";
    assert_eq!(python_dumps(&PyVal::Dict(d)), expected);
}

#[test]
fn python_dumps_this_differs_from_canonical_json_ensure_ascii_false() {
    // THE trap, directly asserted: canonical_json uses ensure_ascii=False
    // (raw UTF-8 non-ASCII passes through); this serializer does not.
    let mut d = PyDict::new();
    d.push("name", PyVal::Str("héllo".to_string()));
    let out = python_dumps(&PyVal::Dict(d));
    assert!(out.contains("\\u00e9"));
    assert!(!out.contains('é'));
}

#[test]
fn python_dumps_renders_floats_via_py_repr() {
    let mut d = PyDict::new();
    d.push("whole", PyVal::Float(20.0));
    d.push("small", PyVal::Float(1.1));
    assert_eq!(
        python_dumps(&PyVal::Dict(d)),
        r#"{"whole": 20.0, "small": 1.1}"#
    );
}

#[test]
fn python_dumps_renders_bools_lowercase_unquoted() {
    let mut d = PyDict::new();
    d.push("ok", PyVal::Bool(true));
    d.push("bad", PyVal::Bool(false));
    assert_eq!(
        python_dumps(&PyVal::Dict(d)),
        r#"{"ok": true, "bad": false}"#
    );
}

// =============================================================================
// datastore_envelope: the datastore_push decision rules
// =============================================================================

#[test]
fn envelope_injects_timestamp_when_absent() {
    let mut payload = PyDict::new();
    payload.push("channels", PyVal::Dict(PyDict::new()));
    let out = datastore_envelope(payload, 1_752_400_000, 60_000).unwrap();
    assert_eq!(out, r#"{"channels": {}, "timestamp": 1752400000}"#);
}

#[test]
fn envelope_does_not_overwrite_existing_timestamp() {
    let mut payload = PyDict::new();
    payload.push("timestamp", PyVal::Int(111));
    payload.push("channels", PyVal::Dict(PyDict::new()));
    // `now` is a different value than the existing timestamp; the existing
    // one must survive untouched, in its original position.
    let out = datastore_envelope(payload, 999_999_999, 60_000).unwrap();
    assert_eq!(out, r#"{"timestamp": 111, "channels": {}}"#);
}

#[test]
fn envelope_rejects_error_key() {
    let mut payload = PyDict::new();
    payload.push("error", PyVal::Str("boom".to_string()));
    let result = datastore_envelope(payload, 1, 60_000);
    assert_eq!(result, Err(TelemetryError::ErrorKeyPresent));
}

#[test]
fn envelope_rejects_error_key_even_with_timestamp_present() {
    let mut payload = PyDict::new();
    payload.push("timestamp", PyVal::Int(1));
    payload.push("error", PyVal::Str("boom".to_string()));
    let result = datastore_envelope(payload, 1, 60_000);
    assert_eq!(result, Err(TelemetryError::ErrorKeyPresent));
}

#[test]
fn envelope_size_cap_measured_on_utf8_encoded_bytes() {
    let mut payload = PyDict::new();
    payload.push("timestamp", PyVal::Int(1));
    payload.push("x", PyVal::Str("a".repeat(50)));
    let encoded_len = python_dumps(&PyVal::Dict(payload.clone())).len();

    // Cap set one byte under the actual encoded length -> reject.
    let too_small = datastore_envelope(payload.clone(), 1, encoded_len - 1);
    assert_eq!(
        too_small,
        Err(TelemetryError::TooLarge {
            bytes: encoded_len,
            max_bytes: encoded_len - 1,
        })
    );

    // Cap set to the exact encoded length -> boundary is inclusive (only
    // `> max_bytes` rejects, matching Python's `if encoded_bytes > cap`).
    let exact = datastore_envelope(payload, 1, encoded_len);
    assert!(exact.is_ok());
}

#[test]
fn envelope_default_datastore_max_bytes_matches_python_constant() {
    let fx = fixture();
    let expected = fx["datastore_max_bytes"].as_i64().unwrap() as usize;
    assert_eq!(expected, 60_000, "Python _DATASTORE_MAX_BYTES == 60000");
}

// =============================================================================
// PyVal::List (R68-8): the list variant, against CPython-derived goldens
// =============================================================================
//
// Added because the `["revenue", "segment-observations"]` producer's payload
// is irreducibly list-bearing (`segment_observations` is an array of
// observation objects, `modules/segment_observations.py:154-160`), and this
// value model had no list variant -- so that payload could not be expressed
// here at all, let alone routed through `datastore_envelope`.
//
// The variant is ADDITIVE: every golden above is untouched and still asserts
// the same bytes. Each expected string below was produced by running the
// equivalent structure through real CPython `json.dumps` with default
// arguments, not hand-written, so the separators (`", "` between elements)
// and the empty-list shape are the interpreter's own output.

/// CPython: `json.dumps({"a": []})`.
#[test]
fn python_dumps_writes_an_empty_list_as_empty_brackets() {
    let mut d = PyDict::new();
    d.push("a", PyVal::List(vec![]));
    assert_eq!(python_dumps(&PyVal::Dict(d)), r#"{"a": []}"#);
}

/// CPython: `json.dumps({"a": [1, 2, 3]})` -- note the `", "` separator,
/// the DEFAULT, not the compact `","` canonical form.
#[test]
fn python_dumps_separates_list_elements_with_comma_space() {
    let mut d = PyDict::new();
    d.push(
        "a",
        PyVal::List(vec![PyVal::Int(1), PyVal::Int(2), PyVal::Int(3)]),
    );
    assert_eq!(python_dumps(&PyVal::Dict(d)), r#"{"a": [1, 2, 3]}"#);
}

/// CPython: `json.dumps({"a": [[1, 2], [], [3]]})`.
#[test]
fn python_dumps_nests_lists_inside_lists() {
    let mut d = PyDict::new();
    d.push(
        "a",
        PyVal::List(vec![
            PyVal::List(vec![PyVal::Int(1), PyVal::Int(2)]),
            PyVal::List(vec![]),
            PyVal::List(vec![PyVal::Int(3)]),
        ]),
    );
    assert_eq!(python_dumps(&PyVal::Dict(d)), r#"{"a": [[1, 2], [], [3]]}"#);
}

/// CPython: `json.dumps({"a": [{"x": 1}, {"y": 2}]})` -- the shape the
/// segment-observations payload actually takes.
#[test]
fn python_dumps_writes_a_list_of_dicts() {
    let mut x = PyDict::new();
    x.push("x", PyVal::Int(1));
    let mut y = PyDict::new();
    y.push("y", PyVal::Int(2));

    let mut d = PyDict::new();
    d.push("a", PyVal::List(vec![PyVal::Dict(x), PyVal::Dict(y)]));
    assert_eq!(
        python_dumps(&PyVal::Dict(d)),
        r#"{"a": [{"x": 1}, {"y": 2}]}"#
    );
}

/// CPython: `json.dumps({"outer": {"inner": [{"k": [7]}]}})` -- dict in list
/// in dict in list, to prove the recursion alternates correctly.
#[test]
fn python_dumps_alternates_dicts_and_lists_to_depth() {
    let mut k = PyDict::new();
    k.push("k", PyVal::List(vec![PyVal::Int(7)]));
    let mut inner = PyDict::new();
    inner.push("inner", PyVal::List(vec![PyVal::Dict(k)]));
    let mut outer = PyDict::new();
    outer.push("outer", PyVal::Dict(inner));

    assert_eq!(
        python_dumps(&PyVal::Dict(outer)),
        r#"{"outer": {"inner": [{"k": [7]}]}}"#
    );
}

/// CPython: `json.dumps({"a": [1, 1.5, "s", True, False]})`.
#[test]
fn python_dumps_writes_every_scalar_kind_inside_a_list() {
    let mut d = PyDict::new();
    d.push(
        "a",
        PyVal::List(vec![
            PyVal::Int(1),
            PyVal::Float(1.5),
            PyVal::Str("s".to_string()),
            PyVal::Bool(true),
            PyVal::Bool(false),
        ]),
    );
    assert_eq!(
        python_dumps(&PyVal::Dict(d)),
        r#"{"a": [1, 1.5, "s", true, false]}"#
    );
}

/// CPython: `json.dumps({"a": ["café", "中"]})` -- `ensure_ascii=True`
/// applies inside lists exactly as it does inside dicts.
#[test]
fn python_dumps_escapes_non_ascii_inside_a_list() {
    let mut d = PyDict::new();
    d.push(
        "a",
        PyVal::List(vec![
            PyVal::Str("café".to_string()),
            PyVal::Str("中".to_string()),
        ]),
    );
    // CPython emits the \u escapes, not the literal characters.
    assert_eq!(
        python_dumps(&PyVal::Dict(d)),
        r#"{"a": ["caf\u00e9", "\u4e2d"]}"#
    );
}

/// CPython: `json.dumps({"a": [0.1, 1e22, 1.0]})` -- `repr` float formatting
/// inside lists, including the `1e+22` exponent form and the `1.0` that must
/// not collapse to `1`.
#[test]
fn python_dumps_uses_repr_float_formatting_inside_a_list() {
    let mut d = PyDict::new();
    d.push(
        "a",
        PyVal::List(vec![
            PyVal::Float(0.1),
            PyVal::Float(1e22),
            PyVal::Float(1.0),
        ]),
    );
    assert_eq!(python_dumps(&PyVal::Dict(d)), r#"{"a": [0.1, 1e+22, 1.0]}"#);
}

/// The envelope must accept a list-bearing payload unchanged -- that is the
/// whole point of the variant. CPython golden for the same dict with
/// `"timestamp"` appended by the envelope rule.
#[test]
fn the_envelope_accepts_a_list_bearing_payload() {
    let mut observation = PyDict::new();
    observation.push("observation_id", PyVal::Str("obs-1040-6".to_string()));

    let mut payload = PyDict::new();
    payload.push("generated_at", PyVal::Int(1050));
    payload.push(
        "segment_observations",
        PyVal::List(vec![PyVal::Dict(observation)]),
    );

    assert_eq!(
        datastore_envelope(payload, 1234, 60_000).expect("a list payload is encodable"),
        r#"{"generated_at": 1050, "segment_observations": [{"observation_id": "obs-1040-6"}], "timestamp": 1234}"#
    );
}
