//! Parity tests against Python truth. Fixtures are generated by
//! `tools/port/gen_canonical_json_fixtures.py` in the `cl_revenue_ops-port`
//! worktree and committed here as `fixtures/canonical_json.json` — see that
//! script for how each case was produced (Python json.dumps(sort_keys=True,
//! separators=(",",":"), ensure_ascii=False) is the arbiter).
use revops_core::canonical::canonical_json;

#[test]
fn canonical_json_matches_python_bytes() {
    let raw = include_str!("../../../fixtures/canonical_json.json");
    let cases: serde_json::Value = serde_json::from_str(raw).unwrap();
    for case in cases.as_array().unwrap() {
        let got = canonical_json(&case["value"]);
        assert_eq!(got, case["canonical"].as_str().unwrap());
    }
}
