//! Parity tests against Python truth. Fixtures are generated by
//! `tools/port/gen_rounding_fixtures.py` in the `cl_revenue_ops-port`
//! worktree and committed here as `fixtures/rounding.json` — see that
//! script for how each case was produced (Python `modules.utils` is the
//! arbiter, nothing here is hand-computed).
use revops_core::msat::{base_to_sats_ceil, base_to_sats_floor, parse_msat, sats_to_base};
use serde_json::Value;

fn fixtures() -> Value {
    let raw = include_str!("../../../fixtures/rounding.json");
    serde_json::from_str(raw).unwrap()
}

#[test]
fn ceil_matches_python() {
    for case in fixtures()["ceil"].as_array().unwrap() {
        let msat = case["msat"].as_u64().unwrap();
        assert_eq!(
            base_to_sats_ceil(msat),
            case["sats"].as_u64().unwrap(),
            "msat={msat}"
        );
    }
}

#[test]
fn floor_matches_python() {
    for case in fixtures()["floor"].as_array().unwrap() {
        let msat = case["msat"].as_u64().unwrap();
        assert_eq!(
            base_to_sats_floor(msat),
            case["sats"].as_u64().unwrap(),
            "msat={msat}"
        );
    }
}

#[test]
fn to_base_matches_python() {
    for case in fixtures()["to_base"].as_array().unwrap() {
        let sats = case["sats"].as_u64().unwrap();
        assert_eq!(
            sats_to_base(sats),
            case["msat"].as_u64().unwrap(),
            "sats={sats}"
        );
    }
}

#[test]
fn parse_matches_python() {
    for case in fixtures()["parse"].as_array().unwrap() {
        let expected = case["msat"].as_i64().unwrap();
        assert_eq!(
            parse_msat(&case["input"]),
            expected,
            "input={:?}",
            case["input"]
        );
    }
}
