//! Futility breaker + per-kind cooldown tables + fill-fraction dest cooldown
//! (pure decision math; consumes [`crate::errors::FailureKind`] /
//! [`crate::errors::cooldown_base_secs`] from Task 1).
//!
//! Golden parity target: `fixtures/rebalance/cooldowns.json`, generated by
//! `tools/port/gen_rebalance_fixtures.py cooldowns` (port repo, branch
//! `phase5-t6-gen`), which drives:
//!
//! - [`persisted_cooldown_secs`] against the REAL `Database.
//!   record_pair_rebalance_failure` (SQL-embedded backoff math,
//!   `database.py:2657-2733`), reading `cooldown_until - last_failure_at`
//!   back after repeated calls build up `failure_count`;
//! - [`dest_cooldown_secs`] against the REAL `RebalanceEngine.
//!   _effective_dest_cooldown_secs` (audit F7, `rebalance_engine_v2.py:
//!   876-927`), fed an explicit `anchor` dict to bypass the DB lookup;
//! - [`drift_override`] is NOT driven (there is no standalone function —
//!   see that function's doc comment).
//!
//! [`PairFutility`] (in-memory, 3 failures / 1800s window per `(src, dst)`,
//! `rebalance_engine_v2.py:158-167,1670-1706`) and [`DestFutility`]
//! (thresholds 4/10, keyed on `to_peer_id` NOT scid — DEF-063,
//! `rebalancer.py:507-544`) are documented, fully-specified-by-the-plan
//! in-memory state machines with no batch input/output table to
//! golden-pin; they are proven by targeted unit tests below instead of a
//! JSON fixture (see `gen_cooldowns`'s docstring in the generator for the
//! same scope note).

use crate::errors::{cooldown_base_secs, FailureKind};

/// Port of the persisted per-pair cooldown backoff
/// (`database.py::record_pair_rebalance_failure`'s SQL: `cooldown_until -
/// last_failure_at == base_cooldown * MIN(MAX(failure_count, 1), 6)`).
/// `failure_count` is the POST-increment count (the count returned by this
/// call, i.e. `>= 1` in practice — `max(failure_count, 1)` is a defensive
/// clamp mirroring the SQL exactly for any stray `<= 0` input).
pub fn persisted_cooldown_secs(kind: FailureKind, failure_count: i64) -> i64 {
    let base = cooldown_base_secs(kind);
    let multiplier = failure_count.clamp(1, 6);
    base * multiplier
}

/// Port of `RebalanceEngine._effective_dest_cooldown_secs` (audit F7,
/// `rebalance_engine_v2.py:876-927`), reduced to take the destination's
/// REMAINING band gap directly (the real function derives it from
/// `target_band_low * capacity_sats - local_sats`; that derivation is the
/// caller's/state-builder's concern, deferred with `rebalance_state_v2.py`
/// per the plan's "Explicitly Deferred" section).
///
/// `amount_sats <= 0` (no anchor / anchor amount not recorded) and
/// `remaining_band_gap_sats <= 0` (channel already at/above the band floor
/// — refill completed) both fall back to the full `base_secs`. Otherwise:
/// `fill_fraction = amount_sats / (amount_sats + remaining_band_gap_sats)`,
/// `effective = base_secs * min(1.0, fill_fraction * 2.0)`, truncated
/// toward zero (py `int(...)`, floor for non-negative values).
pub fn dest_cooldown_secs(base_secs: i64, amount_sats: i64, remaining_band_gap_sats: i64) -> i64 {
    if amount_sats <= 0 || remaining_band_gap_sats <= 0 {
        return base_secs;
    }
    let fill_fraction = amount_sats as f64 / (amount_sats + remaining_band_gap_sats) as f64;
    let scale = (fill_fraction * 2.0).min(1.0);
    (base_secs as f64 * scale) as i64
}

/// Phase 3.3 drift override: `anchor_ratio - current_ratio >= 0.30`
/// (`rebalance_engine_v2.py:1148-1167`, `rebalance_drift_override_ratio`'s
/// config default). This IS the whole function body in Python — a single
/// inline boolean, not a standalone method — so there is nothing to drive
/// via a stub `self`; the fixture instead pins several float-precision
/// edges (e.g. `0.7 - 0.4 == 0.29999999999999993`, NOT exactly `0.30` in
/// IEEE-754 double) that a "helpfully" pre-rounded reimplementation would
/// get wrong.
pub fn drift_override(anchor_ratio: f64, current_ratio: f64) -> bool {
    anchor_ratio - current_ratio >= 0.30
}

/// Port of `RebalanceEngine`'s in-memory pair-level futility tracker
/// (`rebalance_engine_v2.py:158-167` init, `:1670-1715` methods):
/// `{(src, dst): [failure_ts, ...]}`. A pair that fails
/// [`PairFutility::THRESHOLD`] times within [`PairFutility::WINDOW_SECS`]
/// is futile until the stale entries decay out of the window. Success
/// clears the pair's history outright (py `_record_pair_success`).
#[derive(Debug, Default)]
pub struct PairFutility {
    failures: std::collections::HashMap<(String, String), Vec<f64>>,
}

impl PairFutility {
    /// Py `_futility_threshold` (`rebalance_engine_v2.py:166`).
    pub const THRESHOLD: usize = 3;
    /// Py `_futility_window_sec` (`rebalance_engine_v2.py:167`).
    pub const WINDOW_SECS: f64 = 1800.0;

    pub fn new() -> Self {
        Self::default()
    }

    /// Port of `_prune_pair_failures`: drop timestamps older than the
    /// window, dropping the map entry entirely once empty (mirrors
    /// Python's `pop` on empty survivors).
    fn prune(&mut self, key: &(String, String), now: f64) -> usize {
        let cutoff = now - Self::WINDOW_SECS;
        match self.failures.get_mut(key) {
            None => 0,
            Some(timestamps) => {
                timestamps.retain(|t| *t >= cutoff);
                if timestamps.is_empty() {
                    self.failures.remove(key);
                    0
                } else {
                    timestamps.len()
                }
            }
        }
    }

    /// Port of `_is_pair_in_futility`.
    pub fn is_futile(&mut self, source: &str, dest: &str, now: f64) -> bool {
        let key = (source.to_string(), dest.to_string());
        self.prune(&key, now) >= Self::THRESHOLD
    }

    /// In-window failure count for a pair (py `_failure_count` /
    /// `len(_prune_pair_failures(key))`, `rebalance_engine_v2.py:346-347`).
    /// Added by T7 (engine): the audit skip detail and the sats-EV
    /// failure-penalty fold both need the raw count, not just the boolean.
    pub fn fresh_failure_count(&mut self, source: &str, dest: &str, now: f64) -> usize {
        let key = (source.to_string(), dest.to_string());
        self.prune(&key, now)
    }

    /// Port of `_record_pair_failure`.
    pub fn record_failure(&mut self, source: &str, dest: &str, now: f64) {
        self.failures
            .entry((source.to_string(), dest.to_string()))
            .or_default()
            .push(now);
    }

    /// Port of `_record_pair_success`: clears the pair's failure history
    /// outright.
    pub fn record_success(&mut self, source: &str, dest: &str) {
        self.failures
            .remove(&(source.to_string(), dest.to_string()));
    }
}

/// Port of `EVRebalancer._futility_key` (`rebalancer.py:534-544`, DEF-063):
/// a splice mints a new SCID for the same peer, resetting SCID-keyed
/// failure history and letting a chronically-failing pair evade the
/// breaker. Key on the destination peer pubkey (stable across splices),
/// falling back to the channel id only when the peer id is unknown/empty.
pub fn dest_futility_key(to_peer_id: &str, to_channel: &str) -> String {
    if to_peer_id.is_empty() {
        to_channel.to_string()
    } else {
        to_peer_id.to_string()
    }
}

/// Failure classification the destination futility breaker's threshold
/// depends on (py `EVRebalancer._classify_error`, `rebalancer.py:522-532`,
/// reduced to the two buckets [`DestFutility::should_skip`] distinguishes).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DestErrorClass {
    /// `"no_route"` / `"budget_exceeded"` — structural problems unlikely to
    /// resolve within a cycle; trips the breaker at 4 attempts.
    Structural,
    /// Everything else; trips the breaker at 10 attempts (existing
    /// threshold).
    Other,
}

/// Port of `EVRebalancer`'s destination futility/failure-count breaker
/// (`rebalancer.py:507-544`): DB-persisted in production (`increment_
/// failure_count`/`reset_failure_count`), reduced here to the in-memory
/// decision math `_should_skip_futility` implements — persistence is a
/// `RebalanceStore` (T7 engine.rs) concern, out of scope for this pure
/// module.
#[derive(Debug, Default)]
pub struct DestFutility {
    counts: std::collections::HashMap<String, i64>,
}

impl DestFutility {
    /// Py `_should_skip_futility`'s structural-error threshold
    /// (`rebalancer.py:512-517`: `no_route`/`budget_exceeded` trip at 4).
    pub const STRUCTURAL_THRESHOLD: i64 = 4;
    /// Py `_should_skip_futility`'s catch-all threshold (`rebalancer.py:
    /// 518`: everything else trips at 10, "the existing threshold").
    pub const OTHER_THRESHOLD: i64 = 10;

    pub fn new() -> Self {
        Self::default()
    }

    /// Port of `Database.increment_failure_count`'s counter semantics
    /// (count-only; `error_type`'s classification is applied at read time
    /// by [`Self::should_skip`], matching `_should_skip_futility`'s
    /// `last_error_type` parameter being whatever the MOST RECENT failure
    /// classified as).
    pub fn record_failure(&mut self, key: &str) -> i64 {
        let entry = self.counts.entry(key.to_string()).or_insert(0);
        *entry += 1;
        *entry
    }

    /// Port of `Database.reset_failure_count`: success clears the counter.
    pub fn record_success(&mut self, key: &str) {
        self.counts.remove(key);
    }

    pub fn failure_count(&self, key: &str) -> i64 {
        *self.counts.get(key).unwrap_or(&0)
    }

    /// Port of `EVRebalancer._should_skip_futility` (`rebalancer.py:
    /// 507-520`): `(last_error_class == Structural && fail_count >= 4) ||
    /// fail_count >= 10`.
    pub fn should_skip(fail_count: i64, last_error_class: DestErrorClass) -> bool {
        if last_error_class == DestErrorClass::Structural
            && fail_count >= Self::STRUCTURAL_THRESHOLD
        {
            return true;
        }
        fail_count >= Self::OTHER_THRESHOLD
    }

    /// Convenience: [`Self::should_skip`] applied to this tracker's current
    /// count for `key`.
    pub fn is_futile(&self, key: &str, last_error_class: DestErrorClass) -> bool {
        Self::should_skip(self.failure_count(key), last_error_class)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pair_futility_threshold_and_window() {
        let mut pf = PairFutility::new();
        let now = 1_700_000_000.0;
        assert!(!pf.is_futile("src", "dst", now));
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now + 10.0);
        assert!(!pf.is_futile("src", "dst", now + 20.0));
        pf.record_failure("src", "dst", now + 20.0);
        assert!(pf.is_futile("src", "dst", now + 20.0));
    }

    #[test]
    fn pair_futility_window_decay() {
        let mut pf = PairFutility::new();
        let now = 1_700_000_000.0;
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now);
        assert!(pf.is_futile("src", "dst", now));
        // Past the 1800s window: all three timestamps prune away.
        assert!(!pf.is_futile("src", "dst", now + PairFutility::WINDOW_SECS + 1.0));
    }

    #[test]
    fn pair_futility_success_clears_history() {
        let mut pf = PairFutility::new();
        let now = 1_700_000_000.0;
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now);
        assert!(pf.is_futile("src", "dst", now));
        pf.record_success("src", "dst");
        assert!(!pf.is_futile("src", "dst", now));
    }

    #[test]
    fn pair_futility_keys_are_independent() {
        let mut pf = PairFutility::new();
        let now = 1_700_000_000.0;
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now);
        pf.record_failure("src", "dst", now);
        assert!(!pf.is_futile("src", "other-dst", now));
        assert!(!pf.is_futile("other-src", "dst", now));
    }

    #[test]
    fn dest_futility_key_prefers_peer_id_def_063() {
        assert_eq!(dest_futility_key("peer-1", "123x1x0"), "peer-1");
        assert_eq!(dest_futility_key("", "123x1x0"), "123x1x0");
    }

    #[test]
    fn dest_futility_structural_trips_at_4() {
        let mut df = DestFutility::new();
        for _ in 0..3 {
            df.record_failure("peer-1");
        }
        assert!(!df.is_futile("peer-1", DestErrorClass::Structural));
        df.record_failure("peer-1");
        assert!(df.is_futile("peer-1", DestErrorClass::Structural));
        // The SAME count does not trip the "other" class yet (10 needed).
        assert!(!df.is_futile("peer-1", DestErrorClass::Other));
    }

    #[test]
    fn dest_futility_other_trips_at_10() {
        let mut df = DestFutility::new();
        for _ in 0..9 {
            df.record_failure("peer-1");
        }
        assert!(!df.is_futile("peer-1", DestErrorClass::Other));
        df.record_failure("peer-1");
        assert!(df.is_futile("peer-1", DestErrorClass::Other));
    }

    #[test]
    fn dest_futility_success_resets_counter() {
        let mut df = DestFutility::new();
        for _ in 0..10 {
            df.record_failure("peer-1");
        }
        assert!(df.is_futile("peer-1", DestErrorClass::Other));
        df.record_success("peer-1");
        assert_eq!(df.failure_count("peer-1"), 0);
        assert!(!df.is_futile("peer-1", DestErrorClass::Other));
    }
}
