//! Sats-EV gate + per-attempt ceiling + fee escalation (pure decision math).
//!
//! Port of the sats-EV gate terms in `modules/rebalance_engine_v2.py`
//! (`_build_score_decomposition`, `EXPECTED_UTILIZATION` /
//! `SOURCE_UTILIZATION_DISCOUNT` / `FAILURE_COST_RATE` /
//! `UNVALIDATED_ADVERTISED_FEE_DISCOUNT`, the inline hold-margin gate in
//! `find_candidates` at `rebalance_engine_v2.py:1449-1510`, and
//! `_per_attempt_fee_ceiling`), plus `modules/rebalancer.py`'s
//! `EVRebalancer._apply_fee_escalation`.
//!
//! Golden parity target: `fixtures/rebalance/ev.json`, generated by
//! `tools/port/gen_rebalance_fixtures.py ev` (port repo, branch
//! `phase5-t6-gen`) driving the REAL Python functions with stub self/pair/
//! cfg objects — see that generator's `gen_ev` docstring for the exact
//! technique. All floats compared via `revops_econ::pyfloat::py_repr`
//! string equality (Global Constraints: byte-parity discipline); every sats
//! score is rounded to 6 decimals via `revops_econ::pyfloat::py_round`.
//!
//! ## Scope: a reduced `EvInputs` (documented, not an oversight)
//!
//! The real `_build_score_decomposition` computes `expected_future_value_
//! sats`/`source_opportunity_sats`/`activity_penalty_sats` FROM raw ppm/
//! utilization/activity inputs using [`EXPECTED_UTILIZATION`]/
//! [`SOURCE_UTILIZATION_DISCOUNT`]/[`UNVALIDATED_ADVERTISED_FEE_DISCOUNT`].
//! [`EvInputs`] takes those three terms ALREADY COMPUTED — the raw-to-sats
//! reduction is exercised in the fixture generator (driving the real
//! function directly), not re-derived here; only the resulting sats numbers
//! cross this module's interface boundary. The three named constants are
//! still exported `pub` from this module as the frozen contract values a
//! future caller (T7's `engine.rs`) needs to perform that reduction itself.
//!
//! [`EvInputs`] also carries no `failure_count`: every fixture case is
//! driven with an EMPTY in-cycle failure history, so the real formula's
//! `failure_penalty_sats` term (`failure_count * expected_fee_sats *
//! FAILURE_COST_RATE`) is always exactly `0.0` and drops out, leaving the
//! reduced 4-term formula this module implements (`p*efv - fee -
//! source_opp - activity_penalty`) byte-identical to the real 5-term one
//! for every fixture case. [`FAILURE_COST_RATE`] is still exported `pub` as
//! the frozen constant a future caller combines with `cooldowns.rs`'s
//! failure-count trackers to fold a failure penalty into `fee_sats` (or a
//! sibling term) before calling [`sats_ev_gate`].
//!
//! `sats_ev_gate` also does not implement Python's third `p_success` branch
//! (`rejection_reason == "no_route"` forcing `p_success = 0.05`): `EvInputs`
//! has no `rejection_reason` field, matching the frozen 2-branch contract
//! in the plan's brief (probability-present clamp vs. no-probability
//! prior/empirical blend only).

use revops_econ::pyfloat::py_round;

/// Audit F2/RE-H1/H2: expected fraction of refilled liquidity actually
/// routed within the evaluation horizon (the flat prior used when a
/// channel's own utilization has not been realized/measured yet).
pub const EXPECTED_UTILIZATION: f64 = 0.5;
/// The source was over-full: its marginal sat routes with lower probability
/// than the destination's marginal sat, so its forgone earnings are
/// discounted relative to the destination's expected earnings.
pub const SOURCE_UTILIZATION_DISCOUNT: f64 = 0.5;
/// Each recent in-window failure of a pair charges this fraction of the
/// route cost as an expected-retry penalty (`failure_penalty_sats`).
pub const FAILURE_COST_RATE: f64 = 0.25;
/// E-4.3: the destination's ADVERTISED outbound fee is an unvalidated ask;
/// discounted by this factor before competing with realized evidence unless
/// the destination has a validated forward history.
pub const UNVALIDATED_ADVERTISED_FEE_DISCOUNT: f64 = 0.5;

/// Reason string surfaced when a priced pair's sats-EV score does not clear
/// the configured hold margin (py `"below_hold_margin"`,
/// `rebalance_engine_v2.py:1478,1492,1502`). Error/reason strings are
/// contracts (Global Constraints); this one is local to the gate rather
/// than centralized in `errors.rs` because it is not one of the listed
/// engine failure-classifier strings — it is a planner/gate REJECTION
/// reason, a different contract surface (audit + skip records).
pub const BELOW_HOLD_MARGIN: &str = "below_hold_margin";

/// Inputs to the sats-EV do-nothing gate (py `_build_score_decomposition`'s
/// sats terms + the inline hold-margin check). See the module doc comment
/// for the scope note on why this is a reduced, already-partially-computed
/// input set.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EvInputs {
    /// Router-reported success probability in parts-per-million; `<= 0`
    /// means "no probability reported" (falls back to the prior/empirical
    /// blend below).
    pub probability_ppm: i64,
    /// Destination attempt count backing the empirical success-rate blend
    /// (py `_query_dest_success_rate`'s `total >= 3` gate).
    pub dest_attempts: i64,
    /// Destination empirical success rate in `[0, 1]` (only consulted when
    /// `dest_attempts >= 3` and `probability_ppm <= 0`).
    pub dest_success_rate: f64,
    /// Already-computed `expected_future_value_sats` (destination refill
    /// value + source drain value).
    pub efv_sats: f64,
    /// `expected_fee_sats` — the route's actual/estimated cost in sats.
    /// `<= 0` triggers the zero-cost bypass (always passes).
    pub fee_sats: i64,
    /// Already-computed `source_opportunity_sats`.
    pub source_opportunity_sats: f64,
    /// Already-computed `activity_penalty_sats` (feature #1, capped soft
    /// penalty for channels already being helpfully moved by live flow).
    pub activity_penalty_sats: f64,
    /// The configured `rebalance_hold_margin` (py `cfg.rebalance_hold_
    /// margin`, default `0.0`).
    pub hold_margin_sats: f64,
}

/// Verdict of the sats-EV gate.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EvVerdict {
    pub pass: bool,
    /// `round(p_success * efv_sats - fee_sats - source_opportunity_sats -
    /// activity_penalty_sats, 6)` (py `final_score_sats`).
    pub final_score_sats: f64,
    /// `Some(BELOW_HOLD_MARGIN)` when rejected, `None` when passing.
    pub reject_reason: Option<&'static str>,
}

/// Py `_build_score_decomposition`'s `p_success` derivation
/// (`rebalance_engine_v2.py:430-442`), reduced to the two branches
/// `EvInputs` supports (see module doc comment):
///
/// - `probability_ppm > 0`: `clamp(probability_ppm / 1e6, 0.05, 0.99)`.
/// - else, `dest_attempts >= 3`: blend the `0.5` prior with the empirical
///   rate as `clamp(0.5 * (0.5 + dest_success_rate), 0.05, 0.95)`.
/// - else: flat `0.5` prior (no probability, insufficient history).
fn p_success(probability_ppm: i64, dest_attempts: i64, dest_success_rate: f64) -> f64 {
    if probability_ppm > 0 {
        return (probability_ppm as f64 / 1_000_000.0).clamp(0.05, 0.99);
    }
    if dest_attempts >= 3 {
        return (0.5 * (0.5 + dest_success_rate)).clamp(0.05, 0.95);
    }
    0.5
}

/// Port of the sats-EV do-nothing gate: py `_build_score_decomposition`'s
/// `final_score_sats` formula (reduced per the module doc comment) plus the
/// inline hold-margin check at `rebalance_engine_v2.py:1468-1472`
/// (`final_score_present and route_cost_sats > 0 and final_score <
/// hold_margin` → reject `"below_hold_margin"`). Zero-cost routes
/// (`fee_sats <= 0`) ALWAYS pass — the zero-budget equalization invariant.
pub fn sats_ev_gate(i: &EvInputs) -> EvVerdict {
    let p = p_success(i.probability_ppm, i.dest_attempts, i.dest_success_rate);
    let raw =
        p * i.efv_sats - i.fee_sats as f64 - i.source_opportunity_sats - i.activity_penalty_sats;
    let final_score_sats = py_round(raw, 6);
    let rejected = i.fee_sats > 0 && final_score_sats < i.hold_margin_sats;
    EvVerdict {
        pass: !rejected,
        final_score_sats,
        reject_reason: if rejected {
            Some(BELOW_HOLD_MARGIN)
        } else {
            None
        },
    }
}

/// Port of `_per_attempt_fee_ceiling` (`rebalance_engine_v2.py:1803-1829`,
/// audit F1): bound a single attempt's fee by the ppm cap on amount —
/// `min(prob_adjusted_budget_sats, ceil(amount_sats * pair_fee_cap_ppm /
/// 1e6))`. `pair_fee_cap_ppm <= 0` or `amount_sats <= 0` disables the
/// ceiling (legacy: budget only); `prob_adjusted_budget_sats <= 0`
/// preserves the zero-budget equalization invariant (only free routes
/// admitted). Integer-exact ceil via `(amount * ppm + 999_999) / 1_000_000`
/// (Global Constraints).
pub fn per_attempt_ceiling(
    prob_adjusted_budget_sats: i64,
    amount_sats: i64,
    pair_fee_cap_ppm: i64,
) -> i64 {
    let budget = prob_adjusted_budget_sats.max(0);
    if pair_fee_cap_ppm <= 0 || amount_sats <= 0 {
        return budget;
    }
    let ppm_cap_sats = (amount_sats * pair_fee_cap_ppm + 999_999) / 1_000_000;
    budget.min(ppm_cap_sats)
}

/// Port of `EVRebalancer._apply_fee_escalation`'s escalation arithmetic
/// (`rebalancer.py:547-558`), reduced to its 2-argument core per the frozen
/// interface. Python: `if fail_count == 0 or last_attempted_ppm <= 0: return
/// ev_max_fee_ppm; if last_attempted_ppm >= ev_max_fee_ppm: return
/// ev_max_fee_ppm; return min(int(last_attempted_ppm * 1.5),
/// ev_max_fee_ppm)`.
///
/// The `fail_count == 0` guard is NOT representable here (no `fail_count`
/// parameter in the reduced 2-argument signature) and is the CALLER's
/// responsibility: a caller only reaches for escalation once it already
/// knows a prior attempt failed, i.e. `fail_count >= 1` always holds by the
/// time this is called. The `last_attempted_sats <= 0` guard, however, IS
/// fully expressible from the two given arguments alone (it does not
/// depend on `fail_count`), so it is ported here directly — pinned by the
/// fixture's `last_zero_still_driven_with_failcount_1` case (Python returns
/// `ev_max_fee_ppm` unmodified for `last_attempted_ppm <= 0` regardless of
/// `fail_count`). The `last_attempted_ppm >= ev_max_fee_ppm` guard needs no
/// separate branch: `last * 1.5 >= last >= ev_max` already makes
/// `min(escalated, ev_max) == ev_max`. Python's `int(x * 1.5)` truncates
/// toward zero, matching Rust's `as i64` cast on a non-negative `f64`.
pub fn fee_escalation(last_attempted_sats: i64, ev_max_sats: i64) -> i64 {
    if last_attempted_sats <= 0 {
        return ev_max_sats;
    }
    let escalated = (last_attempted_sats as f64 * 1.5) as i64;
    escalated.min(ev_max_sats)
}
