//! Native route executor: strict validation, `payment_pending` semantics
//! (port of `modules/rebalance_native_executor_v2.py`, `NativeRouteExecutor`,
//! `~/bin/cl_revenue_ops-port`, branch `port`).
//!
//! Golden parity: `fixtures/rebalance/executor.json`, generated by
//! `tools/port/gen_rebalance_fixtures.py executor` (port repo, branch
//! `phase5-t5-gen`) driving the REAL Python executor over a scripted
//! payment-RPC double.
//!
//! ## Safety contracts carried by this module
//!
//! - **payment_pending — abandon, never cancel** (production incident,
//!   `rebalance_native_executor_v2.py:342-363,492-514`): when a payment may
//!   still settle (`waitsendpay` code 200 / proxy timeout / `waitsendpay_
//!   status=pending`, each only AFTER `sendpay` was attempted), the executor
//!   sets `payment_pending=true`, surfaces the PLANNED fee, keeps the
//!   invoice AND the payment (no `delpay`/`delinvoice`), emits NO route
//!   exclusions and NO segment observations, and returns
//!   `payment_pending_timeout: <msg>`. Deleting the invoice here would allow
//!   an immediate repeat payment while the first HTLC can still settle.
//! - **DryRun cuts at the INVOICE boundary** ([`PaymentMode`]): validation
//!   and pricing run identically to Live, but the very first payment RPC —
//!   `invoice` — is never issued; the gate returns
//!   [`DRYRUN_GATE_SENDPAY_DISABLED`] having called ZERO [`PaymentRpc`]
//!   methods. The `Live` variant of [`PaymentMode`] is constructed ONLY by
//!   the cutover task — `tests/executor.rs::payment_mode_live_not_
//!   constructed_in_crate` scans every crate's src tree for the
//!   path-qualified token (so even mentioning it here would trip the scan)
//!   to enforce it.
//! - **Strict route validation before any RPC** (`_validate_route`,
//!   `rebalance_native_executor_v2.py:277-332`): first hop is the source
//!   SCID, final hop is the dest SCID AND our node id, final amount is
//!   exactly `amount_sats*1000`, amounts are monotone non-increasing, and
//!   the planned fee fits `max_fee_sats` — else
//!   `native_route_invalid: <reason>` / `native_route_over_budget: ...`
//!   (which, matching Python's `f"{prefix}: {reason}"`, renders as
//!   `native_route_over_budget: route_over_budget: X > Y`).
//! - **Error strings are contracts**: prefixes come from [`crate::errors`]
//!   verbatim; the executor-scoped [`NATIVE_INVOICE_ERROR_PREFIX`] (NX-4)
//!   and [`DRYRUN_GATE_SENDPAY_DISABLED`] (Rust-only gate; Python has no
//!   dry-run) are defined here — they are not part of T1's global list.
//!
//! ## Port deviations (documented, deliberate)
//!
//! - `our_id` arrives via [`ExecuteRequest`] (Python's engine injects it the
//!   same way via the `our_id=` ctor kwarg, skipping the lazy `getinfo`);
//!   `execute` therefore NEVER calls [`PaymentRpc::getinfo_id`] — that
//!   method exists on the seam for the engine's `is_available` probe at
//!   wiring time (T7/T8).
//! - `now_ms` arrives via [`ExecuteRequest`] (Python calls `time.time()`
//!   inline): the invoice label is `rebal-native-{now_ms}-{dest_scid}` and
//!   segment observations get `observed_at = now_ms / 1000`.
//! - **RPC error encoding** (the seam convention, mirrored by the fixture
//!   generator): a structured CLN RPC error (pyln `RpcError.error` dict) is
//!   carried as `RpcFailure{ message: <the error dict as JSON text> }`;
//!   [`error_details`] parses the message as JSON to recover
//!   `code`/`message`/`data` exactly like Python's `_error_details` reads
//!   `exc.error` (structured errors must carry a non-empty `"message"`).
//!   Plain-text failures stay plain text. Proxy timeouts are plain-text
//!   messages containing `"rpc timeout"` (Python detects the
//!   `RPCTimeoutError` class first and falls back to the same substring —
//!   the generator asserts every scripted timeout carries the substring so
//!   both detectors agree).
//! - The frozen [`PaymentRpc::sendpay`] has no `amount_msat` parameter
//!   (Python passes `amount_sats*1000` explicitly): validation pins the
//!   final hop to exactly that value, so the live impl derives it from
//!   `route.last().amount_msat` (the generator asserts the equivalence).
//!   It also has no `description` parameter on `invoice` — Python's
//!   cosmetic `"cl_revenue_ops rebalance {src}->{dst}"` string is not part
//!   of the seam; the live impl supplies its own description.
//! - `bolt11`/`payment_secret` are passed as `""` when the invoice response
//!   omits them (Python omits the keys; the live impl must translate `""`
//!   back to key-omission).
//! - [`crate::segstore::SegmentObservationStore::record`] is T3's narrowed
//!   six-parameter interface: Python's `observation_context` pass-through
//!   (`source_channel_id`/`dest_channel_id`/`route_policy`/`router_kind`/
//!   `correlation_id`) is dropped — the same documented scope decision as
//!   segstore's, and the fixture (generated with `observation_context=None`,
//!   i.e. all-empty context) matches exactly.

use serde_json::{json, Map, Value};

use crate::errors::{
    NATIVE_ROUTE_INVALID_PREFIX, NATIVE_ROUTE_OVER_BUDGET_PREFIX, NATIVE_SENDPAY_ERROR_PREFIX,
    PAYMENT_PENDING_TIMEOUT_PREFIX,
};
use crate::router::{RpcFailure, SendpayHop};
use crate::segstore::SegmentObservationStore;
use crate::types::ExecutionResult;

/// `rebalance_native_executor_v2.py:19` (`INVOICE_EXPIRY_SEC`).
pub const INVOICE_EXPIRY_SEC: i64 = 300;
/// `rebalance_native_executor_v2.py:20` (`SENDPAY_TIMEOUT_SEC`) — both the
/// `waitsendpay` `timeout` param and the proxy-deadline extension.
pub const SENDPAY_TIMEOUT_SEC: i64 = 60;
/// `rebalance_native_executor_v2.py:205` (`ATTRIBUTED_CONFIDENCE`): CLN
/// named channel AND direction.
pub const ATTRIBUTED_CONFIDENCE: f64 = 0.85;
/// `rebalance_native_executor_v2.py:206` (`INFERRED_CONFIDENCE_FLOOR`): the
/// all-middle-hops fallback splits blame `0.85/n`, never below this floor.
pub const INFERRED_CONFIDENCE_FLOOR: f64 = 0.2;
/// The DryRun gate's error string (Rust-only: Python has no dry-run mode;
/// the plan's Task 5 contract pins this exact text). Executor-scoped, so it
/// lives here rather than in T1's frozen `errors.rs` list.
pub const DRYRUN_GATE_SENDPAY_DISABLED: &str = "dryrun_gate: sendpay_disabled";
/// `rebalance_native_executor_v2.py:376` (NX-4 malformed invoice response):
/// `f"native_invoice_error: {reason}"`. Executor-scoped (see above).
pub const NATIVE_INVOICE_ERROR_PREFIX: &str = "native_invoice_error: ";

/// Narrow payment-RPC seam — fixtures/tests script it; the live impl lands
/// at cutover. See the module docs for the error-encoding and
/// parameter-derivation conventions live impls must follow.
pub trait PaymentRpc {
    /// `getinfo`'s `id` — used by the engine's availability probe, never by
    /// [`NativeRouteExecutor::execute`] (which takes the injected
    /// [`ExecuteRequest::our_id`]).
    fn getinfo_id(&self) -> Result<String, RpcFailure>;
    /// `invoice` with expiry [`INVOICE_EXPIRY_SEC`].
    fn invoice(&self, amount_msat: i64, label: &str, expiry_secs: i64)
        -> Result<Value, RpcFailure>;
    fn sendpay(
        &self,
        route: &[SendpayHop],
        payment_hash: &str,
        bolt11: &str,
        payment_secret: &str,
    ) -> Result<Value, RpcFailure>;
    /// `waitsendpay` with timeout [`SENDPAY_TIMEOUT_SEC`]; CLN code 200 =
    /// timed out, payment STILL PENDING.
    fn waitsendpay(&self, payment_hash: &str, timeout_secs: i64) -> Result<Value, RpcFailure>;
    fn delpay(&self, payment_hash: &str, status: &str) -> Result<(), RpcFailure>;
    fn delinvoice(&self, label: &str, status: &str) -> Result<(), RpcFailure>;
}

/// Sendpay-path gate (Global Constraints): `Live` is constructed ONLY by
/// the cutover task — a source-scan test asserts no construction site in
/// any crate's src tree.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PaymentMode {
    DryRun,
    Live,
}

/// One execution request — the Python `execute(...)` positional arguments
/// plus the injected `our_id` and the caller-supplied clock (see the module
/// docs on both deviations).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExecuteRequest {
    pub route: Vec<SendpayHop>,
    pub amount_sats: i64,
    pub source_channel_id: String,
    pub dest_channel_id: String,
    pub max_fee_sats: i64,
    pub our_id: String,
    /// Wall-clock milliseconds: invoice label timestamp; `/1000` is the
    /// segment-observation `observed_at`.
    pub now_ms: i64,
}

/// Execute an already-priced circular route with CLN sendpay
/// (`NativeRouteExecutor`, `rebalance_native_executor_v2.py:16-537`).
pub struct NativeRouteExecutor<'a> {
    pub rpc: &'a dyn PaymentRpc,
    pub mode: PaymentMode,
    pub segstore: &'a SegmentObservationStore,
}

// ---------------------------------------------------------------------------
// Pure helpers (ported statics)
// ---------------------------------------------------------------------------

/// `utils.base_to_sats_ceil` (`-(-base // 1000)`), for non-negative msat.
fn base_to_sats_ceil(base_msat: i64) -> i64 {
    debug_assert!(base_msat >= 0);
    (base_msat + 999) / 1000
}

/// `utils.parse_msat` for the JSON shapes the executor meets (int / float /
/// `"Nmsat"` string / null; anything unparseable -> 0, matching Python's
/// lenient fallback).
fn parse_msat(v: &Value) -> i64 {
    match v {
        Value::Number(n) => n
            .as_i64()
            .or_else(|| n.as_f64().map(|f| f as i64))
            .unwrap_or(0),
        Value::String(s) => {
            let s = s.trim();
            let s = s.strip_suffix("msat").unwrap_or(s);
            s.parse().unwrap_or(0)
        }
        _ => 0,
    }
}

/// `_route_summary` (`rebalance_native_executor_v2.py:109-125`), over typed
/// hops (every field is present by construction).
fn route_summary(route: &[SendpayHop]) -> Value {
    Value::Array(
        route
            .iter()
            .enumerate()
            .map(|(index, hop)| {
                json!({
                    "index": index,
                    "channel": hop.channel,
                    "direction": hop.direction,
                    "id": hop.id,
                    "amount_msat": hop.amount_msat,
                    "delay": hop.delay,
                })
            })
            .collect(),
    )
}

/// `_failure_class` (`rebalance_native_executor_v2.py:127-136`), checked in
/// Python's exact order.
fn failure_class(error_text: &str) -> &'static str {
    let normalized = error_text.to_lowercase();
    if normalized.contains("temporary_channel_failure") {
        return "liquidity";
    }
    if normalized.contains("fee_insufficient") || normalized.contains("incorrect_cltv_expiry") {
        return "fee";
    }
    if normalized.contains("timeout") || normalized.contains("deadline") {
        return "timeout";
    }
    "unknown"
}

/// `_error_details` (`rebalance_native_executor_v2.py:82-107`) under the
/// seam's error encoding: a JSON-object message is the structured
/// `RpcError.error` dict (code/message + data attribution keys); anything
/// else is a plain-text failure with empty details.
fn error_details(failure: &RpcFailure) -> (String, Map<String, Value>) {
    let mut details = Map::new();
    let Ok(Value::Object(err)) = serde_json::from_str::<Value>(&failure.message) else {
        return (failure.message.clone(), details);
    };
    for key in ["code", "message"] {
        if let Some(v) = err.get(key) {
            details.insert(key.to_string(), v.clone());
        }
    }
    if let Some(Value::Object(data)) = err.get("data") {
        for key in [
            "erring_channel",
            "erring_direction",
            "erring_node",
            "erring_index",
            "failcode",
            "failcodename",
            "failcode_name",
        ] {
            if let Some(v) = data.get(key) {
                details.insert(key.to_string(), v.clone());
            }
        }
    }
    let text = match err.get("message") {
        Some(Value::String(msg)) if !msg.is_empty() => msg.clone(),
        // Python falls back to str(err) (the dict repr); the seam convention
        // requires structured errors to carry a message, so the raw JSON
        // text is the closest faithful stand-in and never fixture-compared.
        _ => failure.message.clone(),
    };
    (text, details)
}

/// `_compact_detail_suffix` (`rebalance_native_executor_v2.py:138-154`):
/// fixed key order; `None`/`""` skipped (`0` is kept, matching Python's
/// `not in (None, "")`).
fn compact_detail_suffix(details: &Map<String, Value>) -> String {
    const KEYS: [&str; 7] = [
        "failcodename",
        "failcode_name",
        "failcode",
        "erring_channel",
        "erring_direction",
        "erring_index",
        "erring_node",
    ];
    let parts: Vec<String> = KEYS
        .iter()
        .filter_map(|key| {
            let v = details.get(*key)?;
            let text = match v {
                Value::Null => return None,
                Value::String(s) if s.is_empty() => return None,
                Value::String(s) => s.clone(),
                other => other.to_string(),
            };
            Some(format!("{key}={text}"))
        })
        .collect();
    if parts.is_empty() {
        String::new()
    } else {
        format!(" ({})", parts.join(", "))
    }
}

/// Python's `direction in (0, 1, "0", "1")` + `int(direction)`.
fn direction_as_bit(v: Option<&Value>) -> Option<u8> {
    match v {
        Some(Value::Number(n)) => match n.as_i64() {
            Some(0) => Some(0),
            Some(1) => Some(1),
            _ => None,
        },
        Some(Value::String(s)) => match s.as_str() {
            "0" => Some(0),
            "1" => Some(1),
            _ => None,
        },
        _ => None,
    }
}

/// `_exclude_from_failure` (`rebalance_native_executor_v2.py:156-194`).
fn exclude_from_failure(
    route: &[SendpayHop],
    details: &Map<String, Value>,
    error_text: &str,
) -> Vec<String> {
    let channel = details
        .get("erring_channel")
        .and_then(Value::as_str)
        .unwrap_or("")
        .trim()
        .to_string();
    let direction = direction_as_bit(details.get("erring_direction"));
    if !channel.is_empty() {
        if let Some(direction) = direction {
            return vec![format!("{channel}/{direction}")];
        }
        return vec![channel];
    }

    if !matches!(failure_class(error_text), "liquidity" | "fee") {
        return Vec::new();
    }

    // If CLN does not name the erring channel, avoid replaying the exact
    // failed external middle path on the immediate retry. First and final
    // hops are pinned local channels, so only MIDDLE hops are useful
    // exclusions for alternate route discovery.
    let mut exclusions = Vec::new();
    if route.len() > 2 {
        for hop in &route[1..route.len() - 1] {
            let scid = hop.channel.trim();
            if scid.is_empty() {
                continue;
            }
            // SendpayHop.direction is typed u8; the router only ever emits
            // 0/1, so the Python `direction in (0,1,"0","1")` guard reduces
            // to the always-directional entry.
            let entry = format!("{scid}/{}", hop.direction);
            if !exclusions.contains(&entry) {
                exclusions.push(entry);
            }
        }
    }
    exclusions
}

/// `_is_payment_unresolved` (`rebalance_native_executor_v2.py:334-363`):
/// true when the payment may still settle despite the failure. `code` 200
/// is CLN's "timed out, payment still pending"; a proxy deadline
/// (plain-text `"rpc timeout"`, see the module docs) on sendpay/waitsendpay
/// leaves the HTLC state unknown; `waitsendpay_status=pending` is the
/// non-complete non-failed poll result.
fn is_payment_unresolved(
    payment_attempted: bool,
    raw_message: &str,
    error_text: &str,
    details: &Map<String, Value>,
) -> bool {
    if !payment_attempted {
        return false;
    }
    if details.get("code").and_then(Value::as_i64) == Some(200) {
        return true;
    }
    if raw_message.to_lowercase().contains("rpc timeout") {
        return true;
    }
    error_text.contains("waitsendpay_status=pending")
}

// ---------------------------------------------------------------------------
// Executor
// ---------------------------------------------------------------------------

/// The Python try-block's failure carrier: `raw_message` is `str(exc)` (the
/// proxy-timeout detector's input), `error_text`/`details` are
/// `_error_details(exc)`.
struct Failure {
    raw_message: String,
    error_text: String,
    details: Map<String, Value>,
}

impl Failure {
    fn from_rpc(failure: RpcFailure) -> Self {
        let (error_text, details) = error_details(&failure);
        Failure {
            raw_message: failure.message,
            error_text,
            details,
        }
    }

    fn internal(text: String) -> Self {
        Failure {
            raw_message: text.clone(),
            error_text: text,
            details: Map::new(),
        }
    }
}

/// What the payment attempt produced before any failure handling.
struct AttemptOutcome {
    paid: Value,
}

impl<'a> NativeRouteExecutor<'a> {
    /// Port of `execute` (`rebalance_native_executor_v2.py:395-537`) with
    /// the DryRun gate inserted at the exact `invoice` boundary.
    pub fn execute(&self, req: &ExecuteRequest) -> ExecutionResult {
        let mut result = ExecutionResult {
            success: false,
            attempts: 1,
            fee_sats: 0,
            fee_msat: 0,
            fee_ppm: 0,
            hops: req.route.len() as i64,
            parts: 1,
            error: None,
            amount_sats: req.amount_sats,
            payment_pending: false,
            payment_hash: None,
            excluded_channels: Vec::new(),
            route_type: "native",
            failure_data: json!({ "route_summary": route_summary(&req.route) }),
        };

        let planned_fee_msat = match validate_route(req) {
            Ok(fee) => fee,
            Err((reason, fee_msat)) => {
                let prefix = if reason.starts_with("route_over_budget") {
                    NATIVE_ROUTE_OVER_BUDGET_PREFIX
                } else {
                    NATIVE_ROUTE_INVALID_PREFIX
                };
                result.error = Some(format!("{prefix}{reason}"));
                result.fee_msat = fee_msat;
                result.fee_sats = if fee_msat != 0 {
                    base_to_sats_ceil(fee_msat)
                } else {
                    0
                };
                return result;
            }
        };

        if self.mode == PaymentMode::DryRun {
            // The gate sits exactly where Python issues the `invoice` RPC:
            // validation and pricing above ran identically to Live; ZERO
            // PaymentRpc methods have been called.
            result.error = Some(DRYRUN_GATE_SENDPAY_DISABLED.to_string());
            result.fee_msat = planned_fee_msat;
            result.fee_sats = base_to_sats_ceil(planned_fee_msat);
            return result;
        }

        let label = format!("rebal-native-{}-{}", req.now_ms, req.dest_channel_id);
        let mut payment_hash = String::new();
        let mut payment_attempted = false;

        match self.attempt_payment(req, &label, &mut payment_hash, &mut payment_attempted) {
            Ok(AttemptOutcome { paid }) => {
                let actual_sent_msat = match &paid {
                    Value::Object(obj) => {
                        parse_msat(obj.get("amount_sent_msat").unwrap_or(&Value::Null))
                    }
                    _ => 0,
                };
                let sent = if actual_sent_msat != 0 {
                    actual_sent_msat
                } else {
                    // Python `actual_sent_msat or parse_msat(route[0][...])`:
                    // 0 is falsy, fall back to the first-hop amount.
                    req.route.first().map(|h| h.amount_msat).unwrap_or(0)
                };
                let actual_fee_msat = (sent - req.amount_sats * 1000).max(0);
                result.success = true;
                result.fee_msat = actual_fee_msat;
                result.fee_sats = base_to_sats_ceil(actual_fee_msat);
                if req.amount_sats > 0 {
                    result.fee_ppm = (actual_fee_msat * 1_000_000) / (req.amount_sats * 1000);
                }
                result
            }
            Err(failure) => {
                if is_payment_unresolved(
                    payment_attempted,
                    &failure.raw_message,
                    &failure.error_text,
                    &failure.details,
                ) {
                    // The HTLC may still settle. Do NOT delete the invoice
                    // or the payment, do NOT emit route exclusions, and
                    // surface the planned fee so the engine keeps the
                    // budget held until reconciliation resolves it.
                    result.payment_pending = true;
                    result.error = Some(format!(
                        "{PAYMENT_PENDING_TIMEOUT_PREFIX}{}",
                        failure.error_text
                    ));
                    result.fee_msat = planned_fee_msat;
                    result.fee_sats = base_to_sats_ceil(planned_fee_msat);
                    result.failure_data = json!({
                        "failure_class": "pending",
                        "payment_hash": payment_hash,
                        "invoice_label": label,
                        "route_summary": route_summary(&req.route),
                    });
                    result.payment_hash = Some(payment_hash);
                    return result;
                }

                // Malformed-invoice failures reuse the terminal machinery
                // but keep Python's dedicated error string and untouched
                // failure_data/exclusions (`_fail_malformed_invoice_response`).
                if let Some(reason) = failure.raw_message.strip_prefix(MALFORMED_INVOICE_MARKER) {
                    result.error = Some(format!("{NATIVE_INVOICE_ERROR_PREFIX}{reason}"));
                    let class = failure_class(result.error.as_deref().unwrap_or(""));
                    if let Value::Object(fd) = &mut result.failure_data {
                        fd.insert("failure_class".to_string(), json!(class));
                    }
                    self.cleanup_failed_payment("", &label);
                    return result;
                }

                let mut failure_data = failure.details.clone();
                let class = failure_class(&failure.error_text);
                failure_data.insert("failure_class".to_string(), json!(class));
                failure_data.insert("route_summary".to_string(), route_summary(&req.route));
                result.excluded_channels =
                    exclude_from_failure(&req.route, &failure.details, &failure.error_text);
                result.error = Some(format!(
                    "{NATIVE_SENDPAY_ERROR_PREFIX}{}{}",
                    failure.error_text,
                    compact_detail_suffix(&failure_data)
                ));
                result.failure_data = Value::Object(failure_data);
                self.cleanup_failed_payment(&payment_hash, &label);
                self.record_failure_observations(&result, req);
                result
            }
        }
    }

    /// The Python try-block (`rebalance_native_executor_v2.py:430-491`):
    /// invoice -> sendpay -> waitsendpay. `Err(Failure)` is the raised
    /// exception; a malformed invoice response is signalled via
    /// [`MALFORMED_INVOICE_MARKER`] so the caller can keep NX-4's dedicated
    /// error shape.
    fn attempt_payment(
        &self,
        req: &ExecuteRequest,
        label: &str,
        payment_hash: &mut String,
        payment_attempted: &mut bool,
    ) -> Result<AttemptOutcome, Failure> {
        let invoice = self
            .rpc
            .invoice(req.amount_sats * 1000, label, INVOICE_EXPIRY_SEC)
            .map_err(Failure::from_rpc)?;
        let Value::Object(invoice) = invoice else {
            return Err(Failure::internal(format!(
                "{MALFORMED_INVOICE_MARKER}unexpected response"
            )));
        };
        let hash = invoice
            .get("payment_hash")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string();
        if hash.is_empty() {
            return Err(Failure::internal(format!(
                "{MALFORMED_INVOICE_MARKER}missing payment_hash"
            )));
        }
        *payment_hash = hash.clone();

        // Python includes bolt11/payment_secret only when truthy; the seam
        // passes "" for absent (live impls translate back to omission).
        let truthy_str = |key: &str| -> String {
            invoice
                .get(key)
                .and_then(Value::as_str)
                .unwrap_or("")
                .to_string()
        };
        let bolt11 = truthy_str("bolt11");
        let payment_secret = truthy_str("payment_secret");

        *payment_attempted = true;
        self.rpc
            .sendpay(&req.route, &hash, &bolt11, &payment_secret)
            .map_err(Failure::from_rpc)?;
        let paid = self
            .rpc
            .waitsendpay(&hash, SENDPAY_TIMEOUT_SEC)
            .map_err(Failure::from_rpc)?;
        if let Value::Object(obj) = &paid {
            match obj.get("status") {
                None | Some(Value::Null) => {}
                Some(Value::String(s)) if s == "complete" => {}
                Some(status) => {
                    let text = match status {
                        Value::String(s) => s.clone(),
                        other => other.to_string(),
                    };
                    return Err(Failure::internal(format!("waitsendpay_status={text}")));
                }
            }
        }
        Ok(AttemptOutcome { paid })
    }

    /// `_cleanup_failed_payment` (`rebalance_native_executor_v2.py:383-393`):
    /// best-effort `delpay status=failed` + `delinvoice status=unpaid`,
    /// every error swallowed.
    fn cleanup_failed_payment(&self, payment_hash: &str, label: &str) {
        if !payment_hash.is_empty() {
            let _ = self.rpc.delpay(payment_hash, "failed");
        }
        if !label.is_empty() {
            let _ = self.rpc.delinvoice(label, "unpaid");
        }
    }

    /// `_record_failure_observations`
    /// (`rebalance_native_executor_v2.py:208-275`): confidence-weighted
    /// blame per attribution quality — [`ATTRIBUTED_CONFIDENCE`] when CLN
    /// named channel+direction, both directions at half confidence when
    /// only the channel is named, and the all-middle-hops fallback split
    /// `0.85/n` with the [`INFERRED_CONFIDENCE_FLOOR`].
    fn record_failure_observations(&self, result: &ExecutionResult, req: &ExecuteRequest) {
        if result.success {
            return;
        }
        let fd = match &result.failure_data {
            Value::Object(fd) => fd,
            _ => return,
        };
        let class = fd
            .get("failure_class")
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty())
            .unwrap_or("unknown");
        let attributed_channel = fd
            .get("erring_channel")
            .and_then(Value::as_str)
            .unwrap_or("")
            .trim()
            .to_string();
        let attributed_direction = direction_as_bit(fd.get("erring_direction"));

        let mut targets: Vec<(String, u8, f64)> = Vec::new();
        if !attributed_channel.is_empty() {
            if let Some(direction) = attributed_direction {
                targets.push((attributed_channel, direction, ATTRIBUTED_CONFIDENCE));
            } else {
                // Attributed channel, unknown direction: both directions at
                // half confidence instead of dropping the observation.
                for direction in [0u8, 1u8] {
                    targets.push((
                        attributed_channel.clone(),
                        direction,
                        ATTRIBUTED_CONFIDENCE / 2.0,
                    ));
                }
            }
        } else {
            // Inferred attribution: excluded_channels is the
            // all-middle-hops fallback. Split the evidence across suspects.
            let mut directed: Vec<(String, u8)> = Vec::new();
            for entry in &result.excluded_channels {
                let Some((scid, direction_text)) = entry.split_once('/') else {
                    continue;
                };
                if scid.is_empty() {
                    continue;
                }
                let Ok(direction) = direction_text.parse::<i64>() else {
                    continue;
                };
                // Python int(direction_text) accepts any int; segstore
                // validation later drops non-0/1. The typed record()
                // interface needs u8; out-of-range values cannot occur from
                // exclude_from_failure (u8 direction source).
                let Ok(direction) = u8::try_from(direction) else {
                    continue;
                };
                directed.push((scid.to_string(), direction));
            }
            if directed.is_empty() {
                return;
            }
            let confidence =
                (ATTRIBUTED_CONFIDENCE / directed.len() as f64).max(INFERRED_CONFIDENCE_FLOOR);
            targets = directed
                .into_iter()
                .map(|(scid, direction)| (scid, direction, confidence))
                .collect();
        }

        let observed_at = req.now_ms / 1000;
        for (scid, direction, confidence) in targets {
            self.segstore.record(
                &scid,
                direction,
                req.amount_sats,
                class,
                confidence,
                observed_at,
            );
        }
    }
}

/// Internal sentinel distinguishing NX-4 malformed-invoice failures inside
/// the shared failure plumbing (never surfaces: the caller strips it and
/// emits [`NATIVE_INVOICE_ERROR_PREFIX`]).
const MALFORMED_INVOICE_MARKER: &str = "\u{0}malformed_invoice:";

/// `_validate_route` (`rebalance_native_executor_v2.py:277-332`), over
/// typed hops: `Ok(planned_fee_msat)` or `Err((reason, fee_msat))`. The
/// Python-only `hop_N_not_object` / `hop_N_missing_<field>` branches are
/// unreachable through [`SendpayHop`] (fields always present, typed) and
/// deliberately have no Rust counterpart.
fn validate_route(req: &ExecuteRequest) -> Result<i64, (String, i64)> {
    if req.amount_sats <= 0 {
        return Err(("invalid_amount".to_string(), 0));
    }
    let (Some(first), Some(last)) = (req.route.first(), req.route.last()) else {
        return Err(("missing_route".to_string(), 0));
    };

    if first.channel != req.source_channel_id {
        return Err(("first_hop_not_source_channel".to_string(), 0));
    }
    if last.channel != req.dest_channel_id {
        return Err(("final_hop_not_dest_channel".to_string(), 0));
    }
    if last.id != req.our_id {
        return Err(("final_hop_not_our_node".to_string(), 0));
    }

    let expected_final_msat = req.amount_sats * 1000;
    if last.amount_msat != expected_final_msat {
        return Err(("final_amount_mismatch".to_string(), 0));
    }

    let mut previous_msat: Option<i64> = None;
    for (index, hop) in req.route.iter().enumerate() {
        if hop.amount_msat <= 0 {
            return Err((format!("hop_{index}_invalid_amount"), 0));
        }
        if let Some(prev) = previous_msat {
            if hop.amount_msat > prev {
                return Err(("increasing_route_amount".to_string(), 0));
            }
        }
        previous_msat = Some(hop.amount_msat);
    }

    let fee_msat = (first.amount_msat - expected_final_msat).max(0);
    let max_fee_msat = req.max_fee_sats.max(0) * 1000;
    if fee_msat > max_fee_msat {
        return Err((
            format!(
                "route_over_budget: {} > {}",
                base_to_sats_ceil(fee_msat),
                req.max_fee_sats
            ),
            fee_msat,
        ));
    }
    Ok(fee_msat)
}
