//! Rust port of the Python rebalance stack (cl_revenue_ops v2.18.1, branch
//! `port`, `modules/rebalancer.py` + `rebalance_engine_v2.py` +
//! `rebalance_planner_v2.py` + `rebalance_router_v3.py` +
//! `rebalance_native_executor_v2.py` + `rebalance_modes.py` +
//! `rebalance_route_policy.py` + `segment_observations.py` +
//! `rebalance_execution.py`): planner → router → executor → engine
//! orchestration, ported per
//! `docs/superpowers/plans/2026-07-17-phase5-rebalance.md`.
//!
//! Every module for the whole phase is pre-declared here (Task 1, Wave 0) so
//! that Waves 1-5 — implemented as parallel, isolated tasks/worktrees — never
//! need to touch this file again. Modules land as stub files with doc
//! comments only until their owning task replaces them.
//!
//! Parity discipline (Global Constraints): every pure function is proven
//! against committed JSON fixtures under `fixtures/rebalance/`, generated by
//! `tools/port/gen_rebalance_fixtures.py` (port repo) running the real
//! Python modules. Error strings are contracts, centralized once in
//! [`errors`] and never retyped inline.
#![forbid(unsafe_code)]

pub mod cooldowns;
pub mod defib;
pub mod engine;
pub mod errors;
pub mod ev;
pub mod executor;
pub mod facade;
pub mod modes;
pub mod planner;
pub mod route_policy;
pub mod router;
pub mod segstore;
pub mod types;
