//! Askrene router v3: `getroutes` pricing, throwaway exclude layers, orphan
//! sweep — port of `modules/rebalance_router_v3.py` plus the surviving
//! fee/CLTV policy helpers from `modules/rebalance_router_v2.py` and the
//! engine's `_sweep_orphan_exclude_layers`
//! (`modules/rebalance_engine_v2.py:293-330`).
//!
//! Golden parity: `fixtures/rebalance/router.json`, generated by
//! `tools/port/gen_rebalance_fixtures.py router` (port repo, branch
//! `phase5-t4-gen`) driving the REAL Python `RebalanceRouterV3` over a
//! scripted plugin/rpc stub.
//!
//! Production contracts carried by this module (ledgered incidents):
//!
//! - **No `maxdelay` is ever passed to `getroutes`** — [`GetRoutesRequest`]
//!   simply has no such field, so askrene's default (2016) governs. Passing
//!   a tight maxdelay silently starved long-CLTV routes (the Tallship
//!   lesson); the fixture pins the exact param-key set.
//! - **45s per-call timeout** ([`GETROUTES_RPC_TIMEOUT_SECONDS`]) vs the
//!   15s global RPC ceiling: askrene's MCF runtime grows with amount and
//!   graph size (measured on lnnode: ~6-8s at 500k sats, ~16s at 2M sats on
//!   a 153MB gossip store), so every large-pair pricing deterministically
//!   timed out at 15s. The live RPC impl must extend the proxy ceiling for
//!   exactly this call (`rebalance_router_v3.py:46-52`).
//! - **Throwaway exclude layers** are named `rebalance-exclude-{ts}-{n}`
//!   with `n` from a process-global [`AtomicU64`] — Python uses
//!   `itertools.count` because two workers minting the same name leads to
//!   one removing the other's LIVE layer (`rebalance_router_v3.py:604-609`).
//!   Orphans from crashed processes are removed at startup by
//!   [`sweep_orphan_exclude_layers`].
//! - **`"Unknown layer"` getroutes errors invalidate the cycle caches**
//!   (listlayers probe cache AND cached exclude layers, which are removed
//!   best-effort so dropping the references never leaks live layers) —
//!   `rebalance_router_v3.py:264-274,468-475`.
//! - The middle `getroutes` query is `source_peer -> dest_peer` for
//!   `amount + final_hop_fee`, with the local source/dest SCIDs (plus any
//!   retry exclusions) disabled via the throwaway layer so askrene cannot
//!   pick the degenerate `source_peer -> us -> dest_peer` path
//!   (`rebalance_router_v3.py:394-403`); the returned path is still
//!   validated to never loop through our node.
//!
//! Port deviations (documented, deliberate):
//!
//! - `invoice_final_cltv` (Python `_get_invoice_final_cltv`, a
//!   `listconfigs` `cltv-final` lookup cached for the process lifetime)
//!   arrives via [`PlannedPairCtx`] — the frozen [`RouterRpc`] seam has no
//!   `listconfigs` method; the engine wires the value at init (Python
//!   default: 18).
//! - The v2 final-hop gossip fallback queries `listchannels source=<peer>`;
//!   the frozen seam exposes only [`RouterRpc::listchannels_scid`], so the
//!   fallback queries the dest channel's SCID and filters
//!   `source == dest_peer && destination == our_node` — the same edge,
//!   pinned to the exact dest channel (strictly more precise with parallel
//!   channels).
//! - Python's `price_pair` outside a cycle uses per-call create/remove
//!   layer semantics; the Rust [`CycleRouter`] is always cycle-scoped
//!   (construct one per retry for the ephemeral behavior — `end_cycle`, or
//!   simply dropping it, tears the layers down).

use serde::Serialize;
use serde_json::Value;
use std::collections::{BTreeSet, HashMap};
use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::errors::NO_ROUTE;

/// Per-call RPC ceiling for `getroutes` (`rebalance_router_v3.py:52`).
pub const GETROUTES_RPC_TIMEOUT_SECONDS: u64 = 45;

/// Throwaway exclude-layer name prefix (`rebalance_router_v3.py:609`,
/// swept at startup per `rebalance_engine_v2.py:312`).
pub const EXCLUDE_LAYER_PREFIX: &str = "rebalance-exclude-";

/// Always appended to the `getroutes` layer list
/// (`rebalance_router_v3.py:392-393`).
pub const AUTO_NO_MPP_LAYER: &str = "auto.no_mpp_support";

/// Operator-config default for askrene layers (`rebalance_router_v3.py:45`).
pub const DEFAULT_ASKRENE_LAYERS: &str = "standalone";

/// Skip reasons produced by [`translate_getroutes_error`] — EXACT tokens
/// from `rebalance_router_v3.py:88-110` (`_translate_getroutes_error`).
pub const REASON_UNKNOWN_SOURCE_NODE: &str = "unknown_source_node";
/// See [`REASON_UNKNOWN_SOURCE_NODE`].
pub const REASON_UNKNOWN_DEST_NODE: &str = "unknown_dest_node";
/// See [`REASON_UNKNOWN_SOURCE_NODE`].
pub const REASON_UNKNOWN_LAYER: &str = "unknown_layer";
/// See [`REASON_UNKNOWN_SOURCE_NODE`].
pub const REASON_ASKRENE_CHILD_DIED: &str = "askrene_child_died";
/// Middle-path validation failure token (`rebalance_router_v3.py:154-159`).
pub const REASON_PATH_LOOPS_THROUGH_US: &str = "path_loops_through_us";

/// Sentinel config values meaning "run with no configured layers"
/// (`rebalance_router_v3.py:53-60`).
const STANDALONE_SENTINELS: [&str; 6] = ["none", "off", "disabled", "standalone", "false", "0"];

/// `min()` sentinel for routes with an empty path
/// (`rebalance_router_v3.py:588-595`, `_route_fee_msat`).
const EMPTY_PATH_FEE_SENTINEL: i64 = 1_000_000_000_000_000_000; // 10^18

/// Monotonic counter for exclude-layer names; process-global so concurrent
/// workers can never mint duplicates (Python: class-level
/// `itertools.count(1)`, atomic under the GIL).
static EXCLUDE_COUNTER: AtomicU64 = AtomicU64::new(1);

/// An RPC-level failure surfaced by a [`RouterRpc`] implementation. The
/// message text is what [`translate_getroutes_error`] substring-matches, so
/// live impls must preserve CLN's error text verbatim (Python's `str(e)`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RpcFailure {
    pub message: String,
}

impl fmt::Display for RpcFailure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for RpcFailure {}

/// The exact `getroutes` payload (`rebalance_router_v3.py:452-459`):
/// six params, `maxfee_msat == amount_msat`, and deliberately NO `maxdelay`
/// (askrene's default 2016 governs — see the module docs).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct GetRoutesRequest {
    pub source: String,
    pub destination: String,
    pub amount_msat: i64,
    pub layers: Vec<String>,
    pub maxfee_msat: i64,
    pub final_cltv: i64,
}

/// Narrow RPC seam — fixtures/tests script it; the live impl lands with
/// plugin wiring. `getroutes` carries the 45s timeout contract
/// ([`GETROUTES_RPC_TIMEOUT_SECONDS`]).
pub trait RouterRpc {
    fn getroutes(&self, req: &GetRoutesRequest) -> Result<Value, RpcFailure>;
    fn askrene_create_layer(&self, name: &str) -> Result<(), RpcFailure>;
    fn askrene_update_channel(
        &self,
        layer: &str,
        scid_dir: &str,
        enabled: bool,
    ) -> Result<(), RpcFailure>;
    fn askrene_remove_layer(&self, name: &str) -> Result<(), RpcFailure>;
    fn askrene_listlayers(&self) -> Result<Value, RpcFailure>;
    fn listpeerchannels(&self, peer_id: &str) -> Result<Value, RpcFailure>;
    /// v2 gossip fallback: `listchannels short_channel_id=<scid>`.
    fn listchannels_scid(&self, scid: &str) -> Result<Value, RpcFailure>;
}

/// One sendpay-format route hop (`_translate_getroutes_hop_to_sendpay`,
/// `rebalance_router_v3.py:113-129`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SendpayHop {
    pub id: String,
    pub channel: String,
    pub direction: u8,
    pub delay: u32,
    pub amount_msat: i64,
    pub style: &'static str, // always "tlv"
}

/// Result of a `price_pair` attempt, shape shared with the v2 router so the
/// engine consumes either transparently (`rebalance_router_v2.py:19-36`).
/// Python's `error: str = ""` maps to `None` here.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RouteResult {
    pub success: bool,
    pub error: Option<String>,
    pub route_cost_sats: i64,
    pub final_hop_fee_ppm: i64,
    pub hops: i64,
    pub route: Vec<SendpayHop>,
    /// askrene's per-route success-probability estimate; 0 when absent
    /// (older CLN / partial mock) — the engine treats 0 as "no
    /// probability-aware relaxation", identical to the v2 router.
    pub probability_ppm: i64,
}

impl RouteResult {
    fn fail(error: impl Into<String>) -> Self {
        RouteResult {
            success: false,
            error: Some(error.into()),
            ..RouteResult::default()
        }
    }
}

/// Everything one pricing call needs. Mirrors the Python `price_pair`
/// signature plus the router-instance state (`our_node_id`, configured
/// `layer_names`) and the process-static `invoice_final_cltv` (see the
/// module docs on the `listconfigs` deviation; Python default 18).
/// `our_node_id` must be non-empty — Python's getinfo self-heal
/// (`rebalance_router_v3.py:346-359`) lives with the engine wiring.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlannedPairCtx {
    pub our_node_id: String,
    pub source_channel_id: String,
    pub dest_channel_id: String,
    pub source_peer_id: String,
    pub dest_peer_id: String,
    pub amount_sats: i64,
    /// Configured askrene layers (post [`configured_layer_names`]); probed
    /// against live layers each call, missing names silently dropped.
    pub layer_names: Vec<String>,
    /// The node's `cltv-final` config value.
    pub invoice_final_cltv: i64,
}

// ---------------------------------------------------------------------------
// Module-level helpers
// ---------------------------------------------------------------------------

/// Port of `_parse_layer_names` (`rebalance_router_v3.py:33-42`).
fn parse_layer_names(csv: &str) -> Vec<String> {
    csv.split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .collect()
}

/// Port of `_configured_layer_names` (`rebalance_router_v3.py:61-73`):
/// blank config means "use the safe default"; the standalone sentinels run
/// with no configured layers.
pub fn configured_layer_names(raw: Option<&str>) -> Vec<String> {
    let text = raw.unwrap_or("").trim();
    let text = if text.is_empty() {
        DEFAULT_ASKRENE_LAYERS
    } else {
        text
    };
    if STANDALONE_SENTINELS.contains(&text.to_lowercase().as_str()) {
        return Vec::new();
    }
    parse_layer_names(text)
}

/// Port of `_translate_getroutes_error` (`rebalance_router_v3.py:88-110`):
/// EXACT substrings, sourced from `plugins/askrene/askrene.c` and
/// `explain_failure.c` at ElementsProject/lightning@b57edd21. Unknown
/// messages fall back to [`NO_ROUTE`]; callers preserve the original text
/// as detail (`"{reason}: {detail}"`).
pub fn translate_getroutes_error(error: &str) -> &'static str {
    if error.contains("Unknown source node") {
        return REASON_UNKNOWN_SOURCE_NODE;
    }
    if error.contains("Unknown destination node") {
        return REASON_UNKNOWN_DEST_NODE;
    }
    if error.contains("Unknown layer") {
        return REASON_UNKNOWN_LAYER;
    }
    const CHILD_SIGNALS: [&str; 4] = [
        "child died with signal",
        "failed to fork",
        "child produced no output",
        "failed to create pipes",
    ];
    if CHILD_SIGNALS.iter().any(|s| error.contains(s)) {
        return REASON_ASKRENE_CHILD_DIED;
    }
    NO_ROUTE
}

/// Startup sweep: remove leftover `rebalance-exclude-*` layers from
/// previous crashed cycles (`rebalance_engine_v2.py:293-330`). Returns the
/// orphan count (removal failures are still counted, matching Python — the
/// count is for logging only); a failed `listlayers` returns 0.
pub fn sweep_orphan_exclude_layers(rpc: &dyn RouterRpc) -> usize {
    let result = match rpc.askrene_listlayers() {
        Ok(v) => v,
        Err(_) => return 0,
    };
    let orphans: Vec<String> = result["layers"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|l| l["layer"].as_str())
        .filter(|name| name.starts_with(EXCLUDE_LAYER_PREFIX))
        .map(str::to_string)
        .collect();
    for name in &orphans {
        let _ = rpc.askrene_remove_layer(name); // best-effort
    }
    orphans.len()
}

/// Parse an `amount_msat` field that may be an integer, a `"Nmsat"`
/// string, or null (`_parse_msat`, `rebalance_router_v3.py:76-85`).
fn parse_msat(v: &Value) -> Result<i64, String> {
    match v {
        Value::Null => Ok(0),
        Value::Number(n) => n
            .as_i64()
            .ok_or_else(|| format!("cannot parse amount_msat: {v}")),
        Value::String(s) => {
            let trimmed = s.trim_end_matches(['m', 's', 'a', 't']).trim();
            if trimmed.is_empty() {
                Ok(0)
            } else {
                trimmed
                    .parse()
                    .map_err(|_| format!("cannot parse amount_msat: {v}"))
            }
        }
        _ => Err(format!("cannot parse amount_msat: {v}")),
    }
}

/// Lenient `int(x or 0)` for policy fields (missing/null/unparseable -> 0).
fn int_or_zero(v: Option<&Value>) -> i64 {
    match v {
        None | Some(Value::Null) => 0,
        Some(Value::Number(n)) => n.as_i64().unwrap_or(0),
        Some(Value::String(s)) => s.trim().parse().unwrap_or(0),
        Some(_) => 0,
    }
}

/// Integer-exact `math.ceil(a / b)` for non-negative `a`, positive `b`
/// (Global Constraints: ceil idioms ported as checked integer math).
fn ceil_div(a: i64, b: i64) -> i64 {
    debug_assert!(a >= 0 && b > 0);
    (a + b - 1) / b
}

/// CLN's channel direction bit for a traversed edge
/// (`rebalance_router_v2.py:367-370`).
fn channel_direction(start_node_id: &str, end_node_id: &str) -> u8 {
    u8::from(start_node_id > end_node_id)
}

/// Fee in sats for the final hop (`_compute_final_hop_fee_sats`,
/// `rebalance_router_v2.py:183-193`): both base and proportional policy —
/// omitting the base fee fails low-amount routes with WIRE_FEE_INSUFFICIENT.
fn compute_final_hop_fee_sats(amount_sats: i64, fee_ppm: i64, fee_base_msat: i64) -> i64 {
    let fee_msat = fee_base_msat + ceil_div(amount_sats * 1000 * fee_ppm, 1_000_000);
    ceil_div(fee_msat, 1000)
}

/// Convert a getroutes path hop to sendpay format
/// (`_translate_getroutes_hop_to_sendpay`, `rebalance_router_v3.py:113-129`):
/// `short_channel_id_dir` ("SCID/dir") + `next_node_id` becomes
/// `channel` + `direction` + `id`.
fn translate_hop_to_sendpay(hop: &Value) -> Result<SendpayHop, String> {
    let scidd = hop["short_channel_id_dir"]
        .as_str()
        .ok_or("getroutes hop missing short_channel_id_dir")?;
    let (scid, direction) = scidd
        .rsplit_once('/')
        .ok_or_else(|| format!("malformed short_channel_id_dir: {scidd}"))?;
    let direction: u8 = direction
        .parse()
        .map_err(|_| format!("malformed direction in {scidd}"))?;
    let id = hop["next_node_id"]
        .as_str()
        .ok_or("getroutes hop missing next_node_id")?
        .to_string();
    let amount_msat = parse_msat(&hop["amount_msat"])?;
    let delay = hop["delay"]
        .as_i64()
        .and_then(|d| u32::try_from(d).ok())
        .ok_or("getroutes hop missing delay")?;
    Ok(SendpayHop {
        id,
        channel: scid.to_string(),
        direction,
        delay,
        amount_msat,
        style: "tlv",
    })
}

/// Validate the middle path is a clean `peer_A -> peer_B` path
/// (`_validate_getroutes_middle_path`, `rebalance_router_v3.py:132-160`):
/// non-empty, terminates at the dest peer, never routes through us (a
/// degenerate loop). All three failures share one reason token.
fn validate_middle_path(path: &[Value], our_node_id: &str, dest_peer_id: &str) -> bool {
    let Some(last) = path.last() else {
        return false;
    };
    if last["next_node_id"].as_str() != Some(dest_peer_id) {
        return false;
    }
    !path
        .iter()
        .any(|hop| hop["next_node_id"].as_str() == Some(our_node_id))
}

/// `min()` key for cheapest-route selection (`_route_fee_msat`,
/// `rebalance_router_v3.py:588-595`): first-hop amount minus delivered
/// amount; empty paths get a huge sentinel.
fn route_fee_msat(route: &Value) -> Result<i64, String> {
    let path = route["path"].as_array().map(Vec::as_slice).unwrap_or(&[]);
    let Some(first) = path.first() else {
        return Ok(EMPTY_PATH_FEE_SENTINEL);
    };
    let first_amt = parse_msat(&first["amount_msat"])?;
    let delivered = parse_msat(route.get("amount_msat").unwrap_or(&Value::Null))?;
    Ok((first_amt - delivered).max(0))
}

// ---------------------------------------------------------------------------
// v2 policy-lookup helpers (`rebalance_router_v2.py`, surviving subset)
// ---------------------------------------------------------------------------

struct ChannelPolicy {
    fee_ppm: i64,
    fee_base_msat: i64,
    cltv_delta: i64,
}

/// `_channel_matches_scid` (`rebalance_router_v2.py:81-95`): with parallel
/// channels to one peer, policy must be read from the specific channel.
fn channel_matches_scid(ch: &Value, dest_channel_id: &str) -> bool {
    if dest_channel_id.is_empty() {
        return true;
    }
    if ch["short_channel_id"].as_str() == Some(dest_channel_id) {
        return true;
    }
    ch["alias"]["local"].as_str() == Some(dest_channel_id)
}

/// `_get_final_hop_policy` (`rebalance_router_v2.py:127-181`): the actual
/// inbound policy the dest peer charges us. Priority 1 is
/// `listpeerchannels` `updates.remote`; priority 2 the gossip fallback
/// (via the dest channel's SCID — see the module docs).
fn get_final_hop_policy(
    rpc: &dyn RouterRpc,
    our_node_id: &str,
    dest_peer_id: &str,
    dest_channel_id: &str,
) -> Option<ChannelPolicy> {
    if let Ok(result) = rpc.listpeerchannels(dest_peer_id) {
        for ch in result["channels"].as_array().into_iter().flatten() {
            if ch["peer_id"].as_str() != Some(dest_peer_id) {
                continue;
            }
            if !channel_matches_scid(ch, dest_channel_id) {
                continue;
            }
            let remote = &ch["updates"]["remote"];
            if remote.is_null() {
                continue;
            }
            if let Some(fee_ppm) = remote["fee_proportional_millionths"].as_i64() {
                return Some(ChannelPolicy {
                    fee_ppm,
                    fee_base_msat: int_or_zero(remote.get("fee_base_msat")),
                    cltv_delta: int_or_zero(remote.get("cltv_expiry_delta")),
                });
            }
        }
    }

    if !dest_channel_id.is_empty() {
        if let Ok(result) = rpc.listchannels_scid(dest_channel_id) {
            for ch in result["channels"].as_array().into_iter().flatten() {
                if ch["source"].as_str() != Some(dest_peer_id)
                    || ch["destination"].as_str() != Some(our_node_id)
                {
                    continue;
                }
                if let Some(fee_ppm) = ch["fee_per_millionth"].as_i64() {
                    // Python: ch.get("base_fee_millisatoshi",
                    //                 ch.get("fee_base_msat", 0)) — key
                    // presence decides which field is read.
                    let base = if ch.get("base_fee_millisatoshi").is_some() {
                        int_or_zero(ch.get("base_fee_millisatoshi"))
                    } else {
                        int_or_zero(ch.get("fee_base_msat"))
                    };
                    return Some(ChannelPolicy {
                        fee_ppm,
                        fee_base_msat: base,
                        cltv_delta: int_or_zero(ch.get("delay")),
                    });
                }
            }
        }
    }

    None
}

/// `_get_dest_channel_cltv` (`rebalance_router_v2.py:319-338`): the dest
/// peer's `cltv_expiry_delta` for the final hop; safe default 40.
fn get_dest_channel_cltv(rpc: &dyn RouterRpc, dest_peer_id: &str, dest_channel_id: &str) -> i64 {
    if let Ok(result) = rpc.listpeerchannels(dest_peer_id) {
        for ch in result["channels"].as_array().into_iter().flatten() {
            if !channel_matches_scid(ch, dest_channel_id) {
                continue;
            }
            if let Some(cltv) = ch["updates"]["remote"]["cltv_expiry_delta"].as_i64() {
                return cltv;
            }
        }
    }
    40
}

/// `_get_forwarding_policy` (`rebalance_router_v2.py:211-250`): a node's
/// forwarding policy for a concrete outgoing hop, from gossip.
fn get_forwarding_policy(
    rpc: &dyn RouterRpc,
    source_node_id: &str,
    channel_id: &str,
    next_node_id: &str,
) -> Option<ChannelPolicy> {
    if channel_id.is_empty() || next_node_id.is_empty() {
        return None;
    }
    let result = rpc.listchannels_scid(channel_id).ok()?;
    for ch in result["channels"].as_array().into_iter().flatten() {
        if ch["short_channel_id"].as_str() != Some(channel_id)
            || ch["source"].as_str() != Some(source_node_id)
            || ch["destination"].as_str() != Some(next_node_id)
        {
            continue;
        }
        let (Some(fee_ppm), Some(delay)) = (ch["fee_per_millionth"].as_i64(), ch["delay"].as_i64())
        else {
            continue;
        };
        // Python reads this one via _parse_msat_value ("Nmsat" tolerated).
        let base = parse_msat(ch.get("base_fee_millisatoshi").unwrap_or(&Value::Null)).ok()?;
        return Some(ChannelPolicy {
            fee_ppm,
            fee_base_msat: base,
            cltv_delta: delay,
        });
    }
    None
}

/// `_reprice_middle_route_amounts` (`rebalance_router_v2.py:260-294`):
/// recompute middle hop amounts from live policies (router amount fields
/// can lag gossip). A hop amount is what that hop's destination receives,
/// so each non-final hop adds its destination's forwarding fee for the
/// next edge; a missing policy keeps the router's amount.
fn reprice_middle_route_amounts(
    rpc: &dyn RouterRpc,
    hops: &mut [SendpayHop],
    final_amount_msat: i64,
) {
    let Some(last) = hops.last_mut() else {
        return;
    };
    last.amount_msat = final_amount_msat;
    for index in (0..hops.len() - 1).rev() {
        let outgoing = &hops[index + 1];
        let Some(policy) =
            get_forwarding_policy(rpc, &hops[index].id, &outgoing.channel, &outgoing.id)
        else {
            continue; // keep router amount
        };
        let downstream_msat = outgoing.amount_msat;
        let forwarding_fee_msat =
            policy.fee_base_msat + ceil_div(downstream_msat * policy.fee_ppm, 1_000_000);
        hops[index].amount_msat = downstream_msat + forwarding_fee_msat;
    }
}

// ---------------------------------------------------------------------------
// Exclude-layer lifecycle
// ---------------------------------------------------------------------------

fn mint_exclude_layer_name() -> String {
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let n = EXCLUDE_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("{EXCLUDE_LAYER_PREFIX}{ts}-{n}")
}

/// `_build_exclude_layer` (`rebalance_router_v3.py:597-660`): create a
/// throwaway layer disabling the given channels. Directional `"scid/dir"`
/// entries (PR #82) disable only that direction; bare SCIDs disable both.
/// On partial failure the half-built layer is removed (best-effort) before
/// the error propagates, so no caller ever leaks a live layer.
fn build_exclude_layer(rpc: &dyn RouterRpc, entries: &[String]) -> Result<String, RpcFailure> {
    let layer_name = mint_exclude_layer_name();
    let build = || -> Result<(), RpcFailure> {
        rpc.askrene_create_layer(&layer_name)?;
        for entry in entries {
            if entry.contains('/') {
                rpc.askrene_update_channel(&layer_name, entry, false)?;
            } else {
                for direction in 0..2 {
                    rpc.askrene_update_channel(
                        &layer_name,
                        &format!("{entry}/{direction}"),
                        false,
                    )?;
                }
            }
        }
        Ok(())
    };
    if let Err(e) = build() {
        let _ = rpc.askrene_remove_layer(&layer_name); // best-effort rollback
        return Err(e);
    }
    Ok(layer_name)
}

// ---------------------------------------------------------------------------
// CycleRouter
// ---------------------------------------------------------------------------

/// One pricing cycle over askrene `getroutes`. The cycle-scoped caches
/// live HERE, not in globals — Python keeps them thread-local for exactly
/// this isolation (`rebalance_router_v3.py:200-206`): a manual pricing on
/// another thread can never serve or clobber this cycle's cache.
///
/// Within a cycle the live-layer probe is served from one
/// `askrene-listlayers` call, and identical exclude sets share ONE
/// throwaway layer (keyed by set) instead of paying create + updates +
/// remove per pricing call. Both caches are invalidated on `"Unknown
/// layer"` getroutes errors. Dropping the router (or calling
/// [`CycleRouter::end_cycle`]) tears down every cached layer best-effort.
pub struct CycleRouter<'a> {
    rpc: &'a dyn RouterRpc,
    live_layer_names: Option<Vec<String>>,
    exclude_layers: HashMap<BTreeSet<String>, String>,
}

impl<'a> CycleRouter<'a> {
    /// Enter a pricing cycle (`begin_cycle`, `rebalance_router_v3.py:221-239`).
    pub fn begin_cycle(rpc: &'a dyn RouterRpc) -> Self {
        CycleRouter {
            rpc,
            live_layer_names: None,
            exclude_layers: HashMap::new(),
        }
    }

    /// Leave the cycle, tearing down every cached throwaway layer
    /// (`end_cycle`, `rebalance_router_v3.py:241-244`). Plain [`Drop`] does
    /// the same, so a panic-unwind cannot leak live layers.
    pub fn end_cycle(self) {}

    /// Drop the cycle's cached layer state so the next call re-fetches
    /// (`invalidate_layer_cache`, `rebalance_router_v3.py:264-274`): an
    /// `"Unknown layer"` error means some layer in the last getroutes call
    /// no longer exists, and a cached exclude layer may be the casualty —
    /// cached layers are removed (best-effort) so dropping the references
    /// never leaks live askrene layers.
    pub fn invalidate_layer_cache(&mut self) {
        self.live_layer_names = None;
        self.teardown_exclude_layers();
    }

    fn teardown_exclude_layers(&mut self) {
        let layers: Vec<String> = self.exclude_layers.drain().map(|(_, name)| name).collect();
        for layer_name in layers {
            let _ = self.rpc.askrene_remove_layer(&layer_name); // best-effort
        }
    }

    /// Live askrene layer names, cached for the cycle
    /// (`_live_layer_names`, `rebalance_router_v3.py:276-289`); the
    /// requested-vs-live intersection is `_probe_layers`
    /// (`rebalance_router_v3.py:295-324` — a probe failure yields `[]`,
    /// never a hard error: askrene drops unknown layer names silently).
    fn probe_layers(&mut self, requested: &[String]) -> Vec<String> {
        let live: &[String] = if let Some(cached) = &self.live_layer_names {
            cached
        } else {
            let Ok(result) = self.rpc.askrene_listlayers() else {
                return Vec::new();
            };
            let names: Vec<String> = result["layers"]
                .as_array()
                .into_iter()
                .flatten()
                .map(|l| l["layer"].as_str().unwrap_or("").to_string())
                .collect();
            self.live_layer_names = Some(names);
            self.live_layer_names.as_ref().expect("just set")
        };
        requested
            .iter()
            .filter(|name| live.contains(name))
            .cloned()
            .collect()
    }

    /// Get-or-create the throwaway layer for an exclude set
    /// (`_exclude_layer`, `rebalance_router_v3.py:675-711`, cycle-active
    /// branch: identical sets share one cached layer until `end_cycle` or
    /// an unknown-layer invalidation).
    fn exclude_layer(&mut self, entries: &[String]) -> Result<String, RpcFailure> {
        let key: BTreeSet<String> = entries.iter().cloned().collect();
        if let Some(cached) = self.exclude_layers.get(&key) {
            return Ok(cached.clone());
        }
        let layer_name = build_exclude_layer(self.rpc, entries)?;
        self.exclude_layers.insert(key, layer_name.clone());
        Ok(layer_name)
    }

    /// Discover and price a circular rebalance route via askrene
    /// `getroutes` (`price_pair`, `rebalance_router_v3.py:330-434`).
    ///
    /// `exclude` carries retry exclusions (directional `"scid/dir"` or bare
    /// SCIDs); the local source/dest SCIDs are ALWAYS added on top so the
    /// middle search cannot route through our own endpoints
    /// (`rebalance_router_v3.py:394-403`).
    pub fn price_pair(&mut self, pair: &PlannedPairCtx, exclude: &[String]) -> RouteResult {
        let rpc = self.rpc;

        let Some(final_hop_policy) = get_final_hop_policy(
            rpc,
            &pair.our_node_id,
            &pair.dest_peer_id,
            &pair.dest_channel_id,
        ) else {
            return RouteResult::fail(format!(
                "cannot determine final-hop fee for peer {}",
                pair.dest_peer_id
            ));
        };
        let final_hop_fee_ppm = final_hop_policy.fee_ppm;
        let final_hop_fee_base_msat = final_hop_policy.fee_base_msat;
        // The policy lookup already returned the dest peer's cltv_delta;
        // only fall back when it did not carry a usable delta
        // (`rebalance_router_v3.py:371-379`).
        let mut dest_cltv = final_hop_policy.cltv_delta;
        if dest_cltv <= 0 {
            dest_cltv = get_dest_channel_cltv(rpc, &pair.dest_peer_id, &pair.dest_channel_id);
        }
        let required_final_cltv = dest_cltv + pair.invoice_final_cltv;
        let final_hop_fee_sats = compute_final_hop_fee_sats(
            pair.amount_sats,
            final_hop_fee_ppm,
            final_hop_fee_base_msat,
        );
        let route_amount_msat = (pair.amount_sats + final_hop_fee_sats) * 1000;

        // Re-probe live layers each call (cycle-cached) so layers created
        // after startup are picked up; always append auto.no_mpp_support.
        let mut layers = self.probe_layers(&pair.layer_names);
        if !layers.iter().any(|l| l == AUTO_NO_MPP_LAYER) {
            layers.push(AUTO_NO_MPP_LAYER.to_string());
        }

        // Always exclude the local endpoint SCIDs from the middle search,
        // plus any failure exclusions passed by retry logic.
        let mut middle_excludes: Vec<String> = exclude.to_vec();
        for local_scid in [&pair.source_channel_id, &pair.dest_channel_id] {
            if !local_scid.is_empty() && !middle_excludes.iter().any(|e| e == local_scid) {
                middle_excludes.push(local_scid.clone());
            }
        }
        if !middle_excludes.is_empty() {
            match self.exclude_layer(&middle_excludes) {
                Ok(layer_name) => layers.push(layer_name),
                // Python raises out of price_pair here; the engine wraps it
                // as `route_pricing_failed: {e}` (T7). Surface the message.
                Err(e) => return RouteResult::fail(e.message),
            }
        }

        self.price_pair_inner(
            pair,
            route_amount_msat,
            final_hop_fee_ppm,
            final_hop_fee_base_msat,
            required_final_cltv,
            layers,
        )
    }

    /// `_price_pair_inner` (`rebalance_router_v3.py:436-586`).
    fn price_pair_inner(
        &mut self,
        pair: &PlannedPairCtx,
        route_amount_msat: i64,
        final_hop_fee_ppm: i64,
        final_hop_fee_base_msat: i64,
        required_final_cltv: i64,
        layers: Vec<String>,
    ) -> RouteResult {
        let rpc = self.rpc;
        let request = GetRoutesRequest {
            source: pair.source_peer_id.clone(),
            destination: pair.dest_peer_id.clone(),
            amount_msat: route_amount_msat,
            layers,
            maxfee_msat: route_amount_msat,
            final_cltv: required_final_cltv,
        };
        let result = match rpc.getroutes(&request) {
            Ok(v) => v,
            Err(e) => {
                let reason = translate_getroutes_error(&e.message);
                if reason == REASON_UNKNOWN_LAYER {
                    // A cached layer list referenced a layer that no longer
                    // exists; drop the cycle cache so the next pricing call
                    // re-probes instead of failing the whole cycle.
                    self.invalidate_layer_cache();
                }
                return RouteResult::fail(format!("{reason}: {}", e.message));
            }
        };

        let routes = match result.get("routes") {
            Some(Value::Array(routes)) if !routes.is_empty() => routes,
            _ => return RouteResult::fail(format!("{NO_ROUTE}: getroutes returned empty")),
        };

        // Cheapest = min by (first-hop amount - delivered); Python's min()
        // keeps the first minimum on ties.
        let mut cheapest: Option<(&Value, i64)> = None;
        for route in routes {
            let fee = match route_fee_msat(route) {
                Ok(fee) => fee,
                Err(msg) => return RouteResult::fail(msg),
            };
            if cheapest.is_none() || fee < cheapest.expect("some").1 {
                cheapest = Some((route, fee));
            }
        }
        let cheapest = cheapest.expect("routes non-empty").0;
        let empty = Vec::new();
        let middle_path = cheapest["path"].as_array().unwrap_or(&empty);

        if !validate_middle_path(middle_path, &pair.our_node_id, &pair.dest_peer_id) {
            return RouteResult::fail(format!(
                "{REASON_PATH_LOOPS_THROUGH_US}: middle path invalid"
            ));
        }

        let mut middle_sendpay = Vec::with_capacity(middle_path.len());
        for hop in middle_path {
            match translate_hop_to_sendpay(hop) {
                Ok(h) => middle_sendpay.push(h),
                Err(msg) => return RouteResult::fail(msg),
            }
        }
        reprice_middle_route_amounts(rpc, &mut middle_sendpay, route_amount_msat);

        // Wrap the middle path with our own first and last hops to produce
        // a full circular sendpay route: us -> peer_A -> ... -> peer_B -> us.
        let final_hop_fee_sats = compute_final_hop_fee_sats(
            pair.amount_sats,
            final_hop_fee_ppm,
            final_hop_fee_base_msat,
        );
        let (total_forward_msat, first_hop_delay) =
            if let Some(first_middle_hop) = middle_sendpay.first() {
                let Some(policy) = get_forwarding_policy(
                    rpc,
                    &pair.source_peer_id,
                    &first_middle_hop.channel,
                    &first_middle_hop.id,
                ) else {
                    return RouteResult::fail(format!(
                        "cannot determine source peer forwarding policy for {}",
                        first_middle_hop.channel
                    ));
                };
                let middle_forward_msat = first_middle_hop.amount_msat;
                let first_middle_fee_msat = policy.fee_base_msat
                    + ceil_div(middle_forward_msat * policy.fee_ppm, 1_000_000);
                (
                    middle_forward_msat + first_middle_fee_msat,
                    i64::from(first_middle_hop.delay) + policy.cltv_delta,
                )
            } else {
                // Unreachable after validation (empty paths are rejected),
                // kept for structural parity with Python's else-branch.
                (
                    (pair.amount_sats + final_hop_fee_sats) * 1000,
                    required_final_cltv,
                )
            };

        let first_hop = SendpayHop {
            id: pair.source_peer_id.clone(),
            channel: pair.source_channel_id.clone(),
            direction: channel_direction(&pair.our_node_id, &pair.source_peer_id),
            delay: u32::try_from(first_hop_delay).unwrap_or(u32::MAX),
            amount_msat: total_forward_msat,
            style: "tlv",
        };
        let final_hop = SendpayHop {
            id: pair.our_node_id.clone(),
            channel: pair.dest_channel_id.clone(),
            direction: channel_direction(&pair.dest_peer_id, &pair.our_node_id),
            delay: u32::try_from(pair.invoice_final_cltv).unwrap_or(u32::MAX),
            amount_msat: pair.amount_sats * 1000,
            style: "tlv",
        };

        let mut full_route = Vec::with_capacity(middle_sendpay.len() + 2);
        full_route.push(first_hop);
        full_route.append(&mut middle_sendpay);
        full_route.push(final_hop);

        let overpay_msat = total_forward_msat - pair.amount_sats * 1000;
        let total_cost_sats = if overpay_msat <= 0 {
            0
        } else {
            ceil_div(overpay_msat, 1000)
        };

        let probability_ppm = cheapest
            .get("probability_ppm")
            .and_then(Value::as_i64)
            .unwrap_or(0);

        RouteResult {
            success: true,
            error: None,
            route_cost_sats: total_cost_sats,
            final_hop_fee_ppm,
            hops: full_route.len() as i64,
            route: full_route,
            probability_ppm,
        }
    }
}

impl Drop for CycleRouter<'_> {
    fn drop(&mut self) {
        self.teardown_exclude_layers();
    }
}
